<!doctype html><html lang=en-us prefix="og: https://ogp.me/ns#"><head><meta charset=utf-8><meta name=viewport content="width=device-width,initial-scale=1,shrink-to-fit=no"><meta http-equiv=X-UA-Compatible content="IE=edge"><title>Discrete Multivariate Analysis - STAT 579 - Problem Set 5 | metafunctor</title><meta name=title content="Discrete Multivariate Analysis - STAT 579 - Problem Set 5 | metafunctor"><meta name=description content="Problem set 5 for discrete multivariate analysis."><meta name=keywords content="machine learning,statistical computing,open source,research,computer science,artificial intelligence"><meta name=author content="Alex Towell"><meta name=robots content="index, follow, max-image-preview:large, max-snippet:-1, max-video-preview:-1"><link rel=canonical href=https://metafunctor.com/probsets/stat579/stat579-hw5/><link rel=alternate hreflang=en href=https://metafunctor.com/probsets/stat579/stat579-hw5/><link rel=alternate hreflang=x-default href=https://metafunctor.com/probsets/stat579/stat579-hw5/><style>*,*::before,*::after{box-sizing:border-box;margin:0;padding:0}html{font-size:16px;-webkit-font-smoothing:antialiased;-moz-osx-font-smoothing:grayscale}body{margin:0;font-family:-apple-system,BlinkMacSystemFont,segoe ui,roboto,sans-serif;font-size:17px;line-height:1.7;color:#2c2c2c;background:#fff}.elegant-header{position:sticky;top:0;z-index:1000;background:rgba(254,254,254,.95);backdrop-filter:blur(10px);border-bottom:1px solid rgba(0,0,0,8%)}.header-inner{max-width:1400px;margin:0 auto;padding:1rem 2rem;display:flex;justify-content:space-between;align-items:center}.site-logo{font-size:1.5rem;font-weight:700;color:#2c2c2c;text-decoration:none}.nav-primary ul{display:flex;gap:2rem;list-style:none}.nav-primary a{font-size:.9rem;font-weight:500;color:#4a4a4a;text-decoration:none}.hero-elegant{padding:5rem 2rem;text-align:center;background:linear-gradient(180deg,#fafafa 0%,#ffffff 100%)}.hero-title{font-size:3.5rem;font-weight:700;margin-bottom:1rem;background:linear-gradient(135deg,#2c2c2c 0%,#003d7a 100%);-webkit-background-clip:text;-webkit-text-fill-color:transparent;background-clip:text}.hero-subtitle{font-size:1.25rem;color:#4a4a4a;max-width:600px;margin:0 auto 3rem}.skip-to-main{position:absolute;top:-100px;left:0;background:#0050a0;color:#fff;padding:.5rem 1rem;text-decoration:none;font-weight:600;z-index:10000}.skip-to-main:focus{top:0}.preload *{transition:none!important}</style><link rel=preconnect href=https://fonts.googleapis.com><link rel=preconnect href=https://fonts.gstatic.com crossorigin><link rel=preconnect href=https://cdnjs.cloudflare.com crossorigin><link rel=dns-prefetch href=https://www.google-analytics.com><link rel=dns-prefetch href=https://cdn.jsdelivr.net><meta property="og:type" content="article"><meta property="og:url" content="https://metafunctor.com/probsets/stat579/stat579-hw5/"><meta property="og:title" content="Discrete Multivariate Analysis - STAT 579 - Problem Set 5"><meta property="og:description" content="Problem set 5 for discrete multivariate analysis."><meta property="og:image" content="https://metafunctor.com/images/og-image.jpg"><meta property="og:image:width" content="1200"><meta property="og:image:height" content="630"><meta property="og:site_name" content="metafunctor"><meta property="og:locale" content="en_US"><meta property="article:author" content="Alex Towell"><meta property="article:published_time" content="2021-05-01T00:00:00Z"><meta property="article:modified_time" content="2025-12-16T19:22:58-06:00"><meta property="article:tag" content="statistics"><meta property="article:tag" content="multivariate-analysis"><meta property="article:tag" content="categorical-data"><meta property="article:tag" content="R"><meta property="article:tag" content="SIUe"><meta name=twitter:card content="summary_large_image"><meta name=twitter:url content="https://metafunctor.com/probsets/stat579/stat579-hw5/"><meta name=twitter:title content="Discrete Multivariate Analysis - STAT 579 - Problem Set 5"><meta name=twitter:description content="Problem set 5 for discrete multivariate analysis."><meta name=twitter:image content="https://metafunctor.com/images/og-image.jpg"><meta name=twitter:site content="@queelius"><meta name=twitter:creator content="@queelius"><script type=application/ld+json>{"@context":"https://schema.org","@graph":[{"@type":"Article","@id":"https:\/\/metafunctor.com\/probsets\/stat579\/stat579-hw5\/#primaryContent","headline":"Discrete Multivariate Analysis - STAT 579 - Problem Set 5","description":"Problem set 5 for discrete multivariate analysis.","url":"https:\/\/metafunctor.com\/probsets\/stat579\/stat579-hw5\/","inLanguage":"en-US","datePublished":"2021-05-01T00:00:00Z","dateModified":"2025-12-16T19:22:58-06:00","wordCount":1149,"timeRequired":"PT6M","author":{"@type":"Person","@id":"https:\/\/metafunctor.com\/#author","name":"Alex Towell","url":"https:\/\/metafunctor.com\/about/"},"publisher":{"@type":"Organization","@id":"https:\/\/metafunctor.com\/#organization","name":"metafunctor","url":"https:\/\/metafunctor.com\/","logo":{"@type":"ImageObject","url":"https:\/\/metafunctor.com\/images\/og-image.jpg"}},"keywords":["statistics","multivariate-analysis","categorical-data","R","SIUe"]},{"@type":"BreadcrumbList","@id":"https:\/\/metafunctor.com\/probsets\/stat579\/stat579-hw5\/#breadcrumb","itemListElement":[{"@type":"ListItem","position":1,"name":"Home","item":"https:\/\/metafunctor.com\/"},{"@type":"ListItem","position":2,"name":"STAT 579 - Discrete Multivariate Analysis - SIUe - Spring 2021","item":"https:\/\/metafunctor.com\/probsets\/stat579\/"},{"@type":"ListItem","position":3,"name":"Discrete Multivariate Analysis - STAT 579 - Problem Set 5","item":"https:\/\/metafunctor.com\/probsets\/stat579\/stat579-hw5\/"}]}]}</script><link rel=preload href="https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700;800&family=Lora:ital,wght@0,400;0,600;0,700;1,400&family=JetBrains+Mono:wght@400;500&display=swap" as=style><link href="https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700;800&family=Lora:ital,wght@0,400;0,600;0,700;1,400&family=JetBrains+Mono:wght@400;500&display=swap" rel=stylesheet media=print onload='this.media="all"'><noscript><link href="https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700;800&family=Lora:ital,wght@0,400;0,600;0,700;1,400&family=JetBrains+Mono:wght@400;500&display=swap" rel=stylesheet></noscript><link rel=stylesheet href=../../../css/refined-elegant.css><link rel=stylesheet href=../../../css/micro-interactions.css><link rel=stylesheet href=../../../css/elegant.css media=print onload='this.media="all"'><link rel=stylesheet href=../../../css/custom.css><link rel=stylesheet href=../../../css/beautify.css><link rel=stylesheet href=https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css crossorigin=anonymous><link rel=stylesheet href=https://cdn.jsdelivr.net/npm/katex@0.16.8/dist/katex.min.css><script defer src=https://cdn.jsdelivr.net/npm/katex@0.16.8/dist/katex.min.js></script><script defer src=https://cdn.jsdelivr.net/npm/katex@0.16.8/dist/contrib/auto-render.min.js></script><script>document.addEventListener("DOMContentLoaded",function(){renderMathInElement(document.body,{delimiters:[{left:"$$",right:"$$",display:!0},{left:"\\[",right:"\\]",display:!0},{left:"$",right:"$",display:!1},{left:"\\(",right:"\\)",display:!1}]})})</script><script defer src=https://cdn.jsdelivr.net/npm/fuse.js@7.0.0/dist/fuse.min.js></script><script async src="https://www.googletagmanager.com/gtag/js?id=G-E08ZXTFTTY"></script><script>var doNotTrack=!1,dnt=navigator.doNotTrack||window.doNotTrack||navigator.msDoNotTrack,doNotTrack=dnt=="1"||dnt=="yes";if(!doNotTrack){window.dataLayer=window.dataLayer||[];function gtag(){dataLayer.push(arguments)}gtag("js",new Date),gtag("config","G-E08ZXTFTTY")}</script><meta name=generator content="Hugo 0.156.0"></head><body><a href=#main-content class=skip-to-main>Skip to main content</a><header class=elegant-header role=banner><div class=header-inner><div class=site-identity><a href=https://metafunctor.com/ class=site-logo aria-label="metafunctor home">metafunctor</a>
<span class=site-tagline aria-label="Site tagline">Research · Coding</span></div><nav class=nav-primary role=navigation aria-label="Main navigation"><button class=mobile-menu-toggle aria-label="Toggle mobile menu" aria-expanded=false>
<span></span>
<span></span>
<span></span></button><ul role=list><li><a href=https://metafunctor.com/>Home</a></li><li><a href=https://metafunctor.com/post/>Posts</a></li><li><a href=https://metafunctor.com/series/>Series</a></li><li class=nav-dropdown><a href=# class=dropdown-toggle aria-haspopup=true aria-expanded=false>Academic <i class="fas fa-chevron-down dropdown-icon"></i></a><ul class=dropdown-menu role=menu><li role=menuitem><a href=https://metafunctor.com/papers/>Papers</a></li><li role=menuitem><a href=https://metafunctor.com/publications/>Publications</a></li><li role=menuitem><a href=https://metafunctor.com/research/>Research</a></li></ul></li><li class=nav-dropdown><a href=# class=dropdown-toggle aria-haspopup=true aria-expanded=false>Creative <i class="fas fa-chevron-down dropdown-icon"></i></a><ul class=dropdown-menu role=menu><li role=menuitem><a href=https://metafunctor.com/writing/>Writing</a></li><li role=menuitem><a href=https://metafunctor.com/media/>Media</a></li></ul></li><li><a href=https://metafunctor.com/projects/>Projects</a></li><li><a href=https://metafunctor.com/about/>About</a></li><li><a href=https://metafunctor.com/search/><i class="fas fa-search" aria-hidden=true></i><span class=sr-only>Search</span></a></li></ul></nav></div></header><style>.nav-dropdown{position:relative}.dropdown-toggle{display:flex;align-items:center;gap:.35rem;cursor:pointer}.dropdown-icon{font-size:.6rem;transition:transform .2s ease}.nav-dropdown.open .dropdown-icon{transform:rotate(180deg)}.dropdown-menu{position:absolute;top:calc(100% + .5rem);left:50%;transform:translateX(-50%);min-width:160px;background:#fff;border:1px solid rgba(0,0,0,.1);border-radius:8px;box-shadow:0 4px 20px rgba(0,0,0,.15);padding:.5rem 0;opacity:0;visibility:hidden;pointer-events:none;transition:opacity .15s ease;z-index:9999;list-style:none}.nav-dropdown.open .dropdown-menu{opacity:1!important;visibility:visible!important;pointer-events:auto!important;transform:translateX(-50%)translateY(0)scale(1)!important}.dropdown-menu::before{content:'';position:absolute;top:-6px;left:50%;transform:translateX(-50%);border-left:6px solid transparent;border-right:6px solid transparent;border-bottom:6px solid #fff;filter:drop-shadow(0 -1px 1px rgba(0,0,0,.1))}.dropdown-menu li{margin:0}.nav-dropdown .dropdown-menu a{display:block!important;padding:.6rem 1.25rem!important;color:#4a4a4a!important;font-size:.875rem!important;font-weight:500!important;text-decoration:none!important;transition:all .15s ease!important;white-space:nowrap!important;cursor:pointer!important;pointer-events:auto!important}.nav-dropdown .dropdown-menu a:hover{background:#f3f4f6!important;color:#4f46e5!important}.nav-dropdown .dropdown-menu a.active{color:#4f46e5!important}@media(max-width:768px){.dropdown-menu{position:static;transform:none;box-shadow:none;border:none;background:rgba(0,0,0,3%);border-radius:0;padding:0;max-height:0;overflow:hidden;opacity:1;visibility:visible;transition:max-height .2s ease}.dropdown-menu::before{display:none}.nav-dropdown.open .dropdown-menu{max-height:300px;padding:.5rem 0}.dropdown-menu a{padding:.5rem 1.5rem .5rem 2rem;font-size:.85rem}}</style><script>document.addEventListener("DOMContentLoaded",function(){const e=document.querySelectorAll(".nav-dropdown");e.forEach(t=>{const n=t.querySelector(".dropdown-toggle");n.addEventListener("click",function(n){n.preventDefault(),n.stopPropagation();const s=t.classList.contains("open");e.forEach(e=>e.classList.remove("open")),s||t.classList.add("open")})}),document.addEventListener("click",function(t){t.target.closest(".nav-dropdown")||e.forEach(e=>e.classList.remove("open"))}),document.addEventListener("keydown",function(t){t.key==="Escape"&&e.forEach(e=>e.classList.remove("open"))})})</script><nav aria-label=Breadcrumb class=breadcrumb-nav><ol class=breadcrumb itemscope itemtype=https://schema.org/BreadcrumbList><li itemprop=itemListElement itemscope itemtype=https://schema.org/ListItem><a itemprop=item href=https://metafunctor.com/><span itemprop=name>Home</span>
</a><meta itemprop=position content="1"></li><li itemprop=itemListElement itemscope itemtype=https://schema.org/ListItem><span class=breadcrumb-separator>/</span>
<a itemprop=item href=https://metafunctor.com/probsets/stat579/><span itemprop=name>STAT 579 - Discrete Multivariate Analysis - SIUe - Spring 2021</span>
</a><meta itemprop=position content="2"></li><li itemprop=itemListElement itemscope itemtype=https://schema.org/ListItem><span class=breadcrumb-separator>/</span>
<span itemprop=name aria-current=page>Discrete Multivariate Analysis - STAT 579 - Problem Set 5</span>
<meta itemprop=position content="3"></li></ol></nav><main id=main-content role=main aria-label="Main content"><div class=main-container><div class=single-post-layout><aside class=post-sidebar><aside class=toc-wrapper aria-label="Table of contents"><nav class=table-of-contents><h2 class=toc-title>Table of Contents</h2><div class=toc-content><nav id=TableOfContents><ul><li><a href=#part-a>Part (a)</a></li><li><a href=#part-b>Part (b)</a></li><li><a href=#part-c>Part (c)</a></li><li><a href=#part-d>Part (d)</a></li></ul><ul><li><a href=#function-used-to-compute-interval-estimates-for-this-problem>Function used to compute interval estimates for this problem.</a></li><li><a href=#part-a-1>Part (a)</a></li><li><a href=#part-b-1>Part (b)</a></li></ul></nav></div></nav></aside><style>.toc-wrapper{position:sticky;top:80px;max-height:calc(100vh - 100px);overflow-y:auto;padding:var(--space-lg);background:var(--paper-dark);border:var(--border-width)solid var(--border-color);border-radius:var(--radius-lg);margin-bottom:var(--space-xl)}.toc-title{font-size:1rem;font-weight:600;color:var(--ink);margin:0 0 var(--space-md);text-transform:uppercase;letter-spacing:.05em;font-size:.875rem}.toc-content{font-size:.9rem}.toc-content ul{list-style:none;padding-left:0;margin:0}.toc-content>ul{border-left:2px solid var(--border-color);padding-left:var(--space-md)}.toc-content li{margin-bottom:var(--space-sm)}.toc-content a{color:var(--ink-light);text-decoration:none;transition:color var(--transition-fast);display:block;padding:var(--space-xs)0}.toc-content a:hover{color:var(--accent)}.toc-content ul ul{margin-top:var(--space-sm);padding-left:var(--space-md)}@media(max-width:1024px){.toc-wrapper{position:relative;top:0;max-height:none}}</style><script>document.addEventListener("DOMContentLoaded",function(){const e=document.querySelectorAll(".toc-content a"),n=Array.from(e).map(e=>{const t=e.getAttribute("href").substring(1);return document.getElementById(t)}).filter(e=>e!==null);function t(){let t="";n.forEach(e=>{const n=e.offsetTop,s=window.scrollY+100;s>=n&&(t=e.getAttribute("id"))}),e.forEach(e=>{e.classList.remove("active"),e.getAttribute("href")==="#"+t?(e.classList.add("active"),e.style.color="var(--accent)",e.style.fontWeight="600"):(e.style.color="",e.style.fontWeight="")})}window.addEventListener("scroll",t),t()})</script></aside><article class=single-post itemscope itemtype=https://schema.org/Article><header class=post-header><h1 class=post-title itemprop=headline>Discrete Multivariate Analysis - STAT 579 - Problem Set 5</h1><div class=post-meta><span class=post-date><i class="far fa-calendar" aria-hidden=true></i>
<time datetime=2021-05-01T00:00:00Z itemprop=datePublished>May 1, 2021
</time></span><span class=post-author itemprop=author itemscope itemtype=https://schema.org/Person><i class="far fa-user" aria-hidden=true></i>
<span itemprop=name>Alex Towell (lex@metafunctor.com)</span>
</span><span class=post-reading-time><i class="far fa-clock" aria-hidden=true></i>
6 min read
</span><span class=post-updated><i class="far fa-edit" aria-hidden=true></i>
Updated: <time datetime=2025-12-16T19:22:58-06:00 itemprop=dateModified>December 16, 2025</time></span></div><div class=tags role=list><a href=https://metafunctor.com/tags/statistics/ class=tag role=listitem>statistics</a>
<a href=https://metafunctor.com/tags/multivariate-analysis/ class=tag role=listitem>multivariate-analysis</a>
<a href=https://metafunctor.com/tags/categorical-data/ class=tag role=listitem>categorical-data</a>
<a href=https://metafunctor.com/tags/r/ class=tag role=listitem>R</a>
<a href=https://metafunctor.com/tags/siue/ class=tag role=listitem>SIUe</a></div></header><div class=content itemprop=articleBody><h1 id=problem-1>Problem 1</h1><p>Consider data from a prospective study on the relationship between daily aspirin use and the onset of heart disease.</p><pre><code>        Disease   No Disease   Total
</code></pre><hr><p>Placebo 28 656 684
Aspirin 18 658 676</p><h2 id=part-a>Part (a)</h2><p>[\[\begin{aligned} \sigma^2\!\left(\log \hat{\operatorname{RR}}\right) &= \frac{1}{n_{1 1}} - \frac{1}{n_{1+}} + \frac{1}{n_{2 1}} - \frac{1}{n_{2+}}\\ &= \frac{1}{28} - \frac{1}{684} + \frac{1}{18} - \frac{1}{658}\\ &\approx 0.883\,. \end{aligned}\]]{.math .display}</p><h2 id=part-b>Part (b)</h2><p>[\[\sigma\!\left(\log \hat{\operatorname{RR}}\right) = \sqrt{\sigma^2(\log \hat{\operatorname{RR}})} \approx 0.297\,.\]]{.math .display}</p><h2 id=part-c>Part (c)</h2><p>The relative risk [\(\operatorname{RR}\)]{.math .inline} is defined as [\[\operatorname{RR}\coloneqq \frac{\pi_1}{\pi_2}\]]{.math .display} The MLE of [\(\log \operatorname{RR}\)]{.math .inline} is given by [\[\hat{\operatorname{RR}} = \frac{\hat\pi_1}{\hat\pi_2} = \frac{n_{1 1}}{n_{1+}} \frac{n_{2+}}{n_{2 1}} = \frac{28}{676} \times \frac{684}{18} \approx 1.574\,.\]]{.math .display} By the invariance property of the MLE, if [\(\hat\theta\)]{.math .inline} is an MLE of [\(\theta\)]{.math .inline} then [\(\operatorname{g}(\theta)\)]{.math .inline} is an MLE of [\(\operatorname{g}(\hat\theta)\)]{.math .inline}. Thus, [\[\log \hat{\operatorname{RR}} = \log \hat{\operatorname{RR}} \approx 0.454\,.\]]{.math .display} A confidence interval for [\(\log \operatorname{RR}\)]{.math .inline} is thus [\[\operatorname{CI}(\log\operatorname{RR}) = \log \hat{\operatorname{RR}} \pm z_{\alpha/2} \sigma(\log \hat{\operatorname{RR}})\,.\]]{.math .display} Letting [\(\alpha = 0.05\)]{.math .inline} and substituting in the values for [\(\log \hat{\operatorname{RR}}\)]{.math .inline} and [\(\sigma(\log \hat{\operatorname{RR}})\)]{.math .inline}, we get the result [\[\operatorname{CI}(\log\hat{\operatorname{RR}}) = 0.454 \pm 1.96 \times 0.297= [-0.128,1.036]\,.\]]{.math .display}</p><h2 id=part-d>Part (d)</h2><p>We take the inverse of the logarithm and obtain the result [\[\operatorname{CI}(\operatorname{RR}) = [e^{-0.128},e^{1.036}] = [0.880,2.818]\,.\]]{.math .display}</p><h1 id=problem-2>Problem 2</h1><p>A diagnostic test for Covid antibodies is being studied. For a sample of [\(n = 122\)]{.math .inline} specimens with antibodies known to be present, the test returned [\(y = 103\)]{.math .inline} positive results. For a sample of [\(n = 401\)]{.math .inline} specimens absent any antibodies, the test returned [\(y = 399\)]{.math .inline} negative results.</p><h2 id=function-used-to-compute-interval-estimates-for-this-problem>Function used to compute interval estimates for this problem.</h2><p>snugshade
Highlighting
[<em># this program performs Bayesian inference for a binomial probability</em>]{style=&ldquo;color: 0.56,0.35,0.01&rdquo;} [<em># - y is the number of successes</em>]{style=&ldquo;color: 0.56,0.35,0.01&rdquo;} [<em># - n is the number of trials</em>]{style=&ldquo;color: 0.56,0.35,0.01&rdquo;} [<em># - alpha is the sum of the tail probabilities</em>]{style=&ldquo;color: 0.56,0.35,0.01&rdquo;} [<em>#</em>]{style=&ldquo;color: 0.56,0.35,0.01&rdquo;} [<em># we also compute a classical interval using normality assumptions of the mle.</em>]{style=&ldquo;color: 0.56,0.35,0.01&rdquo;} binomial_bayesian [&lt;-]{style=&ldquo;color: 0.56,0.35,0.01&rdquo;} [function]{style=&ldquo;color: 0.13,0.29,0.53&rdquo;}(y,n,[alpha=]{style=&ldquo;color: 0.13,0.29,0.53&rdquo;}.[05]{style=&ldquo;color: 0.00,0.00,0.81&rdquo;}) { [<em># compute the maximum likelihood estimator</em>]{style=&ldquo;color: 0.56,0.35,0.01&rdquo;} mle [=]{style=&ldquo;color: 0.56,0.35,0.01&rdquo;} y[<strong>/</strong>]{style=&ldquo;color: 0.81,0.36,0.00&rdquo;}n mle_var [=]{style=&ldquo;color: 0.56,0.35,0.01&rdquo;} mle[<em><strong><strong>]{style=&ldquo;color: 0.81,0.36,0.00&rdquo;}([1]{style=&ldquo;color: 0.00,0.00,0.81&rdquo;}[</strong>-</strong>]{style=&ldquo;color: 0.81,0.36,0.00&rdquo;}mle)[</em><em>/</em>*]{style=&ldquo;color: 0.81,0.36,0.00&rdquo;}n mle_sd [=]{style=&ldquo;color: 0.56,0.35,0.01&rdquo;} [sqrt]{style=&ldquo;color: 0.13,0.29,0.53&rdquo;}(mle_var)</p><p>t0 [=]{style=&ldquo;color: 0.56,0.35,0.01&rdquo;} [qt]{style=&ldquo;color: 0.13,0.29,0.53&rdquo;}([1]{style=&ldquo;color: 0.00,0.00,0.81&rdquo;}[<strong>-</strong>]{style=&ldquo;color: 0.81,0.36,0.00&rdquo;}alpha[<strong>/</strong>]{style=&ldquo;color: 0.81,0.36,0.00&rdquo;}[2]{style=&ldquo;color: 0.00,0.00,0.81&rdquo;}, n[-1]{style=&ldquo;color: 0.00,0.00,0.81&rdquo;}) L [=]{style=&ldquo;color: 0.56,0.35,0.01&rdquo;} mle [<strong>-</strong>]{style=&ldquo;color: 0.81,0.36,0.00&rdquo;} mle_sd[<em><strong><strong>]{style=&ldquo;color: 0.81,0.36,0.00&rdquo;}t0 U [=]{style=&ldquo;color: 0.56,0.35,0.01&rdquo;} mle [</strong>+</strong>]{style=&ldquo;color: 0.81,0.36,0.00&rdquo;} mle_sd[</em>****]{style=&ldquo;color: 0.81,0.36,0.00&rdquo;}t0</p><p>[<em># define the beta distribution parameters</em>]{style=&ldquo;color: 0.56,0.35,0.01&rdquo;} a[=]{style=&ldquo;color: 0.56,0.35,0.01&rdquo;}y[<strong>+</strong>]{style=&ldquo;color: 0.81,0.36,0.00&rdquo;}[1]{style=&ldquo;color: 0.00,0.00,0.81&rdquo;} b[=]{style=&ldquo;color: 0.56,0.35,0.01&rdquo;}n[<strong>-</strong>]{style=&ldquo;color: 0.81,0.36,0.00&rdquo;}y[<strong>+</strong>]{style=&ldquo;color: 0.81,0.36,0.00&rdquo;}[1]{style=&ldquo;color: 0.00,0.00,0.81&rdquo;}</p><p>[<em># computing a confidence interval by taking the upper and lower percentiles of</em>]{style=&ldquo;color: 0.56,0.35,0.01&rdquo;} [<em># the beta distribution computing the median to represent the center of the</em>]{style=&ldquo;color: 0.56,0.35,0.01&rdquo;} [<em># distribution</em>]{style=&ldquo;color: 0.56,0.35,0.01&rdquo;} lower [=]{style=&ldquo;color: 0.56,0.35,0.01&rdquo;} [qbeta]{style=&ldquo;color: 0.13,0.29,0.53&rdquo;}(alpha[<strong>/</strong>]{style=&ldquo;color: 0.81,0.36,0.00&rdquo;}[2]{style=&ldquo;color: 0.00,0.00,0.81&rdquo;},a,b) median [=]{style=&ldquo;color: 0.56,0.35,0.01&rdquo;} [qbeta]{style=&ldquo;color: 0.13,0.29,0.53&rdquo;}(.[5]{style=&ldquo;color: 0.00,0.00,0.81&rdquo;},a,b) upper [=]{style=&ldquo;color: 0.56,0.35,0.01&rdquo;} [qbeta]{style=&ldquo;color: 0.13,0.29,0.53&rdquo;}([1]{style=&ldquo;color: 0.00,0.00,0.81&rdquo;}[<strong>-</strong>]{style=&ldquo;color: 0.81,0.36,0.00&rdquo;}alpha[<strong>/</strong>]{style=&ldquo;color: 0.81,0.36,0.00&rdquo;}[2]{style=&ldquo;color: 0.00,0.00,0.81&rdquo;},a,b) [cat]{style=&ldquo;color: 0.13,0.29,0.53&rdquo;}(["bayesian estimate: "]{style=&ldquo;color: 0.31,0.60,0.02&rdquo;}, [c]{style=&ldquo;color: 0.13,0.29,0.53&rdquo;}(lower,median,upper),["]{style=&ldquo;color: 0.31,0.60,0.02&rdquo;}[<strong>\n</strong>]{style=&ldquo;color: 0.81,0.36,0.00&rdquo;}["]{style=&ldquo;color: 0.31,0.60,0.02&rdquo;}) [cat]{style=&ldquo;color: 0.13,0.29,0.53&rdquo;}(["mle confidence interval estimate: "]{style=&ldquo;color: 0.31,0.60,0.02&rdquo;}, [c]{style=&ldquo;color: 0.13,0.29,0.53&rdquo;}(L,mle,U),["]{style=&ldquo;color: 0.31,0.60,0.02&rdquo;}[<strong>\n</strong>]{style=&ldquo;color: 0.81,0.36,0.00&rdquo;}["]{style=&ldquo;color: 0.31,0.60,0.02&rdquo;})</p><p>[<em># create a grid of p for plotting. you may change to a smaller range than from</em>]{style=&ldquo;color: 0.56,0.35,0.01&rdquo;} [<em># 0 to 1 to see the distribution better</em>]{style=&ldquo;color: 0.56,0.35,0.01&rdquo;} p [=]{style=&ldquo;color: 0.56,0.35,0.01&rdquo;} [seq]{style=&ldquo;color: 0.13,0.29,0.53&rdquo;}([from=]{style=&ldquo;color: 0.13,0.29,0.53&rdquo;}[max]{style=&ldquo;color: 0.13,0.29,0.53&rdquo;}([0]{style=&ldquo;color: 0.00,0.00,0.81&rdquo;},lower[<em><strong><strong>]{style=&ldquo;color: 0.81,0.36,0.00&rdquo;}.[965]{style=&ldquo;color: 0.00,0.00,0.81&rdquo;}),[to=]{style=&ldquo;color: 0.13,0.29,0.53&rdquo;}[min]{style=&ldquo;color: 0.13,0.29,0.53&rdquo;}([1]{style=&ldquo;color: 0.00,0.00,0.81&rdquo;},[1.035]{style=&ldquo;color: 0.00,0.00,0.81&rdquo;}[</strong></strong></em>]{style=&ldquo;color: 0.81,0.36,0.00&rdquo;}upper),[length.out=]{style=&ldquo;color: 0.13,0.29,0.53&rdquo;}[100]{style=&ldquo;color: 0.00,0.00,0.81&rdquo;}) [<em># we are computing the beta density at each point in the grid</em>]{style=&ldquo;color: 0.56,0.35,0.01&rdquo;} posterior [=]{style=&ldquo;color: 0.56,0.35,0.01&rdquo;} [dbeta]{style=&ldquo;color: 0.13,0.29,0.53&rdquo;}(p,a,b)</p><p>ps [=]{style=&ldquo;color: 0.56,0.35,0.01&rdquo;} [rnorm]{style=&ldquo;color: 0.13,0.29,0.53&rdquo;}([n=]{style=&ldquo;color: 0.13,0.29,0.53&rdquo;}[1000000]{style=&ldquo;color: 0.00,0.00,0.81&rdquo;},[mean=]{style=&ldquo;color: 0.13,0.29,0.53&rdquo;}mle,[sd=]{style=&ldquo;color: 0.13,0.29,0.53&rdquo;}mle_sd)</p><p>[<em># plotting the beta density, higher values of the curve represent stronger data</em>]{style=&ldquo;color: 0.56,0.35,0.01&rdquo;} [<em># evidence</em>]{style=&ldquo;color: 0.56,0.35,0.01&rdquo;} [plot]{style=&ldquo;color: 0.13,0.29,0.53&rdquo;}(p,posterior,[type =]{style=&ldquo;color: 0.13,0.29,0.53&rdquo;} ["l"]{style=&ldquo;color: 0.31,0.60,0.02&rdquo;},[col=]{style=&ldquo;color: 0.13,0.29,0.53&rdquo;}["blue"]{style=&ldquo;color: 0.31,0.60,0.02&rdquo;})</p><p>[lines]{style=&ldquo;color: 0.13,0.29,0.53&rdquo;}([density]{style=&ldquo;color: 0.13,0.29,0.53&rdquo;}(ps),[col=]{style=&ldquo;color: 0.13,0.29,0.53&rdquo;}["orange"]{style=&ldquo;color: 0.31,0.60,0.02&rdquo;})</p><p>[points]{style=&ldquo;color: 0.13,0.29,0.53&rdquo;}(median,[0]{style=&ldquo;color: 0.00,0.00,0.81&rdquo;},[col=]{style=&ldquo;color: 0.13,0.29,0.53&rdquo;}["blue"]{style=&ldquo;color: 0.31,0.60,0.02&rdquo;},[pch=]{style=&ldquo;color: 0.13,0.29,0.53&rdquo;}["*"]{style=&ldquo;color: 0.31,0.60,0.02&rdquo;}) [points]{style=&ldquo;color: 0.13,0.29,0.53&rdquo;}([c]{style=&ldquo;color: 0.13,0.29,0.53&rdquo;}(lower,upper),[c]{style=&ldquo;color: 0.13,0.29,0.53&rdquo;}([0]{style=&ldquo;color: 0.00,0.00,0.81&rdquo;},[0]{style=&ldquo;color: 0.00,0.00,0.81&rdquo;}),,[col=]{style=&ldquo;color: 0.13,0.29,0.53&rdquo;}["blue"]{style=&ldquo;color: 0.31,0.60,0.02&rdquo;},[pch=]{style=&ldquo;color: 0.13,0.29,0.53&rdquo;}["|"]{style=&ldquo;color: 0.31,0.60,0.02&rdquo;})</p><p>[<em># lets plot the mle and confidence interval using t-score</em>]{style=&ldquo;color: 0.56,0.35,0.01&rdquo;} [points]{style=&ldquo;color: 0.13,0.29,0.53&rdquo;}(mle,[0]{style=&ldquo;color: 0.00,0.00,0.81&rdquo;},[col=]{style=&ldquo;color: 0.13,0.29,0.53&rdquo;}["orange"]{style=&ldquo;color: 0.31,0.60,0.02&rdquo;},[pch=]{style=&ldquo;color: 0.13,0.29,0.53&rdquo;}["*"]{style=&ldquo;color: 0.31,0.60,0.02&rdquo;}) [points]{style=&ldquo;color: 0.13,0.29,0.53&rdquo;}([c]{style=&ldquo;color: 0.13,0.29,0.53&rdquo;}(L,U),[c]{style=&ldquo;color: 0.13,0.29,0.53&rdquo;}([0]{style=&ldquo;color: 0.00,0.00,0.81&rdquo;},[0]{style=&ldquo;color: 0.00,0.00,0.81&rdquo;}),,[col=]{style=&ldquo;color: 0.13,0.29,0.53&rdquo;}["orange"]{style=&ldquo;color: 0.31,0.60,0.02&rdquo;},[pch=]{style=&ldquo;color: 0.13,0.29,0.53&rdquo;}["|"]{style=&ldquo;color: 0.31,0.60,0.02&rdquo;}) }</p><h2 id=part-a-1>Part (a)</h2><p>Given that antibodies are present, the probability that a positive test result is observed is given by the sensitivity [\(\delta\)]{.math .inline}.</p><p>In classical statistics, while the probability [\(\delta\)]{.math .inline} is not known, the MLE estimator is [\(\hat\delta = \frac{y}{n}\)]{.math .inline} which is asymptotically normal under regularity conditions.</p><p>We compare it with the Bayesian approach, which does not assume normality. The following R function call computes the Bayesian interval estimate for a binomial probability. For comparison, we also compute the confidence interval for the MLE using classical techniques that rely upon the normality assumption of the MLE.</p><p>snugshade
Highlighting
[binomial_bayesian]{style=&ldquo;color: 0.13,0.29,0.53&rdquo;}([y=]{style=&ldquo;color: 0.13,0.29,0.53&rdquo;}[103]{style=&ldquo;color: 0.00,0.00,0.81&rdquo;},[n=]{style=&ldquo;color: 0.13,0.29,0.53&rdquo;}[122]{style=&ldquo;color: 0.00,0.00,0.81&rdquo;},[alpha=]{style=&ldquo;color: 0.13,0.29,0.53&rdquo;}.[05]{style=&ldquo;color: 0.00,0.00,0.81&rdquo;})</p><pre><code>## bayesian estimate:  0.7693298 0.8405335 0.8977577 
## mle confidence interval estimate:  0.7792689 0.8442623 0.9092557
</code></pre><p>The maximum likelihood estimator [\(\hat\delta\)]{.math .inline} is [\(0.844\)]{.math .inline} with an [\(\alpha=0.05\)]{.math .inline} confidence interval [\([0.779,0.909]\)]{.math .inline}.</p><p>The point estimator of [\(\delta\)]{.math .inline} using the Bayesian approach, the [\(50\%\)]{.math .inline}-percentile, is [\(0.841\)]{.math .inline} with an interval estimate [\([0.769,0.898]\)]{.math .inline}.</p><p>The maximum likelihood estimator and its corresponding density plot and confidence interval is plotted in <em>orange</em> and the Bayesian estimator is plotted in <em>blue</em>.</p><h2 id=part-b-1>Part (b)</h2><p>We do the same thing as in part (A).</p><p>snugshade
Highlighting
[binomial_bayesian]{style=&ldquo;color: 0.13,0.29,0.53&rdquo;}([y=]{style=&ldquo;color: 0.13,0.29,0.53&rdquo;}[399]{style=&ldquo;color: 0.00,0.00,0.81&rdquo;},[n=]{style=&ldquo;color: 0.13,0.29,0.53&rdquo;}[401]{style=&ldquo;color: 0.00,0.00,0.81&rdquo;},[alpha=]{style=&ldquo;color: 0.13,0.29,0.53&rdquo;}.[05]{style=&ldquo;color: 0.00,0.00,0.81&rdquo;})</p><pre><code>## bayesian estimate:  0.9821445 0.9933537 0.9984584 
## mle confidence interval estimate:  0.9880966 0.9950125 1.001928
</code></pre><p>The maximum likelihood estimator [\(\hat\delta\)]{.math .inline} is [\(0.844\)]{.math .inline} with an [\(\alpha=0.05\)]{.math .inline} confidence interval [\([0.982,1.002]\)]{.math .inline}</p><p>The point estimator of [\(\delta\)]{.math .inline} using the Bayesian approach, the [\(50\%\)]{.math .inline}-percentile, is [\(0.993\)]{.math .inline} with a [\(\alpha=0.05\)]{.math .inline} interval estimate [\([0.982,0.998]\)]{.math .inline}.</p><p>The maximum likelihood estimator and its corresponding density plot and confidence interval is plotted in <em>orange</em> and the Bayesian estimator is plotted <em>blue</em>.</p><h1 id=problem-3>Problem 3</h1><p>The interval estimate is computed by the following R code.</p><p>snugshade
Highlighting
[<em># this program performs a Bayesian inference for vaccine efficacy</em>]{style=&ldquo;color: 0.56,0.35,0.01&rdquo;} [<em># enter the number of infections in the vaccine group</em>]{style=&ldquo;color: 0.56,0.35,0.01&rdquo;} [<em># and the number of infections in the control group</em>]{style=&ldquo;color: 0.56,0.35,0.01&rdquo;} v [=]{style=&ldquo;color: 0.56,0.35,0.01&rdquo;} [11]{style=&ldquo;color: 0.00,0.00,0.81&rdquo;} c [=]{style=&ldquo;color: 0.56,0.35,0.01&rdquo;} [185]{style=&ldquo;color: 0.00,0.00,0.81&rdquo;}</p><p>[<em># define the beta distribution parameters</em>]{style=&ldquo;color: 0.56,0.35,0.01&rdquo;} a [=]{style=&ldquo;color: 0.56,0.35,0.01&rdquo;} v[<strong>+</strong>]{style=&ldquo;color: 0.81,0.36,0.00&rdquo;}[1]{style=&ldquo;color: 0.00,0.00,0.81&rdquo;} b [=]{style=&ldquo;color: 0.56,0.35,0.01&rdquo;} c[<strong>+</strong>]{style=&ldquo;color: 0.81,0.36,0.00&rdquo;}[1]{style=&ldquo;color: 0.00,0.00,0.81&rdquo;}</p><p>[<em># simulate a very large number of draws from the posterior distribution on p=P(V|I)</em>]{style=&ldquo;color: 0.56,0.35,0.01&rdquo;} [<em># for each simulated p, compute the value for vaccine efficacy VE</em>]{style=&ldquo;color: 0.56,0.35,0.01&rdquo;} p [=]{style=&ldquo;color: 0.56,0.35,0.01&rdquo;} [rbeta]{style=&ldquo;color: 0.13,0.29,0.53&rdquo;}([1000000]{style=&ldquo;color: 0.00,0.00,0.81&rdquo;},a,b) efficacy [=]{style=&ldquo;color: 0.56,0.35,0.01&rdquo;} [1]{style=&ldquo;color: 0.00,0.00,0.81&rdquo;}[<strong>-</strong>]{style=&ldquo;color: 0.81,0.36,0.00&rdquo;}p[<strong>/</strong>]{style=&ldquo;color: 0.81,0.36,0.00&rdquo;}([1]{style=&ldquo;color: 0.00,0.00,0.81&rdquo;}[<strong>-</strong>]{style=&ldquo;color: 0.81,0.36,0.00&rdquo;}p)</p><p>[<em># create a plot of the posterior distribution on VE</em>]{style=&ldquo;color: 0.56,0.35,0.01&rdquo;} [hist]{style=&ldquo;color: 0.13,0.29,0.53&rdquo;}(efficacy,[xlab=]{style=&ldquo;color: 0.13,0.29,0.53&rdquo;}["Efficacy"]{style=&ldquo;color: 0.31,0.60,0.02&rdquo;},[probability =]{style=&ldquo;color: 0.13,0.29,0.53&rdquo;} [TRUE]{style=&ldquo;color: 0.56,0.35,0.01&rdquo;}) [points]{style=&ldquo;color: 0.13,0.29,0.53&rdquo;}([density]{style=&ldquo;color: 0.13,0.29,0.53&rdquo;}(efficacy),[type =]{style=&ldquo;color: 0.13,0.29,0.53&rdquo;} [l]{style=&ldquo;color: 0.31,0.60,0.02&rdquo;})</p><p>pt_est [=]{style=&ldquo;color: 0.56,0.35,0.01&rdquo;} [quantile]{style=&ldquo;color: 0.13,0.29,0.53&rdquo;}(efficacy,[c]{style=&ldquo;color: 0.13,0.29,0.53&rdquo;}(.[5]{style=&ldquo;color: 0.00,0.00,0.81&rdquo;})) [points]{style=&ldquo;color: 0.13,0.29,0.53&rdquo;}(pt_est,[0]{style=&ldquo;color: 0.00,0.00,0.81&rdquo;},[col=]{style=&ldquo;color: 0.13,0.29,0.53&rdquo;}["blue"]{style=&ldquo;color: 0.31,0.60,0.02&rdquo;},[pch=]{style=&ldquo;color: 0.13,0.29,0.53&rdquo;}[8]{style=&ldquo;color: 0.00,0.00,0.81&rdquo;})</p><p>[<em># compute percentiles for a 95% interval estimate</em>]{style=&ldquo;color: 0.56,0.35,0.01&rdquo;} interval_est [=]{style=&ldquo;color: 0.56,0.35,0.01&rdquo;} [quantile]{style=&ldquo;color: 0.13,0.29,0.53&rdquo;}(efficacy,[c]{style=&ldquo;color: 0.13,0.29,0.53&rdquo;}(.[025]{style=&ldquo;color: 0.00,0.00,0.81&rdquo;},.[975]{style=&ldquo;color: 0.00,0.00,0.81&rdquo;})) [points]{style=&ldquo;color: 0.13,0.29,0.53&rdquo;}(interval_est,[c]{style=&ldquo;color: 0.13,0.29,0.53&rdquo;}([0]{style=&ldquo;color: 0.00,0.00,0.81&rdquo;},[0]{style=&ldquo;color: 0.00,0.00,0.81&rdquo;}),[col=]{style=&ldquo;color: 0.13,0.29,0.53&rdquo;}["red"]{style=&ldquo;color: 0.31,0.60,0.02&rdquo;},[pch=]{style=&ldquo;color: 0.13,0.29,0.53&rdquo;}["|"]{style=&ldquo;color: 0.31,0.60,0.02&rdquo;})</p><p>snugshade
Highlighting
[print]{style=&ldquo;color: 0.13,0.29,0.53&rdquo;}(pt_est)</p><pre><code>##       50% 
## 0.9371837
</code></pre><p>snugshade
Highlighting
[print]{style=&ldquo;color: 0.13,0.29,0.53&rdquo;}(interval_est)</p><pre><code>##      2.5%     97.5% 
## 0.8916741 0.9670500
</code></pre><p>We see that the density plot is not quite normal (e.g., non-symmetric). On the plot, we plotted the [\(50\%\)]{.math .inline} in blue and the [\(95\%\)]{.math .inline} interval estimate in red.</p></div><nav class=post-navigation><a href=../../../probsets/stat579/stat579-hw6/ class=nav-prev><span class=nav-label>← Previous</span>
<span class=nav-title>Discrete Multivariate Analysis - STAT 579 - Problem Set 6</span>
</a><a href=../../../probsets/stat579/stat579-hw10/ class=nav-next><span class=nav-label>Next →</span>
<span class=nav-title>Discrete Multivariate Analysis - STAT 579 - Problem Set 10</span></a></nav></article></div></div></main><footer class=elegant-footer role=contentinfo aria-label="Site footer"><div class=footer-content><div class=footer-about><h3>metafunctor</h3><p>Research engineer and computer scientist specializing in machine learning, statistical computing, and open source software development.</p><nav aria-label="Social media links" class=social-links><a href=https://twitter.com/queelius target=_blank rel="noopener noreferrer" aria-label=Twitter><i class="fab fa-twitter" aria-hidden=true></i>
</a><a href=https://github.com/queelius target=_blank rel="noopener noreferrer" aria-label=GitHub><i class="fab fa-github" aria-hidden=true></i>
</a><a href=https://www.linkedin.com/in/alexander-towell-487015151/ target=_blank rel="noopener noreferrer" aria-label=LinkedIn><i class="fab fa-linkedin" aria-hidden=true></i>
</a><a href=../../../index.xml target=_blank rel="noopener noreferrer" aria-label=RSS><i class="fas fa-rss" aria-hidden=true></i>
</a><a href=mailto:lex@metafunctor.com target=_blank rel="noopener noreferrer" aria-label=Email><i class="fas fa-envelope" aria-hidden=true></i>
</a><a href=https://keybase.io/queelius target=_blank rel="noopener noreferrer" aria-label=Keybase><i class="fab fa-keybase" aria-hidden=true></i>
</a><a href=https://www.youtube.com/@queelius target=_blank rel="noopener noreferrer" aria-label=YouTube><i class="fab fa-youtube" aria-hidden=true></i>
</a><a href="https://scholar.google.com/citations?view_op=list_works&amp;hl=en&amp;user=E9mnFzQAAAAJ" target=_blank rel="noopener noreferrer" aria-label="Google Scholar"><i class="fas fa-graduation-cap" aria-hidden=true></i>
</a><a href="https://orcid.org/my-orcid?orcid=0000-0001-6443-9897" target=_blank rel="noopener noreferrer" aria-label=ORCID><i class="fab fa-orcid" aria-hidden=true></i></a></nav></div><nav class=footer-section aria-labelledby=footer-content><h4 id=footer-content>Content</h4><div class=footer-links><a href=https://metafunctor.com/post/>Posts</a>
<a href=https://metafunctor.com/papers/>Papers</a>
<a href=https://metafunctor.com/series/>Series</a>
<a href=https://metafunctor.com/publications/>Publications</a>
<a href=https://metafunctor.com/writing/>Writing</a></div></nav><nav class=footer-section aria-labelledby=footer-code><h4 id=footer-code>Code</h4><div class=footer-links><a href=https://metafunctor.com/projects/>Projects</a>
<a href=https://github.com/queelius target=_blank rel="noopener noreferrer">GitHub</a>
<a href=https://pypi.org/user/queelius/ target=_blank rel="noopener noreferrer">PyPI</a></div></nav><nav class=footer-section aria-labelledby=footer-connect><h4 id=footer-connect>Connect</h4><div class=footer-links><a href=https://metafunctor.com/about/>About</a>
<a href=mailto:lex@metafunctor.com>Contact</a>
<a href=https://metafunctor.com/index.xml type=application/rss+xml>RSS Feed</a></div></nav></div><div class=footer-bottom><p class=copyright>© 2026 Alex Towell. All rights reserved.</p><p class=accessibility-note><a href=#main-content>Back to top</a></p></div></footer><script src=../../../js/performance-optimizations.js defer></script><script src=../../../js/performance-enhancements.js defer></script><script src=../../../js/mobile-menu.js defer></script><script src=../../../js/modern-interactions.js defer></script><script src=../../../js/search.js defer></script><script src=../../../js/reading-progress.js defer></script><script src=../../../js/copy-code.js defer></script><script src=../../../js/anchor-links.js defer></script><button id=back-to-top aria-label="Back to top" style="display:none;position:fixed;bottom:30px;right:30px;z-index:1000;background:linear-gradient(135deg,#667eea 0%,#764ba2 100%);color:#fff;border:none;border-radius:50%;width:50px;height:50px;cursor:pointer;box-shadow:0 4px 15px rgba(102,126,234,.4);transition:all .3s ease">
<i class="fas fa-arrow-up"></i>
</button>
<script>const backToTop=document.getElementById("back-to-top");window.addEventListener("scroll",()=>{window.scrollY>300?backToTop.style.display="block":backToTop.style.display="none"}),backToTop.addEventListener("click",()=>{window.scrollTo({top:0,behavior:"smooth"})})</script><script data-goatcounter=https://queelius.goatcounter.com/count async src=//gc.zgo.at/count.js></script></body></html>