<!doctype html><html lang=en-us prefix="og: https://ogp.me/ns#"><head><meta charset=utf-8><meta name=viewport content="width=device-width,initial-scale=1,shrink-to-fit=no"><meta http-equiv=X-UA-Compatible content="IE=edge"><title>Statistical Methods - STAT 581 - Problem Set 1 | metafunctor</title><meta name=title content="Statistical Methods - STAT 581 - Problem Set 1 | metafunctor"><meta name=description content="An experiment is designed to investigate whether the time to drill holes in rock holes using wet or dry drilling."><meta name=keywords content="machine learning,statistical computing,open source,research,computer science,artificial intelligence"><meta name=author content="Alex Towell"><meta name=robots content="index, follow, max-image-preview:large, max-snippet:-1, max-video-preview:-1"><link rel=canonical href=https://metafunctor.com/probsets/stat581/stat581-hw1/><link rel=alternate hreflang=en href=https://metafunctor.com/probsets/stat581/stat581-hw1/><link rel=alternate hreflang=x-default href=https://metafunctor.com/probsets/stat581/stat581-hw1/><style>*,*::before,*::after{box-sizing:border-box;margin:0;padding:0}html{font-size:16px;-webkit-font-smoothing:antialiased;-moz-osx-font-smoothing:grayscale}body{margin:0;font-family:-apple-system,BlinkMacSystemFont,segoe ui,roboto,sans-serif;font-size:17px;line-height:1.7;color:#2c2c2c;background:#fff}.elegant-header{position:sticky;top:0;z-index:1000;background:rgba(254,254,254,.95);backdrop-filter:blur(10px);border-bottom:1px solid rgba(0,0,0,8%)}.header-inner{max-width:1400px;margin:0 auto;padding:1rem 2rem;display:flex;justify-content:space-between;align-items:center}.site-logo{font-size:1.5rem;font-weight:700;color:#2c2c2c;text-decoration:none}.nav-primary ul{display:flex;gap:2rem;list-style:none}.nav-primary a{font-size:.9rem;font-weight:500;color:#4a4a4a;text-decoration:none}.hero-elegant{padding:5rem 2rem;text-align:center;background:linear-gradient(180deg,#fafafa 0%,#ffffff 100%)}.hero-title{font-size:3.5rem;font-weight:700;margin-bottom:1rem;background:linear-gradient(135deg,#2c2c2c 0%,#003d7a 100%);-webkit-background-clip:text;-webkit-text-fill-color:transparent;background-clip:text}.hero-subtitle{font-size:1.25rem;color:#4a4a4a;max-width:600px;margin:0 auto 3rem}.skip-to-main{position:absolute;top:-100px;left:0;background:#0050a0;color:#fff;padding:.5rem 1rem;text-decoration:none;font-weight:600;z-index:10000}.skip-to-main:focus{top:0}.preload *{transition:none!important}</style><link rel=preconnect href=https://fonts.googleapis.com><link rel=preconnect href=https://fonts.gstatic.com crossorigin><link rel=preconnect href=https://cdnjs.cloudflare.com crossorigin><link rel=dns-prefetch href=https://www.google-analytics.com><link rel=dns-prefetch href=https://cdn.jsdelivr.net><meta property="og:type" content="article"><meta property="og:url" content="https://metafunctor.com/probsets/stat581/stat581-hw1/"><meta property="og:title" content="Statistical Methods - STAT 581 - Problem Set 1"><meta property="og:description" content="An experiment is designed to investigate whether the time to drill holes in rock holes using wet or dry drilling."><meta property="og:image" content="https://metafunctor.com/images/og-image.jpg"><meta property="og:image:width" content="1200"><meta property="og:image:height" content="630"><meta property="og:site_name" content="metafunctor"><meta property="og:locale" content="en_US"><meta property="article:author" content="Alex Towell"><meta property="article:published_time" content="2021-12-01T00:00:00Z"><meta property="article:modified_time" content="2025-12-16T19:22:58-06:00"><meta property="article:tag" content="statistics"><meta property="article:tag" content="statistical-methods"><meta property="article:tag" content="R"><meta property="article:tag" content="SIUe"><meta name=twitter:card content="summary_large_image"><meta name=twitter:url content="https://metafunctor.com/probsets/stat581/stat581-hw1/"><meta name=twitter:title content="Statistical Methods - STAT 581 - Problem Set 1"><meta name=twitter:description content="An experiment is designed to investigate whether the time to drill holes in rock holes using wet or dry drilling."><meta name=twitter:image content="https://metafunctor.com/images/og-image.jpg"><meta name=twitter:site content="@queelius"><meta name=twitter:creator content="@queelius"><script type=application/ld+json>{"@context":"https://schema.org","@graph":[{"@type":"Article","@id":"https:\/\/metafunctor.com\/probsets\/stat581\/stat581-hw1\/#primaryContent","headline":"Statistical Methods - STAT 581 - Problem Set 1","description":"An experiment is designed to investigate whether the time to drill holes in rock holes using wet or dry drilling.","url":"https:\/\/metafunctor.com\/probsets\/stat581\/stat581-hw1\/","inLanguage":"en-US","datePublished":"2021-12-01T00:00:00Z","dateModified":"2025-12-16T19:22:58-06:00","wordCount":1025,"timeRequired":"PT5M","author":{"@type":"Person","@id":"https:\/\/metafunctor.com\/#author","name":"Alex Towell","url":"https:\/\/metafunctor.com\/about/"},"publisher":{"@type":"Organization","@id":"https:\/\/metafunctor.com\/#organization","name":"metafunctor","url":"https:\/\/metafunctor.com\/","logo":{"@type":"ImageObject","url":"https:\/\/metafunctor.com\/images\/og-image.jpg"}},"keywords":["statistics","statistical-methods","R","SIUe"]},{"@type":"BreadcrumbList","@id":"https:\/\/metafunctor.com\/probsets\/stat581\/stat581-hw1\/#breadcrumb","itemListElement":[{"@type":"ListItem","position":1,"name":"Home","item":"https:\/\/metafunctor.com\/"},{"@type":"ListItem","position":2,"name":"STAT 581 - Statistical Methods - SIUe - Fall 2021","item":"https:\/\/metafunctor.com\/probsets\/stat581\/"},{"@type":"ListItem","position":3,"name":"Statistical Methods - STAT 581 - Problem Set 1","item":"https:\/\/metafunctor.com\/probsets\/stat581\/stat581-hw1\/"}]}]}</script><link rel=preload href="https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700;800&family=Lora:ital,wght@0,400;0,600;0,700;1,400&family=JetBrains+Mono:wght@400;500&display=swap" as=style><link href="https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700;800&family=Lora:ital,wght@0,400;0,600;0,700;1,400&family=JetBrains+Mono:wght@400;500&display=swap" rel=stylesheet media=print onload='this.media="all"'><noscript><link href="https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700;800&family=Lora:ital,wght@0,400;0,600;0,700;1,400&family=JetBrains+Mono:wght@400;500&display=swap" rel=stylesheet></noscript><link rel=stylesheet href=../../../css/refined-elegant.css><link rel=stylesheet href=../../../css/micro-interactions.css><link rel=stylesheet href=../../../css/elegant.css media=print onload='this.media="all"'><link rel=stylesheet href=../../../css/custom.css><link rel=stylesheet href=../../../css/beautify.css><link rel=stylesheet href=https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css crossorigin=anonymous><link rel=stylesheet href=https://cdn.jsdelivr.net/npm/katex@0.16.8/dist/katex.min.css><script defer src=https://cdn.jsdelivr.net/npm/katex@0.16.8/dist/katex.min.js></script><script defer src=https://cdn.jsdelivr.net/npm/katex@0.16.8/dist/contrib/auto-render.min.js></script><script>document.addEventListener("DOMContentLoaded",function(){renderMathInElement(document.body,{delimiters:[{left:"$$",right:"$$",display:!0},{left:"\\[",right:"\\]",display:!0},{left:"$",right:"$",display:!1},{left:"\\(",right:"\\)",display:!1}]})})</script><script defer src=https://cdn.jsdelivr.net/npm/fuse.js@7.0.0/dist/fuse.min.js></script><script async src="https://www.googletagmanager.com/gtag/js?id=G-E08ZXTFTTY"></script><script>var doNotTrack=!1,dnt=navigator.doNotTrack||window.doNotTrack||navigator.msDoNotTrack,doNotTrack=dnt=="1"||dnt=="yes";if(!doNotTrack){window.dataLayer=window.dataLayer||[];function gtag(){dataLayer.push(arguments)}gtag("js",new Date),gtag("config","G-E08ZXTFTTY")}</script><meta name=generator content="Hugo 0.156.0"></head><body><a href=#main-content class=skip-to-main>Skip to main content</a><header class=elegant-header role=banner><div class=header-inner><div class=site-identity><a href=https://metafunctor.com/ class=site-logo aria-label="metafunctor home">metafunctor</a>
<span class=site-tagline aria-label="Site tagline">Research · Coding</span></div><nav class=nav-primary role=navigation aria-label="Main navigation"><button class=mobile-menu-toggle aria-label="Toggle mobile menu" aria-expanded=false>
<span></span>
<span></span>
<span></span></button><ul role=list><li><a href=https://metafunctor.com/>Home</a></li><li><a href=https://metafunctor.com/post/>Posts</a></li><li><a href=https://metafunctor.com/series/>Series</a></li><li class=nav-dropdown><a href=# class=dropdown-toggle aria-haspopup=true aria-expanded=false>Academic <i class="fas fa-chevron-down dropdown-icon"></i></a><ul class=dropdown-menu role=menu><li role=menuitem><a href=https://metafunctor.com/papers/>Papers</a></li><li role=menuitem><a href=https://metafunctor.com/publications/>Publications</a></li><li role=menuitem><a href=https://metafunctor.com/research/>Research</a></li></ul></li><li class=nav-dropdown><a href=# class=dropdown-toggle aria-haspopup=true aria-expanded=false>Creative <i class="fas fa-chevron-down dropdown-icon"></i></a><ul class=dropdown-menu role=menu><li role=menuitem><a href=https://metafunctor.com/writing/>Writing</a></li><li role=menuitem><a href=https://metafunctor.com/media/>Media</a></li></ul></li><li><a href=https://metafunctor.com/projects/>Projects</a></li><li><a href=https://metafunctor.com/about/>About</a></li><li><a href=https://metafunctor.com/search/><i class="fas fa-search" aria-hidden=true></i><span class=sr-only>Search</span></a></li></ul></nav></div></header><style>.nav-dropdown{position:relative}.dropdown-toggle{display:flex;align-items:center;gap:.35rem;cursor:pointer}.dropdown-icon{font-size:.6rem;transition:transform .2s ease}.nav-dropdown.open .dropdown-icon{transform:rotate(180deg)}.dropdown-menu{position:absolute;top:calc(100% + .5rem);left:50%;transform:translateX(-50%);min-width:160px;background:#fff;border:1px solid rgba(0,0,0,.1);border-radius:8px;box-shadow:0 4px 20px rgba(0,0,0,.15);padding:.5rem 0;opacity:0;visibility:hidden;pointer-events:none;transition:opacity .15s ease;z-index:9999;list-style:none}.nav-dropdown.open .dropdown-menu{opacity:1!important;visibility:visible!important;pointer-events:auto!important;transform:translateX(-50%)translateY(0)scale(1)!important}.dropdown-menu::before{content:'';position:absolute;top:-6px;left:50%;transform:translateX(-50%);border-left:6px solid transparent;border-right:6px solid transparent;border-bottom:6px solid #fff;filter:drop-shadow(0 -1px 1px rgba(0,0,0,.1))}.dropdown-menu li{margin:0}.nav-dropdown .dropdown-menu a{display:block!important;padding:.6rem 1.25rem!important;color:#4a4a4a!important;font-size:.875rem!important;font-weight:500!important;text-decoration:none!important;transition:all .15s ease!important;white-space:nowrap!important;cursor:pointer!important;pointer-events:auto!important}.nav-dropdown .dropdown-menu a:hover{background:#f3f4f6!important;color:#4f46e5!important}.nav-dropdown .dropdown-menu a.active{color:#4f46e5!important}@media(max-width:768px){.dropdown-menu{position:static;transform:none;box-shadow:none;border:none;background:rgba(0,0,0,3%);border-radius:0;padding:0;max-height:0;overflow:hidden;opacity:1;visibility:visible;transition:max-height .2s ease}.dropdown-menu::before{display:none}.nav-dropdown.open .dropdown-menu{max-height:300px;padding:.5rem 0}.dropdown-menu a{padding:.5rem 1.5rem .5rem 2rem;font-size:.85rem}}</style><script>document.addEventListener("DOMContentLoaded",function(){const e=document.querySelectorAll(".nav-dropdown");e.forEach(t=>{const n=t.querySelector(".dropdown-toggle");n.addEventListener("click",function(n){n.preventDefault(),n.stopPropagation();const s=t.classList.contains("open");e.forEach(e=>e.classList.remove("open")),s||t.classList.add("open")})}),document.addEventListener("click",function(t){t.target.closest(".nav-dropdown")||e.forEach(e=>e.classList.remove("open"))}),document.addEventListener("keydown",function(t){t.key==="Escape"&&e.forEach(e=>e.classList.remove("open"))})})</script><nav aria-label=Breadcrumb class=breadcrumb-nav><ol class=breadcrumb itemscope itemtype=https://schema.org/BreadcrumbList><li itemprop=itemListElement itemscope itemtype=https://schema.org/ListItem><a itemprop=item href=https://metafunctor.com/><span itemprop=name>Home</span>
</a><meta itemprop=position content="1"></li><li itemprop=itemListElement itemscope itemtype=https://schema.org/ListItem><span class=breadcrumb-separator>/</span>
<a itemprop=item href=https://metafunctor.com/probsets/stat581/><span itemprop=name>STAT 581 - Statistical Methods - SIUe - Fall 2021</span>
</a><meta itemprop=position content="2"></li><li itemprop=itemListElement itemscope itemtype=https://schema.org/ListItem><span class=breadcrumb-separator>/</span>
<span itemprop=name aria-current=page>Statistical Methods - STAT 581 - Problem Set 1</span>
<meta itemprop=position content="3"></li></ol></nav><main id=main-content role=main aria-label="Main content"><div class=main-container><div class=single-post-layout><article class=single-post itemscope itemtype=https://schema.org/Article><header class=post-header><h1 class=post-title itemprop=headline>Statistical Methods - STAT 581 - Problem Set 1</h1><div class=post-meta><span class=post-date><i class="far fa-calendar" aria-hidden=true></i>
<time datetime=2021-12-01T00:00:00Z itemprop=datePublished>December 1, 2021
</time></span><span class=post-author itemprop=author itemscope itemtype=https://schema.org/Person><i class="far fa-user" aria-hidden=true></i>
<span itemprop=name>Alex Towell (lex@metafunctor.com)</span>
</span><span class=post-reading-time><i class="far fa-clock" aria-hidden=true></i>
5 min read
</span><span class=post-updated><i class="far fa-edit" aria-hidden=true></i>
Updated: <time datetime=2025-12-16T19:22:58-06:00 itemprop=dateModified>December 16, 2025</time></span></div><div class=tags role=list><a href=https://metafunctor.com/tags/statistics/ class=tag role=listitem>statistics</a>
<a href=https://metafunctor.com/tags/statistical-methods/ class=tag role=listitem>statistical-methods</a>
<a href=https://metafunctor.com/tags/r/ class=tag role=listitem>R</a>
<a href=https://metafunctor.com/tags/siue/ class=tag role=listitem>SIUe</a></div></header><div class=content itemprop=articleBody><p>snugshade</p><p>An experiment is designed to investigate whether the time to drill holes in rock holes using wet or dry drilling. A completely randomized design (CRD) is used. Each method is replicated on 12 rocks. The drilling times (in 1 / 100 minutes) are observed to be</p><hr><p>dry 727 965 904 987 847 918 814 750 804 989 902 939
wet 607 549 762 665 588 798 704 772 780 599 603 699</p><hr><h1 id=q1>Q1</h1><p>The hypothesis of interest is whether drilling time is effected by the choice of wet or dry drilling. We may formulate this as a hypothesis test of the form</p><p>[\[\begin{aligned} H_0 &: \mu_1 = \mu_2\\ H_A &: \mu_1 \neq \mu_2\,, \end{aligned}\]]{.math .display} where [\(\mu_1\)]{.math .inline} and [\(\mu_2\)]{.math .inline} are respectively the expected drilling time for dry and wet drilling.</p><p>If [\(H_0\)]{.math .inline} is true, the drilling method has <em>no</em> effect on drilling time. If [\(H_A\)]{.math .inline} is true, the choice does have an effect on drilling time.</p><h1 id=q2>Q2</h1><p>Two advantages of the completely randomized design (CRD) are:</p><ol><li><p>It is simple to implement and analyze.</p></li><li><p>It accounts for experimental unit variance, namely by controlling for the type I error,</p><p>[\[\alpha = \Pr(\text{decide} \, H_A | H_0 \, \text{true}),\]]{.math .display}</p><p>where [\(\alpha\)]{.math .inline} is the probability of a type I error. It may also be thought of as the type I <em>error rate</em>, or <em>false positive rate</em>.</p></li></ol><h1 id=q3>Q3</h1><p>Two disadvantages of the completely randomized design (CRD) are:</p><ol><li><p>It does not account for type II error, [\[\beta = \Pr(\text{decide} \, H_0 | H_A \, \text{true}).\]]{.math .display} where [\(\beta\)]{.math .inline} is the probability of a type II error.</p><blockquote><p><strong>Additional remarks</strong>: Since we may denote a type I error a false positive, it may be appropriate to denote a type II error a false negative, which implies the convention [\(H_0 \equiv \rm{negative}\)]{.math .inline} and [\(H_A \equiv \rm{positive}\)]{.math .inline}. Thus, [\(\beta\)]{.math .inline} may be thought of as the false negative rate.</p></blockquote><blockquote><p>Consider the unrelated <em>Bloom filter</em>, which is a probabilistic data structure that models sets in which membership queries have a controllable false positive rate [\(\epsilon\)]{.math .inline} and a false negative rate [\(0\)]{.math .inline}. If we take the complement of an object representing such a Bloom filter, then membership queries on its complement have a false positive rate [\(0\)]{.math .inline} and a false negative rate [\(\epsilon\)]{.math .inline}.</p></blockquote></li><li><p>It does not adjust for differences in experimental units nor differences in any other factors.</p></li></ol><h1 id=q4>Q4</h1><p>snugshade
Highlighting
time.mean [&lt;-]{style=&ldquo;color: 0.56,0.35,0.01&rdquo;} [round]{style=&ldquo;color: 0.13,0.29,0.53&rdquo;}([c]{style=&ldquo;color: 0.13,0.29,0.53&rdquo;}([mean]{style=&ldquo;color: 0.13,0.29,0.53&rdquo;}(h1.time.dry), [mean]{style=&ldquo;color: 0.13,0.29,0.53&rdquo;}(h1.time.wet)),[digits=]{style=&ldquo;color: 0.13,0.29,0.53&rdquo;}[3]{style=&ldquo;color: 0.00,0.00,0.81&rdquo;}) time.var [&lt;-]{style=&ldquo;color: 0.56,0.35,0.01&rdquo;} [round]{style=&ldquo;color: 0.13,0.29,0.53&rdquo;}([c]{style=&ldquo;color: 0.13,0.29,0.53&rdquo;}([var]{style=&ldquo;color: 0.13,0.29,0.53&rdquo;}(h1.time.dry), [var]{style=&ldquo;color: 0.13,0.29,0.53&rdquo;}(h1.time.wet)),[digits=]{style=&ldquo;color: 0.13,0.29,0.53&rdquo;}[3]{style=&ldquo;color: 0.00,0.00,0.81&rdquo;}) time.sd [&lt;-]{style=&ldquo;color: 0.56,0.35,0.01&rdquo;} [round]{style=&ldquo;color: 0.13,0.29,0.53&rdquo;}([sqrt]{style=&ldquo;color: 0.13,0.29,0.53&rdquo;}(time.var),[digits=]{style=&ldquo;color: 0.13,0.29,0.53&rdquo;}[3]{style=&ldquo;color: 0.00,0.00,0.81&rdquo;}) n [&lt;-]{style=&ldquo;color: 0.56,0.35,0.01&rdquo;} [c]{style=&ldquo;color: 0.13,0.29,0.53&rdquo;}([length]{style=&ldquo;color: 0.13,0.29,0.53&rdquo;}(h1.time.dry), [length]{style=&ldquo;color: 0.13,0.29,0.53&rdquo;}(h1.time.wet)) time.sd.pooled [&lt;-]{style=&ldquo;color: 0.56,0.35,0.01&rdquo;} [round]{style=&ldquo;color: 0.13,0.29,0.53&rdquo;}([sqrt]{style=&ldquo;color: 0.13,0.29,0.53&rdquo;}(((n[[1]{style=&ldquo;color: 0.00,0.00,0.81&rdquo;}] [<strong>-</strong>]{style=&ldquo;color: 0.81,0.36,0.00&rdquo;} [1]{style=&ldquo;color: 0.00,0.00,0.81&rdquo;}) [<em><strong><strong>]{style=&ldquo;color: 0.81,0.36,0.00&rdquo;} time.var[[1]{style=&ldquo;color: 0.00,0.00,0.81&rdquo;}] [</strong>+</strong>]{style=&ldquo;color: 0.81,0.36,0.00&rdquo;} (n[[2]{style=&ldquo;color: 0.00,0.00,0.81&rdquo;}] [</em><em>-</em><em>]{style=&ldquo;color: 0.81,0.36,0.00&rdquo;} [1]{style=&ldquo;color: 0.00,0.00,0.81&rdquo;}) [</em><strong><strong>]{style=&ldquo;color: 0.81,0.36,0.00&rdquo;} time.var[[2]{style=&ldquo;color: 0.00,0.00,0.81&rdquo;}]) [</strong>/</strong>]{style=&ldquo;color: 0.81,0.36,0.00&rdquo;} ([sum]{style=&ldquo;color: 0.13,0.29,0.53&rdquo;}(n)[<strong>-</strong>]{style=&ldquo;color: 0.81,0.36,0.00&rdquo;}[2]{style=&ldquo;color: 0.00,0.00,0.81&rdquo;})), [digits=]{style=&ldquo;color: 0.13,0.29,0.53&rdquo;}[3]{style=&ldquo;color: 0.00,0.00,0.81&rdquo;})</p><p>[c]{style=&ldquo;color: 0.13,0.29,0.53&rdquo;}(["y.bar.1"]{style=&ldquo;color: 0.31,0.60,0.02&rdquo;} [=]{style=&ldquo;color: 0.56,0.35,0.01&rdquo;} time.mean[[1]{style=&ldquo;color: 0.00,0.00,0.81&rdquo;}], ["y.bar.2"]{style=&ldquo;color: 0.31,0.60,0.02&rdquo;} [=]{style=&ldquo;color: 0.56,0.35,0.01&rdquo;} time.mean[[2]{style=&ldquo;color: 0.00,0.00,0.81&rdquo;}], ["s.1"]{style=&ldquo;color: 0.31,0.60,0.02&rdquo;} [=]{style=&ldquo;color: 0.56,0.35,0.01&rdquo;} time.sd[[1]{style=&ldquo;color: 0.00,0.00,0.81&rdquo;}], ["s.2"]{style=&ldquo;color: 0.31,0.60,0.02&rdquo;} [=]{style=&ldquo;color: 0.56,0.35,0.01&rdquo;} time.sd[[2]{style=&ldquo;color: 0.00,0.00,0.81&rdquo;}], ["s.p"]{style=&ldquo;color: 0.31,0.60,0.02&rdquo;} [=]{style=&ldquo;color: 0.56,0.35,0.01&rdquo;} time.sd.pooled)</p><pre><code>## y.bar.1 y.bar.2     s.1     s.2     s.p 
## 878.833 677.167  89.470  87.189  88.337
</code></pre><p>We see that the sample means are [\[(\bar{y}_1,\bar{y}_2) = (878.833, 677.167),\]]{.math .display} the standard deviations are [\[(s_1,s_2) = (89.47, 87.189),\]]{.math .display} and the pooled standard deviation is [\[s_p = 88.337.\]]{.math .display}</p><h1 id=q5>Q5</h1><p>The test statistic is defined as [\[t_0 = \frac{\bar{y}_1-\bar{y}_2}{s_p \sqrt{\frac{1}{n_1}+\frac{1}{n_2}}}.\]]{.math .display} which is a drawn from a [\(t\)]{.math .inline}-student distribution with [\(n_1+n_2-2\)]{.math .inline} degrees of freedom under the null model (reference distribution).</p><blockquote><p>Under the null model, [\(\bar{y}_1\)]{.math .inline} and [\(\bar{y}_2\)]{.math .inline} are the means of two samples respectively of size [\(n_1\)]{.math .inline} and [\(n_2\)]{.math .inline} whose elements are drawn from the same normal distribution.</p></blockquote><p>Denote this reference distribution by [\(T\)]{.math .inline}. Under the null model, [\(t_0\)]{.math .inline} is a realization of [\(T\)]{.math .inline}. Our general approach is to compute the test statistic [\(t_0\)]{.math .inline} for the given samples and say it is compatible with the null model if it obtains a value that is not too extreme under [\(T\)]{.math .inline}, e.g., a [\(p\)]{.math .inline}-value that is less than some controllable parameter [\(\alpha\)]{.math .inline}.</p><p>The critical point (the minimum value that is considered to be too extreme) is given by solving for [\(t^<em>\)]{.math .inline} in [\[\Pr\{-|t^</em>| &lt; T &lt; |t^<em>|\} = \alpha,\]]{.math .display} which has the solution [\(t^</em> = t_{\rm{df}=n_1+n_2-2}(\alpha/2)\)]{.math .inline}, and [\[\begin{aligned} \text{$p$-value} &= \Pr\{T \notin [-|t_0|,|t_0|]\}\\ &= 2 \Pr\{T > |t_0|\}\\ &= 2(1-F_T(|t_0|)), \end{aligned}\]]{.math .display} where [\(F_T\)]{.math .inline} is the cdf of [\(T\)]{.math .inline}.</p><p>We compute these results in R with:</p><p>snugshade
Highlighting
se [&lt;-]{style=&ldquo;color: 0.56,0.35,0.01&rdquo;} time.sd.pooled[<em><strong><strong>]{style=&ldquo;color: 0.81,0.36,0.00&rdquo;}[sqrt]{style=&ldquo;color: 0.13,0.29,0.53&rdquo;}([1]{style=&ldquo;color: 0.00,0.00,0.81&rdquo;}[</strong>/</strong>]{style=&ldquo;color: 0.81,0.36,0.00&rdquo;}n[[1]{style=&ldquo;color: 0.00,0.00,0.81&rdquo;}][</em><em>+</em><em>]{style=&ldquo;color: 0.81,0.36,0.00&rdquo;}[1]{style=&ldquo;color: 0.00,0.00,0.81&rdquo;}[</em><em>/</em><em>]{style=&ldquo;color: 0.81,0.36,0.00&rdquo;}n[[2]{style=&ldquo;color: 0.00,0.00,0.81&rdquo;}]) t[.0]{style=&ldquo;color: 0.00,0.00,0.81&rdquo;} [&lt;-]{style=&ldquo;color: 0.56,0.35,0.01&rdquo;} [round]{style=&ldquo;color: 0.13,0.29,0.53&rdquo;}((time.mean[[1]{style=&ldquo;color: 0.00,0.00,0.81&rdquo;}][</em><em>-</em><em>]{style=&ldquo;color: 0.81,0.36,0.00&rdquo;}time.mean[[2]{style=&ldquo;color: 0.00,0.00,0.81&rdquo;}])[</em><em>/</em><em>]{style=&ldquo;color: 0.81,0.36,0.00&rdquo;}se,[digits=]{style=&ldquo;color: 0.13,0.29,0.53&rdquo;}[3]{style=&ldquo;color: 0.00,0.00,0.81&rdquo;}) alpha [&lt;-]{style=&ldquo;color: 0.56,0.35,0.01&rdquo;} [0.05]{style=&ldquo;color: 0.00,0.00,0.81&rdquo;} t.star [=]{style=&ldquo;color: 0.56,0.35,0.01&rdquo;} [round]{style=&ldquo;color: 0.13,0.29,0.53&rdquo;}([qt]{style=&ldquo;color: 0.13,0.29,0.53&rdquo;}(alpha[</em><em>/</em><em>]{style=&ldquo;color: 0.81,0.36,0.00&rdquo;}[2]{style=&ldquo;color: 0.00,0.00,0.81&rdquo;},[lower.tail=]{style=&ldquo;color: 0.13,0.29,0.53&rdquo;}F, [df=]{style=&ldquo;color: 0.13,0.29,0.53&rdquo;}n[[1]{style=&ldquo;color: 0.00,0.00,0.81&rdquo;}][</em><em>+</em><em>]{style=&ldquo;color: 0.81,0.36,0.00&rdquo;}n[[2]{style=&ldquo;color: 0.00,0.00,0.81&rdquo;}][</em><em>-</em><em>]{style=&ldquo;color: 0.81,0.36,0.00&rdquo;}[2]{style=&ldquo;color: 0.00,0.00,0.81&rdquo;}),[digits=]{style=&ldquo;color: 0.13,0.29,0.53&rdquo;}[3]{style=&ldquo;color: 0.00,0.00,0.81&rdquo;}) p.value [=]{style=&ldquo;color: 0.56,0.35,0.01&rdquo;} [2]{style=&ldquo;color: 0.00,0.00,0.81&rdquo;}[</em><strong><strong>]{style=&ldquo;color: 0.81,0.36,0.00&rdquo;}[pt]{style=&ldquo;color: 0.13,0.29,0.53&rdquo;}([abs]{style=&ldquo;color: 0.13,0.29,0.53&rdquo;}(t[.0]{style=&ldquo;color: 0.00,0.00,0.81&rdquo;}),[df=]{style=&ldquo;color: 0.13,0.29,0.53&rdquo;}n[[1]{style=&ldquo;color: 0.00,0.00,0.81&rdquo;}][</strong>+</strong>]{style=&ldquo;color: 0.81,0.36,0.00&rdquo;}n[[2]{style=&ldquo;color: 0.00,0.00,0.81&rdquo;}][<strong>-</strong>]{style=&ldquo;color: 0.81,0.36,0.00&rdquo;}[2]{style=&ldquo;color: 0.00,0.00,0.81&rdquo;},[lower.tail=]{style=&ldquo;color: 0.13,0.29,0.53&rdquo;}F)</p><p>[c]{style=&ldquo;color: 0.13,0.29,0.53&rdquo;}(["t.0"]{style=&ldquo;color: 0.31,0.60,0.02&rdquo;}[=]{style=&ldquo;color: 0.56,0.35,0.01&rdquo;}t[.0]{style=&ldquo;color: 0.00,0.00,0.81&rdquo;},["t.*"]{style=&ldquo;color: 0.31,0.60,0.02&rdquo;}[=]{style=&ldquo;color: 0.56,0.35,0.01&rdquo;}t.star,["p.value"]{style=&ldquo;color: 0.31,0.60,0.02&rdquo;}[=]{style=&ldquo;color: 0.56,0.35,0.01&rdquo;}p.value)</p><pre><code>##          t.0          t.*      p.value 
## 5.592000e+00 2.074000e+00 1.272907e-05
</code></pre><p>We see that [\(t_0 = 5.592\)]{.math .inline}, the critical point [\(t^*\)]{.math .inline} for [\(\alpha = 0.05\)]{.math .inline} is [\(2.074\)]{.math .inline}, and the [\(p\)]{.math .inline}-value is less than [\(.001\)]{.math .inline}.</p><h1 id=q6>Q6</h1><p>The experiment finds that the wet drilling method leads to reduced drilling times compared to the dry drilling method.</p><h1 id=q7>Q7</h1><p>snugshade</p><h1 id=q8>Q8</h1><p>No, not all dry drilling times exceed all wet drilling times.</p><p>However, the boxplot does show that the spread of the drilling times area approximately the same between the two methods (providing justification for assuming the two samples have the same variance) and the mean drilling times are significantly different. As a result, most of the time, the wet drilling time is going to be less than the dry drilling time.</p><p>For instance, we see that the mean wet drilling time is less than the best dry drilling time and we also see that the [\(25\)]{.math .inline}-th percentile of the dry method&rsquo;s times is a bit larger than the wet method&rsquo;s longest drilling time. Most tellingly, we see that around [\(67\%\)]{.math .inline} of the time, the wet drilling time is less than the smallest dry drilling time.</p></div><nav class=post-navigation><a href=../../../probsets/stat581/stat581-hw2/ class=nav-prev><span class=nav-label>← Previous</span>
<span class=nav-title>Statistical Methods - STAT 581 - Problem Set 2</span>
</a><a href=../../../probsets/stat581/stat581-exam2/ class=nav-next><span class=nav-label>Next →</span>
<span class=nav-title>Statistical Methods - STAT 581 - Exam 2</span></a></nav></article></div></div></main><footer class=elegant-footer role=contentinfo aria-label="Site footer"><div class=footer-content><div class=footer-about><h3>metafunctor</h3><p>Research engineer and computer scientist specializing in machine learning, statistical computing, and open source software development.</p><nav aria-label="Social media links" class=social-links><a href=https://twitter.com/queelius target=_blank rel="noopener noreferrer" aria-label=Twitter><i class="fab fa-twitter" aria-hidden=true></i>
</a><a href=https://github.com/queelius target=_blank rel="noopener noreferrer" aria-label=GitHub><i class="fab fa-github" aria-hidden=true></i>
</a><a href=https://www.linkedin.com/in/alexander-towell-487015151/ target=_blank rel="noopener noreferrer" aria-label=LinkedIn><i class="fab fa-linkedin" aria-hidden=true></i>
</a><a href=../../../index.xml target=_blank rel="noopener noreferrer" aria-label=RSS><i class="fas fa-rss" aria-hidden=true></i>
</a><a href=mailto:lex@metafunctor.com target=_blank rel="noopener noreferrer" aria-label=Email><i class="fas fa-envelope" aria-hidden=true></i>
</a><a href=https://keybase.io/queelius target=_blank rel="noopener noreferrer" aria-label=Keybase><i class="fab fa-keybase" aria-hidden=true></i>
</a><a href=https://www.youtube.com/@queelius target=_blank rel="noopener noreferrer" aria-label=YouTube><i class="fab fa-youtube" aria-hidden=true></i>
</a><a href="https://scholar.google.com/citations?view_op=list_works&amp;hl=en&amp;user=E9mnFzQAAAAJ" target=_blank rel="noopener noreferrer" aria-label="Google Scholar"><i class="fas fa-graduation-cap" aria-hidden=true></i>
</a><a href="https://orcid.org/my-orcid?orcid=0000-0001-6443-9897" target=_blank rel="noopener noreferrer" aria-label=ORCID><i class="fab fa-orcid" aria-hidden=true></i></a></nav></div><nav class=footer-section aria-labelledby=footer-content><h4 id=footer-content>Content</h4><div class=footer-links><a href=https://metafunctor.com/post/>Posts</a>
<a href=https://metafunctor.com/papers/>Papers</a>
<a href=https://metafunctor.com/series/>Series</a>
<a href=https://metafunctor.com/publications/>Publications</a>
<a href=https://metafunctor.com/writing/>Writing</a></div></nav><nav class=footer-section aria-labelledby=footer-code><h4 id=footer-code>Code</h4><div class=footer-links><a href=https://metafunctor.com/projects/>Projects</a>
<a href=https://github.com/queelius target=_blank rel="noopener noreferrer">GitHub</a>
<a href=https://pypi.org/user/queelius/ target=_blank rel="noopener noreferrer">PyPI</a></div></nav><nav class=footer-section aria-labelledby=footer-connect><h4 id=footer-connect>Connect</h4><div class=footer-links><a href=https://metafunctor.com/about/>About</a>
<a href=mailto:lex@metafunctor.com>Contact</a>
<a href=https://metafunctor.com/index.xml type=application/rss+xml>RSS Feed</a></div></nav></div><div class=footer-bottom><p class=copyright>© 2026 Alex Towell. All rights reserved.</p><p class=accessibility-note><a href=#main-content>Back to top</a></p></div></footer><script src=../../../js/performance-optimizations.js defer></script><script src=../../../js/performance-enhancements.js defer></script><script src=../../../js/mobile-menu.js defer></script><script src=../../../js/modern-interactions.js defer></script><script src=../../../js/search.js defer></script><script src=../../../js/reading-progress.js defer></script><script src=../../../js/copy-code.js defer></script><script src=../../../js/anchor-links.js defer></script><button id=back-to-top aria-label="Back to top" style="display:none;position:fixed;bottom:30px;right:30px;z-index:1000;background:linear-gradient(135deg,#667eea 0%,#764ba2 100%);color:#fff;border:none;border-radius:50%;width:50px;height:50px;cursor:pointer;box-shadow:0 4px 15px rgba(102,126,234,.4);transition:all .3s ease">
<i class="fas fa-arrow-up"></i>
</button>
<script>const backToTop=document.getElementById("back-to-top");window.addEventListener("scroll",()=>{window.scrollY>300?backToTop.style.display="block":backToTop.style.display="none"}),backToTop.addEventListener("click",()=>{window.scrollTo({top:0,behavior:"smooth"})})</script><script data-goatcounter=https://queelius.goatcounter.com/count async src=//gc.zgo.at/count.js></script></body></html>