<!DOCTYPE html>
<html lang="en-us" prefix="og: https://ogp.me/ns#">
<head><script src="/livereload.js?mindelay=10&amp;v=2&amp;port=1313&amp;path=livereload" data-no-instant defer></script>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">

  
  <title>Discrete Multivariate Analysis - STAT 579 - Exam 2 | metafunctor</title>
  <meta name="title" content="Discrete Multivariate Analysis - STAT 579 - Exam 2 | metafunctor">
  <meta name="description" content="Discrete multivariate analysis exam covering log-linear models and categorical data analysis.">

  
  <meta name="keywords" content="machine learning, statistical computing, open source, research, computer science, artificial intelligence">
  <meta name="author" content="Alex Towell">
  <meta name="robots" content="index, follow, max-image-preview:large, max-snippet:-1, max-video-preview:-1">
  <link rel="canonical" href="http://localhost:1313/probsets/stat579/stat579-exam2/">

  
  

  
  <link rel="alternate" hreflang="en" href="http://localhost:1313/probsets/stat579/stat579-exam2/">
  <link rel="alternate" hreflang="x-default" href="http://localhost:1313/probsets/stat579/stat579-exam2/">

  
  
<style>
 

 
*, *::before, *::after {
  box-sizing: border-box;
  margin: 0;
  padding: 0;
}

html {
  font-size: 16px;
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
}

body {
  margin: 0;
  font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', 'Roboto', sans-serif;
  font-size: 17px;
  line-height: 1.7;
  color: #2c2c2c;
  background: #ffffff;
}

 
.elegant-header {
  position: sticky;
  top: 0;
  z-index: 1000;
  background: rgba(254, 254, 254, 0.95);
  backdrop-filter: blur(10px);
  border-bottom: 1px solid rgba(0,0,0,0.08);
}

.header-inner {
  max-width: 1400px;
  margin: 0 auto;
  padding: 1rem 2rem;
  display: flex;
  justify-content: space-between;
  align-items: center;
}

.site-logo {
  font-size: 1.5rem;
  font-weight: 700;
  color: #2c2c2c;
  text-decoration: none;
}

.nav-primary ul {
  display: flex;
  gap: 2rem;
  list-style: none;
}

.nav-primary a {
  font-size: 0.9rem;
  font-weight: 500;
  color: #4a4a4a;
  text-decoration: none;
}

 
.hero-elegant {
  padding: 5rem 2rem;
  text-align: center;
  background: linear-gradient(180deg, #fafafa 0%, #ffffff 100%);
}

.hero-title {
  font-size: 3.5rem;
  font-weight: 700;
  margin-bottom: 1rem;
  background: linear-gradient(135deg, #2c2c2c 0%, #003d7a 100%);
  -webkit-background-clip: text;
  -webkit-text-fill-color: transparent;
  background-clip: text;
}

.hero-subtitle {
  font-size: 1.25rem;
  color: #4a4a4a;
  max-width: 600px;
  margin: 0 auto 3rem;
}

 
.skip-to-main {
  position: absolute;
  top: -100px;
  left: 0;
  background: #0050a0;
  color: white;
  padding: 0.5rem 1rem;
  text-decoration: none;
  font-weight: 600;
  z-index: 10000;
}

.skip-to-main:focus {
  top: 0;
}

 
.preload * {
  transition: none !important;
}
</style>


  
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link rel="preconnect" href="https://cdnjs.cloudflare.com" crossorigin>
  <link rel="dns-prefetch" href="https://www.google-analytics.com">
  <link rel="dns-prefetch" href="https://cdn.jsdelivr.net">

  
  <meta property="og:type" content="article">
  <meta property="og:url" content="http://localhost:1313/probsets/stat579/stat579-exam2/">
  <meta property="og:title" content="Discrete Multivariate Analysis - STAT 579 - Exam 2">
  <meta property="og:description" content="Discrete multivariate analysis exam covering log-linear models and categorical data analysis.">
  <meta property="og:image" content="http://localhost:1313/images/og-image.jpg">
  <meta property="og:image:width" content="1200">
  <meta property="og:image:height" content="630">
  <meta property="og:site_name" content="metafunctor">
  <meta property="og:locale" content="en_US">
  
  <meta property="article:author" content="Alex Towell">
  <meta property="article:published_time" content="2021-05-01T00:00:00Z">
  <meta property="article:modified_time" content="2026-03-16T14:04:45-05:00">
  
  <meta property="article:tag" content="statistics"><meta property="article:tag" content="multivariate-analysis"><meta property="article:tag" content="categorical-data"><meta property="article:tag" content="R"><meta property="article:tag" content="SIUe">
  

  
  <meta name="twitter:card" content="summary_large_image">
  <meta name="twitter:url" content="http://localhost:1313/probsets/stat579/stat579-exam2/">
  <meta name="twitter:title" content="Discrete Multivariate Analysis - STAT 579 - Exam 2">
  <meta name="twitter:description" content="Discrete multivariate analysis exam covering log-linear models and categorical data analysis.">
  <meta name="twitter:image" content="http://localhost:1313/images/og-image.jpg">
  <meta name="twitter:site" content="@queelius">
  <meta name="twitter:creator" content="@queelius">

  
  <script type="application/ld+json">
  {
    "@context": "https://schema.org",
    "@graph": [
      {
        "@type": "Article",
        "@id": "http:\/\/localhost:1313\/probsets\/stat579\/stat579-exam2\/#primaryContent",
        
        "headline": "Discrete Multivariate Analysis - STAT 579 - Exam 2",
        "description": "Discrete multivariate analysis exam covering log-linear models and categorical data analysis.",
        "url": "http:\/\/localhost:1313\/probsets\/stat579\/stat579-exam2\/",
        "inLanguage": "en-US",
        "datePublished": "2021-05-01T00:00:00Z",
        "dateModified": "2026-03-16T14:04:45-05:00",
        "wordCount":  2973 ,
        "timeRequired": "PT14M",
        "author": {
          "@type": "Person",
          "@id": "http:\/\/localhost:1313\/#author",
          "name": "Alex Towell",
          "url": "http:\/\/localhost:1313\/about/"
        },
        "publisher": {
          "@type": "Organization",
          "@id": "http:\/\/localhost:1313\/#organization",
          "name": "metafunctor",
          "url": "http:\/\/localhost:1313\/",
          "logo": {
            "@type": "ImageObject",
            "url": "http:\/\/localhost:1313\/images\/og-image.jpg"
          }
        },
        "keywords": ["statistics", "multivariate-analysis", "categorical-data", "R", "SIUe"]
        
      },
      {
        "@type": "BreadcrumbList",
        "@id": "http:\/\/localhost:1313\/probsets\/stat579\/stat579-exam2\/#breadcrumb",
        "itemListElement": [
          {
            "@type": "ListItem",
            "position": 1,
            "name": "Home",
            "item": "http:\/\/localhost:1313\/"
          },
          {
            "@type": "ListItem",
            "position": 2,
            "name": "STAT 579 - Discrete Multivariate Analysis - SIUe - Spring 2021",
            "item": "http:\/\/localhost:1313\/probsets\/stat579\/"
          },
          {
            "@type": "ListItem",
            "position": 3,
            "name": "Discrete Multivariate Analysis - STAT 579 - Exam 2",
            "item": "http:\/\/localhost:1313\/probsets\/stat579\/stat579-exam2\/"
          }
        ]
      }
    ]
  }
  </script>

  
  <link rel="preload" href="https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700;800&family=Lora:ital,wght@0,400;0,600;0,700;1,400&family=JetBrains+Mono:wght@400;500&display=swap" as="style">
  <link href="https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700;800&family=Lora:ital,wght@0,400;0,600;0,700;1,400&family=JetBrains+Mono:wght@400;500&display=swap" rel="stylesheet" media="print" onload="this.media='all'">
  <noscript><link href="https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700;800&family=Lora:ital,wght@0,400;0,600;0,700;1,400&family=JetBrains+Mono:wght@400;500&display=swap" rel="stylesheet"></noscript>

  
  <link rel="stylesheet" href="../../../css/refined-elegant.css">

  
  <link rel="stylesheet" href="../../../css/micro-interactions.css">

  
  <link rel="stylesheet" href="../../../css/elegant.css" media="print" onload="this.media='all'">

  
  <link rel="stylesheet" href="../../../css/custom.css">

  
  <link rel="stylesheet" href="../../../css/beautify.css">

  
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css" crossorigin="anonymous">
  
  
  
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/katex@0.16.8/dist/katex.min.css">
  <script defer src="https://cdn.jsdelivr.net/npm/katex@0.16.8/dist/katex.min.js"></script>
  <script defer src="https://cdn.jsdelivr.net/npm/katex@0.16.8/dist/contrib/auto-render.min.js"></script>
  <script>
    document.addEventListener("DOMContentLoaded", function() {
      renderMathInElement(document.body, {
        delimiters: [
          {left: "$$", right: "$$", display: true},
          {left: "\\[", right: "\\]", display: true},
          {left: "$", right: "$", display: false},
          {left: "\\(", right: "\\)", display: false}
        ]
      });
    });
  </script>
  

  
  <script defer src="https://cdn.jsdelivr.net/npm/fuse.js@7.0.0/dist/fuse.min.js"></script>

  
  





  
  

  
      <script async src="https://www.googletagmanager.com/gtag/js?id=G-E08ZXTFTTY"></script>
      <script>
        var doNotTrack = false;
        if ( true ) {
          var dnt = (navigator.doNotTrack || window.doNotTrack || navigator.msDoNotTrack);
          var doNotTrack = (dnt == "1" || dnt == "yes");
        }
        if (!doNotTrack) {
          window.dataLayer = window.dataLayer || [];
          function gtag(){dataLayer.push(arguments);}
          gtag('js', new Date());
          gtag('config', 'G-E08ZXTFTTY');
        }
      </script>
  <meta name="generator" content="Hugo 0.163.3">
</head>
<body>
  
  <a href="#main-content" class="skip-to-main">Skip to main content</a>

  <header class="elegant-header" role="banner">
  <div class="header-inner">
    <div class="site-identity">
      <a href="http://localhost:1313/" class="site-logo" aria-label="metafunctor home">metafunctor</a>
      <span class="site-tagline" aria-label="Site tagline">Research · Coding</span>
    </div>
    <nav class="nav-primary" role="navigation" aria-label="Main navigation">
      <button class="mobile-menu-toggle" aria-label="Toggle mobile menu" aria-expanded="false">
        <span></span>
        <span></span>
        <span></span>
      </button>
      <ul role="list">
        <li><a href="http://localhost:1313/" >Home</a></li>
        <li><a href="http://localhost:1313/post/" >Posts</a></li>
        <li><a href="http://localhost:1313/series/" >Series</a></li>
        <li class="nav-dropdown">
          <a href="#" class="dropdown-toggle " aria-haspopup="true" aria-expanded="false">
            Academic <i class="fas fa-chevron-down dropdown-icon"></i>
          </a>
          <ul class="dropdown-menu" role="menu">
            <li role="menuitem"><a href="http://localhost:1313/papers/" >Papers</a></li>
            <li role="menuitem"><a href="http://localhost:1313/publications/" >Publications</a></li>
            <li role="menuitem"><a href="http://localhost:1313/research/" >Research</a></li>
          </ul>
        </li>
        <li><a href="http://localhost:1313/ethos/" >Ethos</a></li>
        <li class="nav-dropdown">
          <a href="#" class="dropdown-toggle " aria-haspopup="true" aria-expanded="false">
            Creative <i class="fas fa-chevron-down dropdown-icon"></i>
          </a>
          <ul class="dropdown-menu" role="menu">
            <li role="menuitem"><a href="http://localhost:1313/writing/" >Writing</a></li>
            <li role="menuitem"><a href="http://localhost:1313/media/" >Media</a></li>
          </ul>
        </li>
        <li><a href="http://localhost:1313/projects/" >Projects</a></li>
        <li><a href="http://localhost:1313/about/" >About</a></li>
        <li><a href="http://localhost:1313/search/" ><i class="fas fa-search" aria-hidden="true"></i><span class="sr-only">Search</span></a></li>
      </ul>
    </nav>
  </div>
</header>

<style>
 
.nav-dropdown {
  position: relative;
}

.dropdown-toggle {
  display: flex;
  align-items: center;
  gap: 0.35rem;
  cursor: pointer;
}

.dropdown-icon {
  font-size: 0.6rem;
  transition: transform 0.2s ease;
}

.nav-dropdown.open .dropdown-icon {
  transform: rotate(180deg);
}

.dropdown-menu {
  position: absolute;
  top: calc(100% + 0.5rem);
  left: 50%;
  transform: translateX(-50%);
  min-width: 160px;
  background: #fff;
  border: 1px solid rgba(0, 0, 0, 0.1);
  border-radius: 8px;
  box-shadow: 0 4px 20px rgba(0, 0, 0, 0.15);
  padding: 0.5rem 0;
  opacity: 0;
  visibility: hidden;
  pointer-events: none;
  transition: opacity 0.15s ease;
  z-index: 9999;
  list-style: none;
}

.nav-dropdown.open .dropdown-menu {
  opacity: 1 !important;
  visibility: visible !important;
  pointer-events: auto !important;
  transform: translateX(-50%) translateY(0) scale(1) !important;
}

 
.dropdown-menu::before {
  content: '';
  position: absolute;
  top: -6px;
  left: 50%;
  transform: translateX(-50%);
  border-left: 6px solid transparent;
  border-right: 6px solid transparent;
  border-bottom: 6px solid #fff;
  filter: drop-shadow(0 -1px 1px rgba(0,0,0,0.1));
}

.dropdown-menu li {
  margin: 0;
}

.nav-dropdown .dropdown-menu a {
  display: block !important;
  padding: 0.6rem 1.25rem !important;
  color: #4a4a4a !important;
  font-size: 0.875rem !important;
  font-weight: 500 !important;
  text-decoration: none !important;
  transition: all 0.15s ease !important;
  white-space: nowrap !important;
  cursor: pointer !important;
  pointer-events: auto !important;
}

.nav-dropdown .dropdown-menu a:hover {
  background: #f3f4f6 !important;
  color: #4f46e5 !important;
}

.nav-dropdown .dropdown-menu a.active {
  color: #4f46e5 !important;
}

 
@media (max-width: 768px) {
  .dropdown-menu {
    position: static;
    transform: none;
    box-shadow: none;
    border: none;
    background: rgba(0, 0, 0, 0.03);
    border-radius: 0;
    padding: 0;
    max-height: 0;
    overflow: hidden;
    opacity: 1;
    visibility: visible;
    transition: max-height 0.2s ease;
  }

  .dropdown-menu::before {
    display: none;
  }

  .nav-dropdown.open .dropdown-menu {
    max-height: 300px;
    padding: 0.5rem 0;
  }

  .dropdown-menu a {
    padding: 0.5rem 1.5rem 0.5rem 2rem;
    font-size: 0.85rem;
  }
}
</style>

<script>
document.addEventListener('DOMContentLoaded', function() {
  const dropdowns = document.querySelectorAll('.nav-dropdown');

  dropdowns.forEach(dropdown => {
    const toggle = dropdown.querySelector('.dropdown-toggle');

    
    toggle.addEventListener('click', function(e) {
      e.preventDefault();
      e.stopPropagation();

      const wasOpen = dropdown.classList.contains('open');

      
      dropdowns.forEach(d => d.classList.remove('open'));

      
      if (!wasOpen) {
        dropdown.classList.add('open');
      }
    });
  });

  
  document.addEventListener('click', function(e) {
    if (!e.target.closest('.nav-dropdown')) {
      dropdowns.forEach(d => d.classList.remove('open'));
    }
  });

  
  document.addEventListener('keydown', function(e) {
    if (e.key === 'Escape') {
      dropdowns.forEach(d => d.classList.remove('open'));
    }
  });
});
</script>


  
  
  <nav aria-label="Breadcrumb" class="breadcrumb-nav">
    <ol class="breadcrumb" itemscope itemtype="https://schema.org/BreadcrumbList">
      <li itemprop="itemListElement" itemscope itemtype="https://schema.org/ListItem">
        <a itemprop="item" href="http://localhost:1313/">
          <span itemprop="name">Home</span>
        </a>
        <meta itemprop="position" content="1" />
      </li>
      
      <li itemprop="itemListElement" itemscope itemtype="https://schema.org/ListItem">
        <span class="breadcrumb-separator">/</span>
        <a itemprop="item" href="http://localhost:1313/probsets/stat579/">
          <span itemprop="name">STAT 579 - Discrete Multivariate Analysis - SIUe - Spring 2021</span>
        </a>
        <meta itemprop="position" content="2" />
      </li>
      
      <li itemprop="itemListElement" itemscope itemtype="https://schema.org/ListItem">
        <span class="breadcrumb-separator">/</span>
        <span itemprop="name" aria-current="page">Discrete Multivariate Analysis - STAT 579 - Exam 2</span>
        <meta itemprop="position" content="3" />
      </li>
    </ol>
  </nav>
  

  <main id="main-content" role="main" aria-label="Main content">
    
<div class="main-container">
  <div class="single-post-layout">
    
    
    <aside class="post-sidebar">
      
<aside class="toc-wrapper" aria-label="Table of contents">
  <nav class="table-of-contents">
    <h2 class="toc-title">Table of Contents</h2>
    <div class="toc-content">
      <nav id="TableOfContents">
  <ul>
    <li><a href="#part-a">Part (a)</a>
      <ul>
        <li><a href="#answer">ANSWER</a></li>
      </ul>
    </li>
    <li><a href="#part-b">Part (b)</a>
      <ul>
        <li><a href="#answer-1">ANSWER</a></li>
      </ul>
    </li>
    <li><a href="#part-c">Part (c)</a>
      <ul>
        <li><a href="#answer-2">ANSWER</a></li>
      </ul>
    </li>
    <li><a href="#part-d">Part (d)</a>
      <ul>
        <li><a href="#answer-3">ANSWER</a></li>
      </ul>
    </li>
    <li><a href="#part-e">Part (e)</a>
      <ul>
        <li><a href="#answer-4">ANSWER</a></li>
      </ul>
    </li>
    <li><a href="#part-f">Part (f)</a>
      <ul>
        <li><a href="#answer-5">ANSWER</a></li>
      </ul>
    </li>
    <li><a href="#part-g">Part (g)</a>
      <ul>
        <li><a href="#answer-6">ANSWER</a></li>
      </ul>
    </li>
    <li><a href="#part-h">Part (h)</a>
      <ul>
        <li><a href="#answer-7">ANSWER</a></li>
      </ul>
    </li>
    <li><a href="#part-i">Part (i)</a>
      <ul>
        <li><a href="#answer-8">ANSWER</a></li>
      </ul>
    </li>
    <li><a href="#part-j">Part (j)</a>
      <ul>
        <li><a href="#answer-9">ANSWER</a></li>
      </ul>
    </li>
  </ul>

  <ul>
    <li><a href="#preliminary-analysis">Preliminary analysis</a></li>
    <li><a href="#part-a-1">Part (a)</a>
      <ul>
        <li><a href="#answer-10">ANSWER</a></li>
      </ul>
    </li>
    <li><a href="#part-b-1">Part (b)</a>
      <ul>
        <li><a href="#answer-11">ANSWER</a></li>
      </ul>
    </li>
    <li><a href="#part-c-1">Part (c)</a>
      <ul>
        <li><a href="#answer-12">ANSWER</a></li>
      </ul>
    </li>
  </ul>

  <ul>
    <li><a href="#part-a-2">Part (a)</a>
      <ul>
        <li><a href="#answer-13">ANSWER</a></li>
      </ul>
    </li>
    <li><a href="#part-b-2">Part (b)</a>
      <ul>
        <li><a href="#answer-14">ANSWER</a></li>
      </ul>
    </li>
    <li><a href="#part-c-2">Part (c)</a>
      <ul>
        <li><a href="#answer-15">ANSWER</a></li>
      </ul>
    </li>
    <li><a href="#part-d-1">Part (d)</a>
      <ul>
        <li><a href="#answer-16">ANSWER</a></li>
      </ul>
    </li>
  </ul>

  <ul>
    <li><a href="#part-a-3">Part (a)</a>
      <ul>
        <li><a href="#answer-17">ANSWER</a></li>
      </ul>
    </li>
    <li><a href="#part-b-3">Part (b)</a>
      <ul>
        <li><a href="#answer-18">ANSWER</a></li>
      </ul>
    </li>
    <li><a href="#part-c-3">Part (c)</a>
      <ul>
        <li><a href="#answer-19">ANSWER</a></li>
      </ul>
    </li>
  </ul>
</nav>
    </div>
  </nav>
</aside>

<style>
.toc-wrapper {
  position: sticky;
  top: 80px;
  max-height: calc(100vh - 100px);
  overflow-y: auto;
  padding: var(--space-lg);
  background: var(--paper-dark);
  border: var(--border-width) solid var(--border-color);
  border-radius: var(--radius-lg);
  margin-bottom: var(--space-xl);
}

.toc-title {
  font-size: 1rem;
  font-weight: 600;
  color: var(--ink);
  margin: 0 0 var(--space-md) 0;
  text-transform: uppercase;
  letter-spacing: 0.05em;
  font-size: 0.875rem;
}

.toc-content {
  font-size: 0.9rem;
}

.toc-content ul {
  list-style: none;
  padding-left: 0;
  margin: 0;
}

.toc-content > ul {
  border-left: 2px solid var(--border-color);
  padding-left: var(--space-md);
}

.toc-content li {
  margin-bottom: var(--space-sm);
}

.toc-content a {
  color: var(--ink-light);
  text-decoration: none;
  transition: color var(--transition-fast);
  display: block;
  padding: var(--space-xs) 0;
}

.toc-content a:hover {
  color: var(--accent);
}

.toc-content ul ul {
  margin-top: var(--space-sm);
  padding-left: var(--space-md);
}

 
@media (max-width: 1024px) {
  .toc-wrapper {
    position: relative;
    top: 0;
    max-height: none;
  }
}
</style>

<script>

document.addEventListener('DOMContentLoaded', function() {
  const tocLinks = document.querySelectorAll('.toc-content a');
  const sections = Array.from(tocLinks).map(link => {
    const id = link.getAttribute('href').substring(1);
    return document.getElementById(id);
  }).filter(section => section !== null);

  function highlightTOC() {
    let current = '';
    sections.forEach(section => {
      const sectionTop = section.offsetTop;
      const scrollPosition = window.scrollY + 100;
      if (scrollPosition >= sectionTop) {
        current = section.getAttribute('id');
      }
    });

    tocLinks.forEach(link => {
      link.classList.remove('active');
      if (link.getAttribute('href') === '#' + current) {
        link.classList.add('active');
        link.style.color = 'var(--accent)';
        link.style.fontWeight = '600';
      } else {
        link.style.color = '';
        link.style.fontWeight = '';
      }
    });
  }

  window.addEventListener('scroll', highlightTOC);
  highlightTOC();
});
</script>

    </aside>
    

    
    <article class="single-post" itemscope itemtype="https://schema.org/Article">
      <header class="post-header">
        <h1 class="post-title" itemprop="headline">Discrete Multivariate Analysis - STAT 579 - Exam 2</h1>
        <div class="post-meta">
          
          <span class="post-date">
            <i class="far fa-calendar" aria-hidden="true"></i>
            <time datetime="2021-05-01T00:00:00Z" itemprop="datePublished">
              May 1, 2021
            </time>
          </span>
          
          
          <span class="post-author" itemprop="author" itemscope itemtype="https://schema.org/Person">
            <i class="far fa-user" aria-hidden="true"></i>
            <span itemprop="name">Alex Towell (lex@metafunctor.com)</span>
          </span>
          
          <span class="post-reading-time">
            <i class="far fa-clock" aria-hidden="true"></i>
            14 min read
          </span>
          
          
          <span class="post-updated">
            <i class="far fa-edit" aria-hidden="true"></i>
            Updated: <time datetime="2026-03-16T14:04:45-05:00" itemprop="dateModified">
              March 16, 2026
            </time>
          </span>
          
          
        </div>
        
        <div class="tags" role="list">
          
          <a href="http://localhost:1313/tags/statistics/" class="tag" role="listitem">statistics</a>
          
          <a href="http://localhost:1313/tags/multivariate-analysis/" class="tag" role="listitem">multivariate-analysis</a>
          
          <a href="http://localhost:1313/tags/categorical-data/" class="tag" role="listitem">categorical-data</a>
          
          <a href="http://localhost:1313/tags/r/" class="tag" role="listitem">R</a>
          
          <a href="http://localhost:1313/tags/siue/" class="tag" role="listitem">SIUe</a>
          
        </div>
        
      </header>

      <div class="content" itemprop="articleBody">
        <h1 id="problem-1">Problem 1</h1>
<p>A genetic model predicts the ratio of green seedlings to yellow seedlings to be [\(3:1\)]{.math .inline}. Consider data from a sample of [\(n=1100\)]{.math .inline} seedlings, where [\(n_1 = 860\)]{.math .inline} is the number of green and [\(n_2 = 240\)]{.math .inline} is the number of yellow.</p>
<h2 id="part-a">Part (a)</h2>
<p>The observed data models the binomial distribution [\[n_g \sim \operatorname{BIN}(n, \pi_g)\]]{.math .display} where [\(n_g\)]{.math .inline} and [\(n_y = n - n_g\)]{.math .inline} are respectively the number of green and yellow seedlings and [\(\pi_g\)]{.math .inline} and [\(\pi_y=1-\pi_g\)]{.math .inline} are respectively the probability of a green and yellow seedling.</p>
<p>Under the null model, the odds of green seedlings to yellow seedlings is [\(3:1\)]{.math .inline}, thus [\[H_0 : \pi_{g 0} = 0.75 \;\; (\pi_{y 0} = 0.25).\]]{.math .display}</p>
<p>We perform a chi-squared test for goodness of fit whose test statistic is given by [\[X^2 = \frac{(n_g - \hat{m}_g}{\hat{m}_g} + \frac{(n_y - \hat{m}_y)^2}{\hat{m}_y}\]]{.math .display} where [\(\hat{m}_g = n \pi_{g 0}\)]{.math .inline} and [\(\hat{m}_y = \pi_{y 0}\)]{.math .inline}.</p>
<p>The parameter space of the unconstrained binomial model is given by [\[\vec{\pi}(\pi_g) = (\pi_g, 1-\pi_g)',\]]{.math .display} which has a dimension of [\(\dim \vec{\pi} = 1\)]{.math .inline}.</p>
<p>The <em>null model</em>, which is the specified binomial [\(\pi_{g 0} = 0.75\)]{.math .inline}, has the parameter space [\(\vec{\pi}_0 = (0.75,0.25)'\)]{.math .inline}, which is just a <em>point</em> with a dimension of [\(\dim \vec{\pi}_0 = 0\)]{.math .inline}.</p>
<p>Thus, under the null model, [\(X^2\)]{.math .inline} is distributed [\(\chi^2\)]{.math .inline} with [\[\operatorname{df} = \dim \vec{\pi} - \dim \vec{\pi}_0 = 1 - 0 = 1\]]{.math .display} degrees of freedom, denoted by [\(\chi^2(1)\)]{.math .inline}.</p>
<h3 id="answer">ANSWER</h3>
<p>We compute the observed [\(X^2\)]{.math .inline} statistic with:</p>
<p>snugshade</p>
<pre><code>## $stat
## [1] 5.939394
## 
## $p
## [1] 0.01480611
## 
## $df
## [1] 1
</code></pre>
<p>We see that [\(X^2\)]{.math .inline} realizes the value [\(X_0^2 = 5.939\)]{.math .inline}.</p>
<h2 id="part-b">Part (b)</h2>
<p>Assuming [\(X^2 \sim \chi^2(1)\)]{.math .inline}, the [\((1-\alpha) \times 100 \%\)]{.math .inline} percentile, denoted by [\(\chi_{\alpha}^2(1)\)]{.math .inline}, is given by solving the equation [\[\Pr[X^2 \geq \chi_{\alpha}^2(1)] = \alpha\]]{.math .display} for [\(\chi_{\alpha}^2\)]{.math .inline}.</p>
<p>We compute the [\(10\)]{.math .inline}-th percentile with the following R code:</p>
<p>snugshade</p>
<h3 id="answer-1">ANSWER</h3>
<p>We see that the [\(10\)]{.math .inline}-th percentile is [\(\chi^2_{0.1}(1) = 2.706\)]{.math .inline}.</p>
<h2 id="part-c">Part (c)</h2>
<h3 id="answer-2">ANSWER</h3>
<p>We say that any observed statistic [\(X_0^2\)]{.math .inline} with [\(\operatorname{df}=1\)]{.math .inline} greater than [\(\chi^2_{0.1}(1) = 2.706\)]{.math .inline} is not compatible with the null model at significance level [\(\alpha = 0.1\)]{.math .inline}.</p>
<p>Since the observed statistic [\(X_0^2 = 5.939 &gt; 2.706\)]{.math .inline}, the null model, which is the genetic theory where the ratio of green to yellow is [\(3:1\)]{.math .inline}, is not compatible with the data.</p>
<h2 id="part-d">Part (d)</h2>
<h3 id="answer-3">ANSWER</h3>
<p>Hypothesis testing, as a dichotomous measure of evidence, does not provide as much information as a more quantitative evidence measure. For instance, it does not provide information about effect size.</p>
<h2 id="part-e">Part (e)</h2>
<p>The MLE of [\(\pi_g\)]{.math .inline} is given by [\(\hat{\pi}_g = \frac{n_g}{n}\)]{.math .inline}. A [\((1-\alpha) \times 100 \%\)]{.math .inline} confidence interval for [\(\pi_g\)]{.math .inline} is given by [\[\hat{\pi}_g \pm z_{\alpha/2} \hat\sigma_{\hat\pi_g}.\]]{.math .display} where [\(\hat\sigma_{\hat\pi_g} = \sqrt{\frac{\hat{\pi}_g (1-\hat{\pi}_g)}{n}}\)]{.math .inline}.</p>
<h3 id="answer-4">ANSWER</h3>
<p>Letting [\(\alpha = 0.10\)]{.math .inline}, the MLE and [\(90\%\)]{.math .inline} confidence interval for [\(\pi_g\)]{.math .inline} is computed with the following R code:</p>
<p>snugshade
Highlighting
n [&lt;-]{style=&ldquo;color: 0.56,0.35,0.01&rdquo;} [sum]{style=&ldquo;color: 0.13,0.29,0.53&rdquo;}(obs) mle [&lt;-]{style=&ldquo;color: 0.56,0.35,0.01&rdquo;} obs[[1]{style=&ldquo;color: 0.00,0.00,0.81&rdquo;}][<strong>/</strong>]{style=&ldquo;color: 0.81,0.36,0.00&rdquo;}n</p>
<p>alpha [&lt;-]{style=&ldquo;color: 0.56,0.35,0.01&rdquo;} [0.1]{style=&ldquo;color: 0.00,0.00,0.81&rdquo;} s2 [&lt;-]{style=&ldquo;color: 0.56,0.35,0.01&rdquo;} mle[<em><strong><strong>]{style=&ldquo;color: 0.81,0.36,0.00&rdquo;}([1]{style=&ldquo;color: 0.00,0.00,0.81&rdquo;}[</strong>-</strong>]{style=&ldquo;color: 0.81,0.36,0.00&rdquo;}mle)[</em><em>/</em><em>]{style=&ldquo;color: 0.81,0.36,0.00&rdquo;}n q [&lt;-]{style=&ldquo;color: 0.56,0.35,0.01&rdquo;} [qnorm]{style=&ldquo;color: 0.13,0.29,0.53&rdquo;}([1]{style=&ldquo;color: 0.00,0.00,0.81&rdquo;}[</em><em>-</em><em>]{style=&ldquo;color: 0.81,0.36,0.00&rdquo;}alpha[</em><em>/</em><em>]{style=&ldquo;color: 0.81,0.36,0.00&rdquo;}[2]{style=&ldquo;color: 0.00,0.00,0.81&rdquo;}) [<em># should be around 1.645</em>]{style=&ldquo;color: 0.56,0.35,0.01&rdquo;} conf [&lt;-]{style=&ldquo;color: 0.56,0.35,0.01&rdquo;} [c]{style=&ldquo;color: 0.13,0.29,0.53&rdquo;}(mle [</em><em>-</em><em>]{style=&ldquo;color: 0.81,0.36,0.00&rdquo;} q [</em><strong><strong>]{style=&ldquo;color: 0.81,0.36,0.00&rdquo;} [sqrt]{style=&ldquo;color: 0.13,0.29,0.53&rdquo;}(s2), mle [</strong>+</strong>]{style=&ldquo;color: 0.81,0.36,0.00&rdquo;} q [*****]{style=&ldquo;color: 0.81,0.36,0.00&rdquo;} [sqrt]{style=&ldquo;color: 0.13,0.29,0.53&rdquo;}(s2))</p>
<p>We see that [\(\hat{\pi}_g = 0.782\)]{.math .inline} and a [\(90\%\)]{.math .inline} confidence interval is [\((0.761, 0.802)\)]{.math .inline}.</p>
<h2 id="part-f">Part (f)</h2>
<h3 id="answer-5">ANSWER</h3>
<p>Based on the observed data, we estimate that the probability [\(\pi_g\)]{.math .inline} of a green strain is between 0.761 and 0.802.</p>
<p>As expected, the null model specifies a value for [\(\pi_g\)]{.math .inline} ([\(0.75\)]{.math .inline}) that is not contained in the computed confidence interval.</p>
<h2 id="part-g">Part (g)</h2>
<p>The same reasoning as in part (a), except we use a different statistic called the likelihood ratio statistic, [\[G^2 = - 2 \log \Lambda\]]{.math .display} where [\[\Lambda = \frac{l(\pi_{g 0})}{l(\hat{\pi}_g)}.\]]{.math .display} where [\(\hat{\pi}_g\)]{.math .inline} is the maximum likelihood estimate [\(n_g / n\)]{.math .inline}.</p>
<p>This may be rewritten as [\[G^2 = 2 \sum_{j=1}^{c} \log\left(\frac{n_j}{n \pi_{j 0}}\right).\]]{.math .display}</p>
<p>Under the null model, [\(G^2\)]{.math .inline} is distributed [\(\chi^2\)]{.math .inline} with [\(1\)]{.math .inline} degree of freedom.</p>
<h3 id="answer-6">ANSWER</h3>
<p>We compute the observed [\(G_2\)]{.math .inline} statistic with the following R code:</p>
<p>snugshade</p>
<pre><code>## $stat
## [1] 6.120841
## 
## $p
## [1] 0.01335972
## 
## $df
## [1] 1
</code></pre>
<p>We see that [\(G^2\)]{.math .inline} realizes the value 6.121.</p>
<h2 id="part-h">Part (h)</h2>
<h3 id="answer-7">ANSWER</h3>
<p>The reference distribution is the chi-squared distribution with [\(1\)]{.math .inline} degrees of freedom.</p>
<p>The [\(p\)]{.math .inline}-value given [\(1\)]{.math .inline} degree of freedom is defined as [\[\text{$p$-value} = \operatorname{P}(G^2 &gt; \chi^2(1)),\]]{.math .display} which was computed to be [\(0.013\)]{.math .inline}. (For comparison, the [\(p\)]{.math .inline}-value for the [\(X^2\)]{.math .inline} test was [\(0.015\)]{.math .inline}.)</p>
<h2 id="part-i">Part (i)</h2>
<h3 id="answer-8">ANSWER</h3>
<p>According to the Fisher scale for interpreting [\(p\)]{.math .inline}-values, a [\(p\)]{.math .inline}-value of [\(0.01\)]{.math .inline} is considered <em>strong</em> evidence against the null model.</p>
<p>Since we obtained a [\(p\)]{.math .inline}-value of slightly larger, the data provides <em>strong</em> evidence against the genetic theory positing that the ratio of green to yellow seedlings is [\(3:1\)]{.math .inline}.</p>
<h2 id="part-j">Part (j)</h2>
<h3 id="answer-9">ANSWER</h3>
<p>The [\(p\)]{.math .inline}-value overstates evidence against the null model by comparing the null model to the alternative model that is best supported by the data.</p>
<h1 id="problem-2">Problem 2</h1>
<p>Consider the results from a study on the relationship between dose level and the severity of side effects. (Larger y values correspond to a more severe response.)</p>
<p>Data:</p>
<pre><code>            [\\(y = 0\\)]{.math .inline}   [\\(y = 1\\)]{.math .inline}   [\\(y = 2\\)]{.math .inline}   [\\(y = 3\\)]{.math .inline}   [\\(y = 4\\)]{.math .inline}
</code></pre>
<hr>
<p>low dose      6                              9                              6                              3                              1
medium dose   2                              5                              6                              6                              6
high dose     1                              4                              6                              8                              8</p>
<h2 id="preliminary-analysis">Preliminary analysis</h2>
<p>We model the cross-sectional data as being an observation of a [\(3 \times 5\)]{.math .inline} random matrix where the row levels, denoted by [\(X\)]{.math .inline}, correspond to dosage level and the column levels, denoted by [\(Y\)]{.math .inline}, correspond to severity of side effects. The elements (cells) of the random matrix are jointly sampled from the multinomial distribution [\[\{n_{i j}\} \sim \operatorname{MULT}(n, \{\pi_{i j}\}).\]]{.math .display} where [\(n_{i j}\)]{.math .inline} denotes the [\((i,j)\)]{.math .inline}-th element of the random matrix, [\(\pi_{i j}\)]{.math .inline} denotes the parameter that specifies the joint probability [\(\Pr(X=i,Y=j)\)]{.math .inline}, and [\(n\)]{.math .inline} denotes the number of trials.</p>
<p>The full model has a parameter space of dimension [\(3 \times 5 - 1 = 14\)]{.math .inline}.</p>
<h2 id="part-a-1">Part (a)</h2>
<p>We consider a simpler model than the full model where [\(X\)]{.math .inline} and [\(Y\)]{.math .inline} are independent, i.e., [\(\pi_{i j\,0} = \Pr(X=i)\Pr(Y=j) = \pi_{i+}\pi_{+j}\)]{.math .inline}. Since we are only free to specify [\(\pi_{i+}\)]{.math .inline} and [\(\pi_{+j}\)]{.math .inline}, the parameter space of the independence model is of dimension [\((3-1) + (5-1) = 6\)]{.math .inline}.</p>
<p>To decide whether the observed data is compatible with [\(X\)]{.math .inline} and [\(Y\)]{.math .inline} being independent, we perform the hypothesis test [\[H_0 : \{\pi_{i j}\} = \{\pi_{i j\,0}\}.\]]{.math .display}</p>
<p>An estimator of [\(\pi_{i+}\)]{.math .inline} is [\(\hat{\pi}_{i+} = n_{i+}/n\)]{.math .inline} and an estimator of [\(\hat{\pi}_{+j}\)]{.math .inline} is [\(n_{+j}/n\)]{.math .inline}, therefore an estimator of [\(\pi_{i j\,0}\)]{.math .inline} is given by [\[\hat{\pi}_{i j\,0} = \hat{\pi}_{i+} \hat{\pi}_{+j} = \frac{n_{i+}n_{+j}}{n^2}.\]]{.math .display} We perform a chi-square test for independence. The test statistic is given by [\[X^2 = \sum_{i=1}^{4} \frac{(n_{i j} - \hat{m}_{i j})^2}{\hat{m}_{i j}}\]]{.math .display} where [\(\hat{m}_{i j} = n \hat{\pi}_{i j\,0}\)]{.math .inline}. Asymptotically, [\(X^2\)]{.math .inline} is distributed [\(\chi^2\)]{.math .inline} with [\(14 - 6 = 8\)]{.math .inline} degrees of freedom.</p>
<h3 id="answer-10">ANSWER</h3>
<p>We compute the observed value of [\(X^2\)]{.math .inline} and its [\(p\)]{.math .inline}-value with the following R code:</p>
<p>snugshade</p>
<pre><code>## $stat
## [1] 14.35678
## 
## $p
## [1] 0.07292708
## 
## $df
## [1] 8
</code></pre>
<p>The test statistic [\(X^2\)]{.math .inline} realizes the value [\(14.357\)]{.math .inline} whose [\(p\)]{.math .inline}-value is 0.073. We consider this [\(p\)]{.math .inline}-value to be moderate evidence against the null model. Stated differently, the observed data is moderately incompatible with the independence model.</p>
<h2 id="part-b-1">Part (b)</h2>
<p>Under the assumption of a monotonic association between [\(X\)]{.math .inline} and [\(Y\)]{.math .inline}, if [\(X\)]{.math .inline} and [\(Y\)]{.math .inline} are independent then their [\(\gamma\)]{.math .inline} correlation is zero. To decide whether the observed data is compatible with [\(X\)]{.math .inline} and [\(Y\)]{.math .inline} being independent, we perform the hypothesis test [\[H_0 : \gamma = 0.\]]{.math .display}</p>
<p>The test statistic is given by [\[Z^* = \frac{\hat\gamma-0}{\hat\sigma(\hat\gamma)},\]]{.math .display} which is normally distributed [\(\mathcal{N}(0,1)\)]{.math .inline} under the null model.</p>
<h3 id="answer-11">ANSWER</h3>
<p>We compute [\(Z^*\)]{.math .inline} and [\(p\)]{.math .inline}-value with the following R code:</p>
<p>snugshade
Highlighting
gamma_test [&lt;-]{style=&ldquo;color: 0.56,0.35,0.01&rdquo;} [independence_test_monotonic_association]{style=&ldquo;color: 0.13,0.29,0.53&rdquo;}(obs)</p>
<p>The observed [\(Z^*\)]{.math .inline} is 4.402 and its [\(p\)]{.math .inline}-value is less than [\(0.001\)]{.math .inline}, which we consider to be very strong evidence against the independence model.</p>
<p>That is, the observed data provides very strong evidence against the independence model under the assumption of a monotonic association.</p>
<h2 id="part-c-1">Part (c)</h2>
<h3 id="answer-12">ANSWER</h3>
<p>Estimates for simpler models have smaller variances than for estimates from more complicated models.</p>
<h1 id="problem-3">Problem 3</h1>
<p>Consider the results from a prospective study on the relationship between sex and hair color.</p>
<p>snugshade
Highlighting
obs [&lt;-]{style=&ldquo;color: 0.56,0.35,0.01&rdquo;} [matrix]{style=&ldquo;color: 0.13,0.29,0.53&rdquo;}([c]{style=&ldquo;color: 0.13,0.29,0.53&rdquo;}([75]{style=&ldquo;color: 0.00,0.00,0.81&rdquo;},[16]{style=&ldquo;color: 0.00,0.00,0.81&rdquo;},[9]{style=&ldquo;color: 0.00,0.00,0.81&rdquo;},[120]{style=&ldquo;color: 0.00,0.00,0.81&rdquo;},[64]{style=&ldquo;color: 0.00,0.00,0.81&rdquo;},[16]{style=&ldquo;color: 0.00,0.00,0.81&rdquo;}),[nrow=]{style=&ldquo;color: 0.13,0.29,0.53&rdquo;}[2]{style=&ldquo;color: 0.00,0.00,0.81&rdquo;},[byrow=]{style=&ldquo;color: 0.13,0.29,0.53&rdquo;}[TRUE]{style=&ldquo;color: 0.56,0.35,0.01&rdquo;}) [dimnames]{style=&ldquo;color: 0.13,0.29,0.53&rdquo;}(obs) [&lt;-]{style=&ldquo;color: 0.56,0.35,0.01&rdquo;} [list]{style=&ldquo;color: 0.13,0.29,0.53&rdquo;}([sex=]{style=&ldquo;color: 0.13,0.29,0.53&rdquo;}[c]{style=&ldquo;color: 0.13,0.29,0.53&rdquo;}([&quot;male&quot;]{style=&ldquo;color: 0.31,0.60,0.02&rdquo;},[&quot;female&quot;]{style=&ldquo;color: 0.31,0.60,0.02&rdquo;}), [hc.level=]{style=&ldquo;color: 0.13,0.29,0.53&rdquo;}[c]{style=&ldquo;color: 0.13,0.29,0.53&rdquo;}([&quot;dark&quot;]{style=&ldquo;color: 0.31,0.60,0.02&rdquo;},[&quot;blonde&quot;]{style=&ldquo;color: 0.31,0.60,0.02&rdquo;},[&quot;red&quot;]{style=&ldquo;color: 0.31,0.60,0.02&rdquo;})) [print]{style=&ldquo;color: 0.13,0.29,0.53&rdquo;}(obs)</p>
<pre><code>##         hc.level
## sex      dark blonde red
##   male     75     16   9
##   female  120     64  16
</code></pre>
<h2 id="part-a-2">Part (a)</h2>
<h3 id="answer-13">ANSWER</h3>
<p>In a prospective study, each row of the table represents an independent multinomial. Thus, the data model is given by [\[\{n_{i j}\} \sim \operatorname{PROD\_MULT}(\{n_{i+}\},\{\pi_{j|i}\}).\]]{.math .display}</p>
<p>We are given a table of [\(I=2\)]{.math .inline} rows and [\(J=3\)]{.math .inline} columns, and thus we have [\(I\)]{.math .inline} independent multinomials. Therefore, the likelihood function is given by [\[l(\{\pi_{j|i}\}) = \prod_{i=1}^{I} \frac{n_{i+}!}{\prod_{j=1}^{J} n_{i j}!} \prod_{j=1}^{J} \pi_{j|i}^{n_{i j}}.\]]{.math .display} Observe that [\[l(\{\pi_{j|i}\}) \propto \prod_{i=1}^{I} \prod_{j=1}^{J} \pi_{j|i}^{n_{i j}}.\]]{.math .display}</p>
<p>Under the full model, the maximum likelihood of [\(\pi_{j|i}\)]{.math .inline} is given by [\[\hat{\pi}_{j | i}^{(F)} = \frac{n_{i j}}{n_{i+}}\]]{.math .display} and under the independence model it is given by [\[\hat{\pi}_{j | i}^{(I)} = \frac{n_{+j}}{n}\]]{.math .display} for [\(i \in \{1,2\}\)]{.math .inline} and [\(j \in \{1,2,3\}\)]{.math .inline}.</p>
<h2 id="part-b-2">Part (b)</h2>
<p>The expected count [\(\hat{m}_{i j}\)]{.math .inline} under the independence model is given by [\[\hat{m}_{i j} = \frac{n_{i+}n_{+j}}{n} = n_{i+} \hat{\pi}_{j|i}^{(I)}.\]]{.math .display}</p>
<h3 id="answer-14">ANSWER</h3>
<p>We use the R function [\(\operatorname{chisq.test}\)]{.math .inline} to compute the expected cell counts [\(\{\hat{m}_{i j}\}\)]{.math .inline}:</p>
<p>snugshade</p>
<pre><code>##         hc.level
## sex      dark blonde    red
##   male     65 26.667  8.333
##   female  130 53.333 16.667
</code></pre>
<h2 id="part-c-2">Part (c)</h2>
<p>In the full model, the paramter space is given by [\[\vec{\pi}^{(F)}(\theta_1,\theta_2, \theta_3, \theta_4) = \begin{pmatrix} \pi_{1|1} = \theta_1 &amp; \pi_{2|1} = \theta_2 &amp; \pi_{3|1} = 1-\theta_1-\theta_2\\ \pi_{1|2} = \theta_3 &amp; \pi_{2|2} = \theta_4 &amp; \pi_{3|2} = 1-\theta_3-\theta_4 \end{pmatrix}\]]{.math .display} which is of dimension [\(I(J-1) = 4\)]{.math .inline} and under the independence model, the parameter space is [\[\vec{\pi}^{(I)}(\theta_1,\theta_2) = \begin{pmatrix} \pi_{1|1} = \theta_1 &amp; \pi_{2|1} = \theta_2 &amp; \pi_{3|1} = 1-\theta_1-\theta_2\\ \pi_{1|2} = \theta_1 &amp; \pi_{2|2} = \theta_2 &amp; \pi_{3|2} = 1-\theta_1-\theta_2 \end{pmatrix}\]]{.math .display} which is of dimension [\(J-1=2\)]{.math .inline}. Thus, under the independence model, [\(G^2\)]{.math .inline} is distributed [\(\chi^2\)]{.math .inline} with [\(\operatorname{df} = I(J-1) - (J-1) = (J-1)(I-1) = 2\)]{.math .inline}</p>
<h3 id="answer-15">ANSWER</h3>
<p>We compute [\(G^2\)]{.math .inline} from the observed counts [\(\{n_{i j}\}\)]{.math .inline} and the expected counts [\(\{\hat{m}_{i j}\}\)]{.math .inline}:</p>
<p>snugshade
Highlighting
I [&lt;-]{style=&ldquo;color: 0.56,0.35,0.01&rdquo;} [dim]{style=&ldquo;color: 0.13,0.29,0.53&rdquo;}(obs)[[1]{style=&ldquo;color: 0.00,0.00,0.81&rdquo;}] J [&lt;-]{style=&ldquo;color: 0.56,0.35,0.01&rdquo;} [dim]{style=&ldquo;color: 0.13,0.29,0.53&rdquo;}(obs)[[2]{style=&ldquo;color: 0.00,0.00,0.81&rdquo;}] G2 [&lt;-]{style=&ldquo;color: 0.56,0.35,0.01&rdquo;} [2]{style=&ldquo;color: 0.00,0.00,0.81&rdquo;}[<em><strong><strong>]{style=&ldquo;color: 0.81,0.36,0.00&rdquo;}[sum]{style=&ldquo;color: 0.13,0.29,0.53&rdquo;}(obs[</strong></strong></em>]{style=&ldquo;color: 0.81,0.36,0.00&rdquo;}[log]{style=&ldquo;color: 0.13,0.29,0.53&rdquo;}(obs[<strong>/</strong>]{style=&ldquo;color: 0.81,0.36,0.00&rdquo;}m.hat)) df [&lt;-]{style=&ldquo;color: 0.56,0.35,0.01&rdquo;} (I[-1]{style=&ldquo;color: 0.00,0.00,0.81&rdquo;})[*****]{style=&ldquo;color: 0.81,0.36,0.00&rdquo;}(J[-1]{style=&ldquo;color: 0.00,0.00,0.81&rdquo;}) p.value [&lt;-]{style=&ldquo;color: 0.56,0.35,0.01&rdquo;} [pchisq]{style=&ldquo;color: 0.13,0.29,0.53&rdquo;}(G2,df,[lower.tail =]{style=&ldquo;color: 0.13,0.29,0.53&rdquo;} [FALSE]{style=&ldquo;color: 0.56,0.35,0.01&rdquo;})</p>
<p>[print]{style=&ldquo;color: 0.13,0.29,0.53&rdquo;}([round]{style=&ldquo;color: 0.13,0.29,0.53&rdquo;}(G2,[3]{style=&ldquo;color: 0.00,0.00,0.81&rdquo;}))</p>
<pre><code>## [1] 9.325
</code></pre>
<p>snugshade
Highlighting
[print]{style=&ldquo;color: 0.13,0.29,0.53&rdquo;}([round]{style=&ldquo;color: 0.13,0.29,0.53&rdquo;}(p.value,[3]{style=&ldquo;color: 0.00,0.00,0.81&rdquo;}))</p>
<pre><code>## [1] 0.009
</code></pre>
<p>We obtain a [\(p\)]{.math .inline}-value around [\(0.01\)]{.math .inline}, which we consider to be strong evidence against the independence model (the data supports the general association model). That is to say, the conditional distribution [\[\Pr(\text{hair color} \,|\, \text{sex} = \text{male})\]]{.math .display} and [\[\Pr(\text{hair color} \,|\, \text{sex} = \text{female}).\]]{.math .display} are different.</p>
<h2 id="part-d-1">Part (d)</h2>
<h3 id="answer-16">ANSWER</h3>
<p>We display a table comparing expected and observed such that if the observed is less than the expected, display [\(-1\)]{.math .inline}, and if observed is greater than expected, display a [\(1\)]{.math .inline}:</p>
<p>snugshade
Highlighting
[print]{style=&ldquo;color: 0.13,0.29,0.53&rdquo;}([sign]{style=&ldquo;color: 0.13,0.29,0.53&rdquo;}(obs[<strong>-</strong>]{style=&ldquo;color: 0.81,0.36,0.00&rdquo;}m.hat))</p>
<pre><code>##         hc.level
## sex      dark blonde red
##   male      1     -1   1
##   female   -1      1  -1
</code></pre>
<p>The observed data is compatible with a model where males are more likely to have dark or red hair (and less likely to have blonde hair) and females are more likely to have blonde hair (and less likely to have dark or red hair).</p>
<h1 id="problem-4">Problem 4</h1>
<p>According to the Hardy-Weinberg model, the number of flies resulting from a crossing of genetic traits are in categories [\(1\)]{.math .inline}, [\(2\)]{.math .inline}, [\(3\)]{.math .inline} with probabilities [\[\begin{aligned} \pi_{1 o}(\theta) &amp;= (1-\theta)^2\\ \pi_{2 o}(\theta) &amp;= 2\theta(1-\theta)\\ \pi_{3 o}(\theta) &amp;= \theta^2 \end{aligned}\]]{.math .display}</p>
<h2 id="part-a-3">Part (a)</h2>
<p>We assume the data model is given by [\[(n_1,n_2,n_3) \sim \operatorname{MULT}(n, \pi_1, \pi_2, \pi_3)\]]{.math .display} where [\(n_j\)]{.math .inline} denotes the number of flies in category [\(j\)]{.math .inline} and [\(\pi_j\)]{.math .inline} denotes the probability a fly is in category [\(j\)]{.math .inline}.</p>
<p>Under the specified model, the likelihood function is given by [\[\operatorname{L}(\theta) \propto \prod_{j=1}^{3} \pi_{j o}(\theta)^{n_j}\]]{.math .display} and the kernel of the log-likelihood function is given by [\[\begin{aligned} l(\theta) &amp;= \sum_{j=1}^{3} n_j \log \pi_{j o}(\theta)\\ &amp;= n_1 \log \pi_{1 o}(\theta) + n_2 \log \pi_{2 o}(\theta) + n_3 \log \pi_{3 o}(\theta)\\ &amp;= n_1 \log (1-\theta)^2 + n_2 \log 2 \theta(1-\theta) + n_3 \log \theta^2\\ &amp;= 2 n_1 \log (1-\theta) + n_2 \log \theta + n_2 \log(1-\theta) + 2 n_3 \log \theta + \rm{const}\\ &amp;= (2 n_1 + n_2) \log (1-\theta) + ( n_2 + 2 n_3)\log \theta + \rm{const}. \end{aligned}\]]{.math .display}</p>
<p>The derivative of the log-likelihood is thus given by [\[\frac{d l}{d \theta} = -\frac{2 n_1 + n_2}{1-\theta} + \frac{n_2 + 2 n_3}{\theta}.\]]{.math .display}</p>
<p>The ML estimate of [\(\theta\)]{.math .inline} is given by [\[\left. \frac{d l}{d \theta} \right\vert_{\hat\theta} = 0.\]]{.math .display} Solving for [\(\hat\theta\)]{.math .inline}, we see that [\[\frac{2 n_1 + n_2}{1-\hat\theta} = \frac{n_2 + 2 n_3}{\hat\theta}.\]]{.math .display} Next, we take the reciprocal of both sides, [\[\frac{1-\hat\theta}{2 n_1 + n_2} = \frac{\hat\theta}{n_2 + 2 n_3}.\]]{.math .display} Expanding the LHS, we get [\[\frac{1}{2 n_1 + n_2} - \frac{\hat\theta}{2 n_1 + n_2} = \frac{\hat\theta}{n_2 + 2 n_3}\]]{.math .display} which may be rewritten as [\[\hat\theta \left(\frac{1}{2 n_1 + n_2} + \frac{1}{n_2 + 2 n_3}\right) = \frac{1}{2 n_1 + n_2}.\]]{.math .display} Dividing both sides by the part in parentheses, we get [\[\hat\theta = \frac{1}{(2 n_1 + n_2) \left(\frac{1}{2 n_1 + n_2} + \frac{1}{n_2 + 2 n_3}\right)},\]]{.math .display} which simplifies to [\[\hat\theta = \frac{1}{1 + \frac{2 n_1 + n_2}{n_2 + 2 n_3}} = \frac{1}{\frac{2 n_3 + 2 n_1 + 2 n_2}{n_2 + 2 n_3}}.\]]{.math .display} Performing the division, we get the simplification [\[\hat\theta = \frac{n_2 + 2 n_3}{2(n_3 + n_1 + n_2)}.\]]{.math .display}</p>
<h3 id="answer-17">ANSWER</h3>
<p>Observe that [\(n_1 + n_2 + n_3\)]{.math .inline} is [\(n\)]{.math .inline}, thus [\[\hat\theta = \frac{n_2 + 2 n_3}{2 n}.\]]{.math .display}</p>
<h2 id="part-b-3">Part (b)</h2>
<p>Using the MLE equation, we compute the result using R:</p>
<p>snugshade
Highlighting
n [=]{style=&ldquo;color: 0.56,0.35,0.01&rdquo;} [c]{style=&ldquo;color: 0.13,0.29,0.53&rdquo;}([40]{style=&ldquo;color: 0.00,0.00,0.81&rdquo;},[50]{style=&ldquo;color: 0.00,0.00,0.81&rdquo;},[10]{style=&ldquo;color: 0.00,0.00,0.81&rdquo;}) mle [&lt;-]{style=&ldquo;color: 0.56,0.35,0.01&rdquo;} (n[[2]{style=&ldquo;color: 0.00,0.00,0.81&rdquo;}] [<strong>+</strong>]{style=&ldquo;color: 0.81,0.36,0.00&rdquo;} [2]{style=&ldquo;color: 0.00,0.00,0.81&rdquo;}[*<strong><strong>]{style=&ldquo;color: 0.81,0.36,0.00&rdquo;}n[[3]{style=&ldquo;color: 0.00,0.00,0.81&rdquo;}])[</strong>/</strong>]{style=&ldquo;color: 0.81,0.36,0.00&rdquo;}[sum]{style=&ldquo;color: 0.13,0.29,0.53&rdquo;}(n)</p>
<h3 id="answer-18">ANSWER</h3>
<p>We see that [\[\hat\theta = 0.7.\]]{.math .display} Plugging in this result, [\[\vec{\pi}_{o}(\hat\theta) = ( (1-\hat\theta)^2, 2\hat\theta(1-\hat\theta), \hat\theta^2)'\]]{.math .display} which we compute with R:</p>
<p>snugshade
Highlighting
pi0.hats [&lt;-]{style=&ldquo;color: 0.56,0.35,0.01&rdquo;} [c]{style=&ldquo;color: 0.13,0.29,0.53&rdquo;}(([1]{style=&ldquo;color: 0.00,0.00,0.81&rdquo;}[<strong>-</strong>]{style=&ldquo;color: 0.81,0.36,0.00&rdquo;}mle)[<strong>^</strong>]{style=&ldquo;color: 0.81,0.36,0.00&rdquo;}[2]{style=&ldquo;color: 0.00,0.00,0.81&rdquo;}, [2]{style=&ldquo;color: 0.00,0.00,0.81&rdquo;}[<em><strong><strong>]{style=&ldquo;color: 0.81,0.36,0.00&rdquo;}mle[</strong></strong></em>]{style=&ldquo;color: 0.81,0.36,0.00&rdquo;}([1]{style=&ldquo;color: 0.00,0.00,0.81&rdquo;}[<strong>-</strong>]{style=&ldquo;color: 0.81,0.36,0.00&rdquo;}mle), mle[<strong>^</strong>]{style=&ldquo;color: 0.81,0.36,0.00&rdquo;}[2]{style=&ldquo;color: 0.00,0.00,0.81&rdquo;})</p>
<p>We see that [\(\vec{\pi}_{o}(\hat\theta) = (0.09, 0.42, 0.49)'\)]{.math .inline}.</p>
<h2 id="part-c-3">Part (c)</h2>
<h3 id="answer-19">ANSWER</h3>
<p>The parameter space of the Hardy-Weinberg model is a function of a single parameter [\(\theta\)]{.math .inline} and thus has a dimension of [\(1\)]{.math .inline}. The parameter space of the full model is [\(2\)]{.math .inline}. Thus, the reference distribution is [\(\chi^2\)]{.math .inline} with [\(\operatorname{df} = 2 - 1 = 1\)]{.math .inline} degrees of freedom.</p>
<p>The following R code computes the realization of [\(G^2\)]{.math .inline}, denoted by [\(G_0^2\)]{.math .inline}, and its [\(p\)]{.math .inline}-value:</p>
<p>snugshade</p>
<pre><code>## $stat
## [1] 104.983
## 
## $p
## [1] 1.231867e-24
## 
## $df
## [1] 1
</code></pre>
<p>We see that [\(G_0^2 = 104.983\)]{.math .inline} with a [\(p\)]{.math .inline}-value less than [\(0.001\)]{.math .inline}, which we consider to be very strong evidence against the Hardy-Weinberg.</p>
<h1 id="library-of-test-functions">Library of test functions</h1>
<div class="highlight sourceCode R"><pre tabindex="0" class="chroma"><code class="language-fallback" data-lang="fallback"><span class="line"><span class="cl"># function for performing a multinomial goodness of fit hypothesis test
</span></span><span class="line"><span class="cl"># with a specified null model pi.0 in which pi.0 is the result of t parameters.
</span></span><span class="line"><span class="cl">#
</span></span><span class="line"><span class="cl"># input:
</span></span><span class="line"><span class="cl">#     obs: vector of counts
</span></span><span class="line"><span class="cl">#     pi.0: vector of hypothesized probabilites,
</span></span><span class="line"><span class="cl">#     t: dimension of the parameter space under the null hypothesis.
</span></span><span class="line"><span class="cl"># 
</span></span><span class="line"><span class="cl"># outputs: two lists, one for X2 and one for G2. each list has:
</span></span><span class="line"><span class="cl">#     X2: list relevant results for X^2 test
</span></span><span class="line"><span class="cl">#     G2: list of relevant results for G^2 test, e.g.:
</span></span><span class="line"><span class="cl">#       list(stat,p,df,reject) where
</span></span><span class="line"><span class="cl">#         p: p-value of the obs under the null model
</span></span><span class="line"><span class="cl">#         df: degrees of freedom of the reference distribution (chi-square)
</span></span><span class="line"><span class="cl">multinomial_goodness_of_fit &lt;- function(obs, pi.0, t=0)
</span></span><span class="line"><span class="cl">{
</span></span><span class="line"><span class="cl">  n &lt;- sum(obs)                 # number of observations
</span></span><span class="line"><span class="cl">  t.full &lt;- length(obs)-1       # dim of parameter space for the full model.
</span></span><span class="line"><span class="cl">  df &lt;- t.full-t                # degrees of freedom for the ref distribution
</span></span><span class="line"><span class="cl">  m.0 &lt;- n*pi.0                 # expected observations (for given n)
</span></span><span class="line"><span class="cl">  
</span></span><span class="line"><span class="cl">  G2 &lt;- 2*sum(obs*log(obs/m.0)) # log-likelihood ratio test statistic
</span></span><span class="line"><span class="cl">  G2.p &lt;- pchisq(q=G2,df=df,lower.tail=FALSE)
</span></span><span class="line"><span class="cl">
</span></span><span class="line"><span class="cl">  X2 &lt;- sum((obs-m.0)^2/m.0)   # test statistic
</span></span><span class="line"><span class="cl">  X2.p &lt;- pchisq(q=X2,df=df,lower.tail=FALSE)
</span></span><span class="line"><span class="cl">
</span></span><span class="line"><span class="cl">  # return relevant test statistics
</span></span><span class="line"><span class="cl">  list(m.0=m.0,pi.0=pi.0,
</span></span><span class="line"><span class="cl">       X2=list(stat=X2,p=X2.p,df=df),
</span></span><span class="line"><span class="cl">       G2=list(stat=G2,p=G2.p,df=df))
</span></span><span class="line"><span class="cl">}
</span></span><span class="line"><span class="cl">
</span></span><span class="line"><span class="cl"># obs is an IxJ matrix representing cross-sectional data (observed counts).
</span></span><span class="line"><span class="cl"># tests for independence P(X,Y) = P(X)P(Y).
</span></span><span class="line"><span class="cl">multinomial_goodness_of_fit_independence_test &lt;- function(obs)
</span></span><span class="line"><span class="cl">{
</span></span><span class="line"><span class="cl">  I &lt;- dim(obs)[1]
</span></span><span class="line"><span class="cl">  J &lt;- dim(obs)[2]
</span></span><span class="line"><span class="cl">  t &lt;- (I-1)+(J-1)
</span></span><span class="line"><span class="cl">  
</span></span><span class="line"><span class="cl">  n &lt;- sum(obs)  
</span></span><span class="line"><span class="cl">  row.sum &lt;- apply(obs,1,sum)
</span></span><span class="line"><span class="cl">  col.sum &lt;- apply(obs,2,sum)
</span></span><span class="line"><span class="cl">  m.0 &lt;- matrix(row.sum) %*% t(matrix(col.sum))/n
</span></span><span class="line"><span class="cl">  
</span></span><span class="line"><span class="cl">  multinomial_goodness_of_fit(obs=obs,pi.0=m.0/n,t=t)
</span></span><span class="line"><span class="cl">}
</span></span><span class="line"><span class="cl">
</span></span><span class="line"><span class="cl">independence_test_monotonic_association &lt;- function(obs)
</span></span><span class="line"><span class="cl">{
</span></span><span class="line"><span class="cl">  # to compute the estimate of gamma and the standard error, we need MESS
</span></span><span class="line"><span class="cl">  library(&#34;MESS&#34;)
</span></span><span class="line"><span class="cl">  
</span></span><span class="line"><span class="cl">  # gkgamma takes an IxJ matrix as an input
</span></span><span class="line"><span class="cl">  gk.result &lt;- gkgamma(obs)
</span></span><span class="line"><span class="cl">  
</span></span><span class="line"><span class="cl">  # compute gamma.hat and its standard error
</span></span><span class="line"><span class="cl">  gamma.hat &lt;- gk.result$estimate
</span></span><span class="line"><span class="cl">  se &lt;- gk.result$se1
</span></span><span class="line"><span class="cl">  
</span></span><span class="line"><span class="cl">  # compute the z statistic and p-value for testing gamma=0 (independence)
</span></span><span class="line"><span class="cl">  z &lt;- gamma.hat / se
</span></span><span class="line"><span class="cl">  p.value &lt;- 2*pnorm(abs(z),lower.tail = FALSE)
</span></span><span class="line"><span class="cl">  
</span></span><span class="line"><span class="cl">  list(gamma=gamma.hat,ase=se,stat=z,p=p.value)
</span></span><span class="line"><span class="cl">}
</span></span></code></pre></div>
      </div>

    
    <nav class="post-navigation">
      
      <a href="../../../probsets/stat579/stat579-final-exam/" class="nav-prev">
        <span class="nav-label">← Previous</span>
        <span class="nav-title">Discrete Multivariate Analysis - STAT 579 - Final Exam</span>
      </a>
      
      
    </nav>
    
  </article>
  </div>
</div>

  </main>
  
  <footer class="elegant-footer" role="contentinfo" aria-label="Site footer">
    <div class="footer-content">
      <div class="footer-about">
        <h3>metafunctor</h3>
        <p>Research engineer and computer scientist specializing in machine learning, statistical computing, and open source software development.</p>
        <nav aria-label="Social media links" class="social-links">
          
          <a href="https://twitter.com/queelius" target="_blank" rel="noopener noreferrer" aria-label="Twitter">
            <i class="fab fa-twitter" aria-hidden="true"></i>
          </a>
          
          <a href="https://github.com/queelius" target="_blank" rel="noopener noreferrer" aria-label="GitHub">
            <i class="fab fa-github" aria-hidden="true"></i>
          </a>
          
          <a href="https://www.linkedin.com/in/alexander-towell-487015151/" target="_blank" rel="noopener noreferrer" aria-label="LinkedIn">
            <i class="fab fa-linkedin" aria-hidden="true"></i>
          </a>
          
          <a href="../../../index.xml" target="_blank" rel="noopener noreferrer" aria-label="RSS">
            <i class="fas fa-rss" aria-hidden="true"></i>
          </a>
          
          <a href="mailto:lex@metafunctor.com" target="_blank" rel="noopener noreferrer" aria-label="Email">
            <i class="fas fa-envelope" aria-hidden="true"></i>
          </a>
          
          <a href="https://keybase.io/queelius" target="_blank" rel="noopener noreferrer" aria-label="Keybase">
            <i class="fab fa-keybase" aria-hidden="true"></i>
          </a>
          
          <a href="https://www.youtube.com/@queelius" target="_blank" rel="noopener noreferrer" aria-label="YouTube">
            <i class="fab fa-youtube" aria-hidden="true"></i>
          </a>
          
          <a href="https://scholar.google.com/citations?view_op=list_works&amp;hl=en&amp;user=E9mnFzQAAAAJ" target="_blank" rel="noopener noreferrer" aria-label="Google Scholar">
            <i class="fas fa-graduation-cap" aria-hidden="true"></i>
          </a>
          
          <a href="https://orcid.org/my-orcid?orcid=0000-0001-6443-9897" target="_blank" rel="noopener noreferrer" aria-label="ORCID">
            <i class="fab fa-orcid" aria-hidden="true"></i>
          </a>
          
        </nav>
      </div>

      <nav class="footer-section" aria-labelledby="footer-content">
        <h4 id="footer-content">Content</h4>
        <div class="footer-links">
          <a href="http://localhost:1313/post/">Posts</a>
          <a href="http://localhost:1313/papers/">Papers</a>
          <a href="http://localhost:1313/series/">Series</a>
          <a href="http://localhost:1313/publications/">Publications</a>
          <a href="http://localhost:1313/writing/">Writing</a>
        </div>
      </nav>

      <nav class="footer-section" aria-labelledby="footer-code">
        <h4 id="footer-code">Code</h4>
        <div class="footer-links">
          <a href="http://localhost:1313/projects/">Projects</a>
          <a href="https://github.com/queelius" target="_blank" rel="noopener noreferrer">GitHub</a>
          <a href="https://pypi.org/user/queelius/" target="_blank" rel="noopener noreferrer">PyPI</a>
        </div>
      </nav>

      <nav class="footer-section" aria-labelledby="footer-connect">
        <h4 id="footer-connect">Connect</h4>
        <div class="footer-links">
          <a href="http://localhost:1313/about/">About</a>
          <a href="mailto:lex@metafunctor.com">Contact</a>
          <a href="http://localhost:1313/index.xml" type="application/rss+xml">RSS Feed</a>
        </div>
      </nav>
    </div>
    <div class="footer-bottom">
      <p class="copyright">
        © 2026 Alex Towell. All rights reserved.
      </p>
      <p class="accessibility-note">
        <a href="#main-content">Back to top</a>
      </p>
    </div>
  </footer>

  
  <script src="../../../js/performance-optimizations.js" defer></script>
  <script src="../../../js/performance-enhancements.js" defer></script>

  
  <script src="../../../js/mobile-menu.js" defer></script>
  <script src="../../../js/modern-interactions.js" defer></script>
  <script src="../../../js/search.js" defer></script>

  
  <script src="../../../js/reading-progress.js" defer></script>
  <script src="../../../js/copy-code.js" defer></script>
  <script src="../../../js/anchor-links.js" defer></script>

  
  <button id="back-to-top" aria-label="Back to top" style="display: none; position: fixed; bottom: 30px; right: 30px; z-index: 1000; background: linear-gradient(135deg, #667eea 0%, #764ba2 100%); color: white; border: none; border-radius: 50%; width: 50px; height: 50px; cursor: pointer; box-shadow: 0 4px 15px rgba(102, 126, 234, 0.4); transition: all 0.3s ease;">
    <i class="fas fa-arrow-up"></i>
  </button>

  <script>
    
    const backToTop = document.getElementById('back-to-top');
    window.addEventListener('scroll', () => {
      if (window.scrollY > 300) {
        backToTop.style.display = 'block';
      } else {
        backToTop.style.display = 'none';
      }
    });
    backToTop.addEventListener('click', () => {
      window.scrollTo({ top: 0, behavior: 'smooth' });
    });
  </script>

  
  <script data-goatcounter="https://queelius.goatcounter.com/count"
          async src="//gc.zgo.at/count.js"></script>
</body>
</html>
