<!doctype html><html lang=en-us prefix="og: https://ogp.me/ns#"><head><meta charset=utf-8><meta name=viewport content="width=device-width,initial-scale=1,shrink-to-fit=no"><meta http-equiv=X-UA-Compatible content="IE=edge"><title>Statistical Methods - STAT 581 - Problem Set 6 | metafunctor</title><meta name=title content="Statistical Methods - STAT 581 - Problem Set 6 | metafunctor"><meta name=description content="A soft drink bottler is interested in studying the effects on a filling process. A factorial experiment is run using three factors: percent carbonation (in %),"><meta name=keywords content="machine learning,statistical computing,open source,research,computer science,artificial intelligence"><meta name=author content="Alex Towell"><meta name=robots content="index, follow, max-image-preview:large, max-snippet:-1, max-video-preview:-1"><link rel=canonical href=https://queelius.github.io/probsets/stat581/stat581-hw6/><link rel=alternate hreflang=en href=https://queelius.github.io/probsets/stat581/stat581-hw6/><link rel=alternate hreflang=x-default href=https://queelius.github.io/probsets/stat581/stat581-hw6/><style>*,*::before,*::after{box-sizing:border-box;margin:0;padding:0}html{font-size:16px;-webkit-font-smoothing:antialiased;-moz-osx-font-smoothing:grayscale}body{margin:0;font-family:-apple-system,BlinkMacSystemFont,segoe ui,roboto,sans-serif;font-size:17px;line-height:1.7;color:#2c2c2c;background:#fff}.elegant-header{position:sticky;top:0;z-index:1000;background:rgba(254,254,254,.95);backdrop-filter:blur(10px);border-bottom:1px solid rgba(0,0,0,8%)}.header-inner{max-width:1400px;margin:0 auto;padding:1rem 2rem;display:flex;justify-content:space-between;align-items:center}.site-logo{font-size:1.5rem;font-weight:700;color:#2c2c2c;text-decoration:none}.nav-primary ul{display:flex;gap:2rem;list-style:none}.nav-primary a{font-size:.9rem;font-weight:500;color:#4a4a4a;text-decoration:none}.hero-elegant{padding:5rem 2rem;text-align:center;background:linear-gradient(180deg,#fafafa 0%,#ffffff 100%)}.hero-title{font-size:3.5rem;font-weight:700;margin-bottom:1rem;background:linear-gradient(135deg,#2c2c2c 0%,#003d7a 100%);-webkit-background-clip:text;-webkit-text-fill-color:transparent;background-clip:text}.hero-subtitle{font-size:1.25rem;color:#4a4a4a;max-width:600px;margin:0 auto 3rem}.skip-to-main{position:absolute;top:-100px;left:0;background:#0050a0;color:#fff;padding:.5rem 1rem;text-decoration:none;font-weight:600;z-index:10000}.skip-to-main:focus{top:0}.preload *{transition:none!important}</style><link rel=preconnect href=https://fonts.googleapis.com><link rel=preconnect href=https://fonts.gstatic.com crossorigin><link rel=preconnect href=https://cdnjs.cloudflare.com crossorigin><link rel=dns-prefetch href=https://www.google-analytics.com><link rel=dns-prefetch href=https://cdn.jsdelivr.net><meta property="og:type" content="article"><meta property="og:url" content="https://queelius.github.io/probsets/stat581/stat581-hw6/"><meta property="og:title" content="Statistical Methods - STAT 581 - Problem Set 6"><meta property="og:description" content="A soft drink bottler is interested in studying the effects on a filling process. A factorial experiment is run using three factors: percent carbonation (in %),"><meta property="og:image" content="https://queelius.github.io/images/og-image.jpg"><meta property="og:image:width" content="1200"><meta property="og:image:height" content="630"><meta property="og:site_name" content="metafunctor"><meta property="og:locale" content="en_US"><meta property="article:author" content="Alex Towell"><meta property="article:published_time" content="2021-12-01T00:00:00Z"><meta property="article:modified_time" content="2025-12-16T19:22:58-06:00"><meta property="article:tag" content="statistics"><meta property="article:tag" content="statistical-methods"><meta property="article:tag" content="R"><meta property="article:tag" content="SIUe"><meta name=twitter:card content="summary_large_image"><meta name=twitter:url content="https://queelius.github.io/probsets/stat581/stat581-hw6/"><meta name=twitter:title content="Statistical Methods - STAT 581 - Problem Set 6"><meta name=twitter:description content="A soft drink bottler is interested in studying the effects on a filling process. A factorial experiment is run using three factors: percent carbonation (in %),"><meta name=twitter:image content="https://queelius.github.io/images/og-image.jpg"><meta name=twitter:site content="@queelius"><meta name=twitter:creator content="@queelius"><script type=application/ld+json>{"@context":"https://schema.org","@graph":[{"@type":"Article","@id":"https:\/\/queelius.github.io\/probsets\/stat581\/stat581-hw6\/#primaryContent","headline":"Statistical Methods - STAT 581 - Problem Set 6","description":"A soft drink bottler is interested in studying the effects on a filling process. A factorial experiment is run using three factors: percent carbonation (in %),","url":"https:\/\/queelius.github.io\/probsets\/stat581\/stat581-hw6\/","inLanguage":"en-US","datePublished":"2021-12-01T00:00:00Z","dateModified":"2025-12-16T19:22:58-06:00","wordCount":1909,"timeRequired":"PT9M","author":{"@type":"Person","@id":"https:\/\/queelius.github.io\/#author","name":"Alex Towell","url":"https:\/\/queelius.github.io\/about/"},"publisher":{"@type":"Organization","@id":"https:\/\/queelius.github.io\/#organization","name":"metafunctor","url":"https:\/\/queelius.github.io\/","logo":{"@type":"ImageObject","url":"https:\/\/queelius.github.io\/images\/og-image.jpg"}},"keywords":["statistics","statistical-methods","R","SIUe"]},{"@type":"BreadcrumbList","@id":"https:\/\/queelius.github.io\/probsets\/stat581\/stat581-hw6\/#breadcrumb","itemListElement":[{"@type":"ListItem","position":1,"name":"Home","item":"https:\/\/queelius.github.io\/"},{"@type":"ListItem","position":2,"name":"STAT 581 - Statistical Methods - SIUe - Fall 2021","item":"https:\/\/queelius.github.io\/probsets\/stat581\/"},{"@type":"ListItem","position":3,"name":"Statistical Methods - STAT 581 - Problem Set 6","item":"https:\/\/queelius.github.io\/probsets\/stat581\/stat581-hw6\/"}]}]}</script><link rel=preload href="https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700;800&family=Lora:ital,wght@0,400;0,600;0,700;1,400&family=JetBrains+Mono:wght@400;500&display=swap" as=style><link href="https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700;800&family=Lora:ital,wght@0,400;0,600;0,700;1,400&family=JetBrains+Mono:wght@400;500&display=swap" rel=stylesheet media=print onload='this.media="all"'><noscript><link href="https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700;800&family=Lora:ital,wght@0,400;0,600;0,700;1,400&family=JetBrains+Mono:wght@400;500&display=swap" rel=stylesheet></noscript><link rel=stylesheet href=/css/refined-elegant.css><link rel=stylesheet href=/css/micro-interactions.css><link rel=stylesheet href=/css/elegant.css media=print onload='this.media="all"'><link rel=stylesheet href=/css/custom.css><link rel=stylesheet href=/css/beautify.css><link rel=stylesheet href=https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css crossorigin=anonymous><link rel=stylesheet href=https://cdn.jsdelivr.net/npm/katex@0.16.8/dist/katex.min.css><script defer src=https://cdn.jsdelivr.net/npm/katex@0.16.8/dist/katex.min.js></script><script defer src=https://cdn.jsdelivr.net/npm/katex@0.16.8/dist/contrib/auto-render.min.js></script><script>document.addEventListener("DOMContentLoaded",function(){renderMathInElement(document.body,{delimiters:[{left:"$$",right:"$$",display:!0},{left:"\\[",right:"\\]",display:!0},{left:"$",right:"$",display:!1},{left:"\\(",right:"\\)",display:!1}]})})</script><script defer src=https://cdn.jsdelivr.net/npm/fuse.js@7.0.0/dist/fuse.min.js></script><script async src="https://www.googletagmanager.com/gtag/js?id=G-E08ZXTFTTY"></script><script>var dnt,doNotTrack=!1;if(!1&&(dnt=navigator.doNotTrack||window.doNotTrack||navigator.msDoNotTrack,doNotTrack=dnt=="1"||dnt=="yes"),!doNotTrack){window.dataLayer=window.dataLayer||[];function gtag(){dataLayer.push(arguments)}gtag("js",new Date),gtag("config","G-E08ZXTFTTY")}</script><meta name=generator content="Hugo 0.152.2"></head><body><a href=#main-content class=skip-to-main>Skip to main content</a><header class=elegant-header role=banner><div class=header-inner><div class=site-identity><a href=https://queelius.github.io/ class=site-logo aria-label="metafunctor home">metafunctor</a>
<span class=site-tagline aria-label="Site tagline">Research · Coding</span></div><nav class=nav-primary role=navigation aria-label="Main navigation"><button class=mobile-menu-toggle aria-label="Toggle mobile menu" aria-expanded=false>
<span></span>
<span></span>
<span></span></button><ul role=list><li><a href=https://queelius.github.io/>Home</a></li><li><a href=https://queelius.github.io/projects/>Projects</a></li><li><a href=https://queelius.github.io/post/>Posts</a></li><li class=nav-dropdown><a href=# class=dropdown-toggle aria-haspopup=true aria-expanded=false>Work <i class="fas fa-chevron-down dropdown-icon"></i></a><ul class=dropdown-menu role=menu><li role=menuitem><a href=https://queelius.github.io/research/>Research</a></li><li role=menuitem><a href=https://queelius.github.io/papers/>Papers</a></li><li role=menuitem><a href=https://queelius.github.io/publications/>Publications</a></li><li role=menuitem><a href=https://queelius.github.io/writing/>Writing</a></li></ul></li><li><a href=https://queelius.github.io/media/>Media</a></li><li><a href=https://queelius.github.io/about/>About</a></li><li><a href=https://queelius.github.io/search/><i class="fas fa-search" aria-hidden=true></i><span class=sr-only>Search</span></a></li></ul></nav></div></header><style>.nav-dropdown{position:relative}.dropdown-toggle{display:flex;align-items:center;gap:.35rem;cursor:pointer}.dropdown-icon{font-size:.6rem;transition:transform .2s ease}.nav-dropdown.open .dropdown-icon{transform:rotate(180deg)}.dropdown-menu{position:absolute;top:calc(100% + .5rem);left:50%;transform:translateX(-50%);min-width:160px;background:#fff;border:1px solid rgba(0,0,0,.1);border-radius:8px;box-shadow:0 4px 20px rgba(0,0,0,.15);padding:.5rem 0;opacity:0;visibility:hidden;pointer-events:none;transition:opacity .15s ease;z-index:9999;list-style:none}.nav-dropdown.open .dropdown-menu{opacity:1!important;visibility:visible!important;pointer-events:auto!important;transform:translateX(-50%)translateY(0)scale(1)!important}.dropdown-menu::before{content:'';position:absolute;top:-6px;left:50%;transform:translateX(-50%);border-left:6px solid transparent;border-right:6px solid transparent;border-bottom:6px solid #fff;filter:drop-shadow(0 -1px 1px rgba(0,0,0,.1))}.dropdown-menu li{margin:0}.nav-dropdown .dropdown-menu a{display:block!important;padding:.6rem 1.25rem!important;color:#4a4a4a!important;font-size:.875rem!important;font-weight:500!important;text-decoration:none!important;transition:all .15s ease!important;white-space:nowrap!important;cursor:pointer!important;pointer-events:auto!important}.nav-dropdown .dropdown-menu a:hover{background:#f3f4f6!important;color:#4f46e5!important}.nav-dropdown .dropdown-menu a.active{color:#4f46e5!important}@media(max-width:768px){.dropdown-menu{position:static;transform:none;box-shadow:none;border:none;background:rgba(0,0,0,3%);border-radius:0;padding:0;max-height:0;overflow:hidden;opacity:1;visibility:visible;transition:max-height .2s ease}.dropdown-menu::before{display:none}.nav-dropdown.open .dropdown-menu{max-height:300px;padding:.5rem 0}.dropdown-menu a{padding:.5rem 1.5rem .5rem 2rem;font-size:.85rem}}</style><script>document.addEventListener("DOMContentLoaded",function(){const e=document.querySelectorAll(".nav-dropdown");e.forEach(t=>{const n=t.querySelector(".dropdown-toggle");n.addEventListener("click",function(n){n.preventDefault(),n.stopPropagation();const s=t.classList.contains("open");e.forEach(e=>e.classList.remove("open")),s||t.classList.add("open")})}),document.addEventListener("click",function(t){t.target.closest(".nav-dropdown")||e.forEach(e=>e.classList.remove("open"))}),document.addEventListener("keydown",function(t){t.key==="Escape"&&e.forEach(e=>e.classList.remove("open"))})})</script><nav aria-label=Breadcrumb class=breadcrumb-nav><ol class=breadcrumb itemscope itemtype=https://schema.org/BreadcrumbList><li itemprop=itemListElement itemscope itemtype=https://schema.org/ListItem><a itemprop=item href=https://queelius.github.io/><span itemprop=name>Home</span>
</a><meta itemprop=position content="1"></li><li itemprop=itemListElement itemscope itemtype=https://schema.org/ListItem><span class=breadcrumb-separator>/</span>
<a itemprop=item href=https://queelius.github.io/probsets/stat581/><span itemprop=name>STAT 581 - Statistical Methods - SIUe - Fall 2021</span>
</a><meta itemprop=position content="2"></li><li itemprop=itemListElement itemscope itemtype=https://schema.org/ListItem><span class=breadcrumb-separator>/</span>
<span itemprop=name aria-current=page>Statistical Methods - STAT 581 - Problem Set 6</span>
<meta itemprop=position content="3"></li></ol></nav><main id=main-content role=main aria-label="Main content"><div class=main-container><div class=single-post-layout><aside class=post-sidebar><aside class=toc-wrapper aria-label="Table of contents"><nav class=table-of-contents><h2 class=toc-title>Table of Contents</h2><div class=toc-content><nav id=TableOfContents><ul><li><a href=#preliminary-analysis>Preliminary analysis</a></li><li><a href=#a>(a)</a></li><li><a href=#b>(b)</a></li><li><a href=#c>(c)</a><ul><li><a href=#additive-model>Additive model</a></li><li><a href=#interaction-model>Interaction model</a></li><li><a href=#decision>Decision</a></li></ul></li><li><a href=#d>(d)</a></li></ul><ul><li><a href=#a-1>(a)</a></li><li><a href=#b-1>(b)</a><ul><li><a href=#i>(i)</a><ul><li><a href=#interpretation>Interpretation</a></li></ul></li><li><a href=#ii>(ii)</a><ul><li><a href=#interpetation>Interpetation</a></li></ul></li><li><a href=#iii>(iii)</a><ul><li><a href=#maximum-setting>Maximum setting</a></li><li><a href=#explanation>Explanation</a></li></ul></li></ul></li></ul><ul><li><a href=#problem-1-additional-analysis-of-the-additive-model>Problem 1: additional analysis of the additive model</a></li><li><a href=#problem-1-plots-of-interactions-that-were-deemed-insignificant>Problem 1: plots of interactions that were deemed insignificant</a></li></ul></nav></div></nav></aside><style>.toc-wrapper{position:sticky;top:80px;max-height:calc(100vh - 100px);overflow-y:auto;padding:var(--space-lg);background:var(--paper-dark);border:var(--border-width)solid var(--border-color);border-radius:var(--radius-lg);margin-bottom:var(--space-xl)}.toc-title{font-size:1rem;font-weight:600;color:var(--ink);margin:0 0 var(--space-md);text-transform:uppercase;letter-spacing:.05em;font-size:.875rem}.toc-content{font-size:.9rem}.toc-content ul{list-style:none;padding-left:0;margin:0}.toc-content>ul{border-left:2px solid var(--border-color);padding-left:var(--space-md)}.toc-content li{margin-bottom:var(--space-sm)}.toc-content a{color:var(--ink-light);text-decoration:none;transition:color var(--transition-fast);display:block;padding:var(--space-xs)0}.toc-content a:hover{color:var(--accent)}.toc-content ul ul{margin-top:var(--space-sm);padding-left:var(--space-md)}@media(max-width:1024px){.toc-wrapper{position:relative;top:0;max-height:none}}</style><script>document.addEventListener("DOMContentLoaded",function(){const e=document.querySelectorAll(".toc-content a"),n=Array.from(e).map(e=>{const t=e.getAttribute("href").substring(1);return document.getElementById(t)}).filter(e=>e!==null);function t(){let t="";n.forEach(e=>{const n=e.offsetTop,s=window.scrollY+100;s>=n&&(t=e.getAttribute("id"))}),e.forEach(e=>{e.classList.remove("active"),e.getAttribute("href")==="#"+t?(e.classList.add("active"),e.style.color="var(--accent)",e.style.fontWeight="600"):(e.style.color="",e.style.fontWeight="")})}window.addEventListener("scroll",t),t()})</script></aside><article class=single-post itemscope itemtype=https://schema.org/Article><header class=post-header><h1 class=post-title itemprop=headline>Statistical Methods - STAT 581 - Problem Set 6</h1><div class=post-meta><span class=post-date><i class="far fa-calendar" aria-hidden=true></i>
<time datetime=2021-12-01T00:00:00Z itemprop=datePublished>December 1, 2021
</time></span><span class=post-author itemprop=author itemscope itemtype=https://schema.org/Person><i class="far fa-user" aria-hidden=true></i>
<span itemprop=name>Alex Towell (lex@metafunctor.com)</span>
</span><span class=post-reading-time><i class="far fa-clock" aria-hidden=true></i>
9 min read
</span><span class=post-updated><i class="far fa-edit" aria-hidden=true></i>
Updated: <time datetime=2025-12-16T19:22:58-06:00 itemprop=dateModified>December 16, 2025</time></span></div><div class=tags role=list><a href=https://queelius.github.io/tags/statistics/ class=tag role=listitem>statistics</a>
<a href=https://queelius.github.io/tags/statistical-methods/ class=tag role=listitem>statistical-methods</a>
<a href=https://queelius.github.io/tags/r/ class=tag role=listitem>R</a>
<a href=https://queelius.github.io/tags/siue/ class=tag role=listitem>SIUe</a></div></header><div class=content itemprop=articleBody><h1 id=problem-1>Problem 1</h1><p>A soft drink bottler is interested in studying the effects on a filling process. A factorial experiment is run using three factors: percent carbonation (in %), operating pressure (in psi), and line speed (in bpm). The response variable is deviation from the target fill height. The experiment consists of [\(n=2\)]{.math .inline} runs for each of the [\(a b c = 12\)]{.math .inline} treatment combinations. The data is available on Blackboard as an Excel File.</p><h2 id=preliminary-analysis>Preliminary analysis</h2><p>The three-factor factorial experiment with [\(a=3\)]{.math .inline} levels of the <em>carbonation</em> factor (in %), denoted by [\(A\)]{.math .inline}, [\(b=2\)]{.math .inline} levels of the operating <em>pressure</em> (in psi), denoted by [\(B\)]{.math .inline}, and [\(c=2\)]{.math .inline} levels of the line <em>speed</em> (in bpm), denoted by [\(C\)]{.math .inline}. Each treatment combination has [\(n=2\)]{.math .inline} replicates for a total of [\(N=a b c n=24\)]{.math .inline} observations. The response variable [\(y\)]{.math .inline} is deviation from the target fill height.</p><p>We describe the observations in the three-factor factorial experiment by the fixed-effects interaction model where treatments are defined to be deviations from the overall mean, [\[Y_{i j k \ell} = \mu + \tau_i + \beta_j + \gamma_k + (\tau\!\beta)_{i j} + (\tau\!\gamma)_{i k} + (\beta\!\gamma)_{j k} + (\tau\!\beta\gamma)_{i j k} + \epsilon_{i j k \ell} \begin{cases} i = 1,\ldots,a=3\\ j = 1,\ldots,b=2\\ k = 1,\ldots,c=2\\ \ell = 1,\ldots,n=2\\ \end{cases}\]]{.math .display} where [\(\mu\)]{.math .inline} is the overall main effect, [\(\tau_i\)]{.math .inline} is the effect of the [\(i\)]{.math .inline}-th level of factor [\(A\)]{.math .inline}, [\(\beta_j\)]{.math .inline} is the effect of the [\(j\)]{.math .inline}-th level of factor [\(B\)]{.math .inline}, and [\(\gamma_k\)]{.math .inline} is the effect of the [\(k\)]{.math .inline}-th level of factor [\(C\)]{.math .inline}. The interaction effects may also be observed using the same labeling, e.g., [\((\tau\!\gamma)_{i k}\)]{.math .inline} is the interaction effect of the [\(i\)]{.math .inline}-th level of factor [\(A\)]{.math .inline} and the [\(k\)]{.math .inline}-th level of factor [\(C\)]{.math .inline}.</p><h2 id=a>(a)</h2><p>snugshade</p><pre><code>##             Df Sum Sq Mean Sq F value   Pr(&gt;F)    
## A            2 252.75  126.38 178.412 1.19e-09 ***
## B            1  45.37   45.37  64.059 3.74e-06 ***
## C            1  22.04   22.04  31.118  0.00012 ***
## A:B          2   5.25    2.63   3.706  0.05581 .  
## A:C          2   0.58    0.29   0.412  0.67149    
## B:C          1   1.04    1.04   1.471  0.24859    
## A:B:C        2   1.08    0.54   0.765  0.48687    
## Residuals   12   8.50    0.71                     
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
</code></pre><p>The tests for each of the main effects and a test of an interaction between carbon [\((A\)]{.math .inline}) and pressure [\((B\)]{.math .inline}) is given by the following table:</p><p>effects [\(F^*\)]{.math .inline} [\(p\)]{.math .inline}-value</p><hr><p>[\(A\)]{.math .inline} [\(178.4\)]{.math .inline} [\(.000\)]{.math .inline}
[\(B\)]{.math .inline} [\(64.1\)]{.math .inline} [\(.000\)]{.math .inline}
[\(C\)]{.math .inline} [\(31.1\)]{.math .inline} [\(.000\)]{.math .inline}
[\(A \times B\)]{.math .inline} [\(3.7\)]{.math .inline} [\(.056\)]{.math .inline}</p><h2 id=b>(b)</h2><p>If an interaction plot is parallel, or nearly so, then there is no need to include the interaction term.</p><p>In the [\(3\)]{.math .inline}-factor ANOVA model, a [\(3\)]{.math .inline}-factor interaction occurs when a [\(2\)]{.math .inline}-factor interaction depends on the level of the [\(3\)]{.math .inline}rd factor.</p><h2 id=c>(c)</h2><p>From the earlier results, we saw that factors [\(A\)]{.math .inline} (carbon), [\(B\)]{.math .inline} (pressure), and [\(C\)]{.math .inline} (speed) were statistically significant, but only the interaction between factor [\(A\)]{.math .inline} and [\(B\)]{.math .inline} (carbon and pressure) had any significance.</p><h3 id=additive-model>Additive model</h3><p>The additive model is given by [\[Y_{i j k \ell}^{(R)} = \mu + \tau_i + \beta_j + \gamma_k + \epsilon_{i j k \ell}.\]]{.math .display} Thus, [\[E(Y_{i j k}^{(R)}) = \mu + \tau_i + \beta_j + \gamma_k.\]]{.math .display}</p><p>We fit the additive model with:</p><p>snugshade
Highlighting
mod.R [=]{style=&ldquo;color: 0.56,0.35,0.01&rdquo;} [aov]{style=&ldquo;color: 0.13,0.29,0.53&rdquo;}(y [<strong>~</strong>]{style=&ldquo;color: 0.81,0.36,0.00&rdquo;} A[<strong>+</strong>]{style=&ldquo;color: 0.81,0.36,0.00&rdquo;}B[<strong>+</strong>]{style=&ldquo;color: 0.81,0.36,0.00&rdquo;}C)</p><p>We define the estimated means for the models with:</p><p>snugshade
Highlighting
fits.R [=]{style=&ldquo;color: 0.56,0.35,0.01&rdquo;} [predict]{style=&ldquo;color: 0.13,0.29,0.53&rdquo;}(mod.R)</p><p>The interaction plots for the additive where the left and right plots are respectively for factor [\(C\)]{.math .inline} at levels [\(1\)]{.math .inline} and [\(2\)]{.math .inline}.</p><p>snugshade
Highlighting
[par]{style=&ldquo;color: 0.13,0.29,0.53&rdquo;}([mfrow=]{style=&ldquo;color: 0.13,0.29,0.53&rdquo;}[c]{style=&ldquo;color: 0.13,0.29,0.53&rdquo;}([1]{style=&ldquo;color: 0.00,0.00,0.81&rdquo;},[2]{style=&ldquo;color: 0.00,0.00,0.81&rdquo;})) [for]{style=&ldquo;color: 0.13,0.29,0.53&rdquo;} (i [in]{style=&ldquo;color: 0.13,0.29,0.53&rdquo;} [1]{style=&ldquo;color: 0.00,0.00,0.81&rdquo;}[<strong>:</strong>]{style=&ldquo;color: 0.81,0.36,0.00&rdquo;}[nlevels]{style=&ldquo;color: 0.13,0.29,0.53&rdquo;}(C)) { [<strong>interaction.plot</strong>]{style=&ldquo;color: 0.13,0.29,0.53&rdquo;}(A[C[<strong>==</strong>]{style=&ldquo;color: 0.81,0.36,0.00&rdquo;}[levels]{style=&ldquo;color: 0.13,0.29,0.53&rdquo;}(C)[i]],B[C[<strong>==</strong>]{style=&ldquo;color: 0.81,0.36,0.00&rdquo;}[levels]{style=&ldquo;color: 0.13,0.29,0.53&rdquo;}(C)[i]], fits.R[C[<strong>==</strong>]{style=&ldquo;color: 0.81,0.36,0.00&rdquo;}[levels]{style=&ldquo;color: 0.13,0.29,0.53&rdquo;}(C)[i]], [xlab=]{style=&ldquo;color: 0.13,0.29,0.53&rdquo;}["A"]{style=&ldquo;color: 0.31,0.60,0.02&rdquo;}, [ylab=]{style=&ldquo;color: 0.13,0.29,0.53&rdquo;}["mean response"]{style=&ldquo;color: 0.31,0.60,0.02&rdquo;}, [trace.label=]{style=&ldquo;color: 0.13,0.29,0.53&rdquo;}["B"]{style=&ldquo;color: 0.31,0.60,0.02&rdquo;}) }</p><h3 id=interaction-model>Interaction model</h3><p>The model that includes interactions between factors [\(A\)]{.math .inline} (carbon) and [\(B\)]{.math .inline} (pressure) is given by [\[Y_{i j k \ell}^{(F)} = \mu + \tau_i + \beta_j + \gamma_k + (\tau\!\beta)_{i j} + \epsilon_{i j k \ell}.\]]{.math .display} Thus, [\[E(Y_{i j k}^{(F)}) = \mu + \tau_i + \beta_j + \gamma_k + (\tau\!\beta)_{i j}.\]]{.math .display}</p><p>We fit the interaction model with:</p><p>snugshade
Highlighting
mod.F [=]{style=&ldquo;color: 0.56,0.35,0.01&rdquo;} [aov]{style=&ldquo;color: 0.13,0.29,0.53&rdquo;}(y [<strong>~</strong>]{style=&ldquo;color: 0.81,0.36,0.00&rdquo;} A[<strong>+</strong>]{style=&ldquo;color: 0.81,0.36,0.00&rdquo;}B[<strong>+</strong>]{style=&ldquo;color: 0.81,0.36,0.00&rdquo;}C[<strong>+</strong>]{style=&ldquo;color: 0.81,0.36,0.00&rdquo;}A[<strong>:</strong>]{style=&ldquo;color: 0.81,0.36,0.00&rdquo;}B)</p><p>We define the estimated means for the models with:</p><p>snugshade
Highlighting
fits.F [=]{style=&ldquo;color: 0.56,0.35,0.01&rdquo;} [predict]{style=&ldquo;color: 0.13,0.29,0.53&rdquo;}(mod.F)</p><p>The interaction plots for the interaction model where the left and right plots are respectively for factor [\(C\)]{.math .inline} at levels [\(1\)]{.math .inline} and [\(2\)]{.math .inline}.</p><p>snugshade
Highlighting
[par]{style=&ldquo;color: 0.13,0.29,0.53&rdquo;}([mfrow=]{style=&ldquo;color: 0.13,0.29,0.53&rdquo;}[c]{style=&ldquo;color: 0.13,0.29,0.53&rdquo;}([1]{style=&ldquo;color: 0.00,0.00,0.81&rdquo;},[2]{style=&ldquo;color: 0.00,0.00,0.81&rdquo;})) [for]{style=&ldquo;color: 0.13,0.29,0.53&rdquo;} (i [in]{style=&ldquo;color: 0.13,0.29,0.53&rdquo;} [1]{style=&ldquo;color: 0.00,0.00,0.81&rdquo;}[<strong>:</strong>]{style=&ldquo;color: 0.81,0.36,0.00&rdquo;}[nlevels]{style=&ldquo;color: 0.13,0.29,0.53&rdquo;}(C)) { [<strong>interaction.plot</strong>]{style=&ldquo;color: 0.13,0.29,0.53&rdquo;}(A[C[<strong>==</strong>]{style=&ldquo;color: 0.81,0.36,0.00&rdquo;}[levels]{style=&ldquo;color: 0.13,0.29,0.53&rdquo;}(C)[i]],B[C[<strong>==</strong>]{style=&ldquo;color: 0.81,0.36,0.00&rdquo;}[levels]{style=&ldquo;color: 0.13,0.29,0.53&rdquo;}(C)[i]], fits.F[C[<strong>==</strong>]{style=&ldquo;color: 0.81,0.36,0.00&rdquo;}[levels]{style=&ldquo;color: 0.13,0.29,0.53&rdquo;}(C)[i]], [xlab=]{style=&ldquo;color: 0.13,0.29,0.53&rdquo;}["A"]{style=&ldquo;color: 0.31,0.60,0.02&rdquo;}, [ylab=]{style=&ldquo;color: 0.13,0.29,0.53&rdquo;}["mean response"]{style=&ldquo;color: 0.31,0.60,0.02&rdquo;}, [trace.label=]{style=&ldquo;color: 0.13,0.29,0.53&rdquo;}["B"]{style=&ldquo;color: 0.31,0.60,0.02&rdquo;}) }</p><h3 id=decision>Decision</h3><p>The interaction model fits show only a slight difference difference from the additive model. As a general rule, we prefer simpler models to complex models, and so we decide to leave out the interaction term.</p><h2 id=d>(d)</h2><p>snugshade
Highlighting
[par]{style=&ldquo;color: 0.13,0.29,0.53&rdquo;}([mfrow=]{style=&ldquo;color: 0.13,0.29,0.53&rdquo;}[c]{style=&ldquo;color: 0.13,0.29,0.53&rdquo;}([1]{style=&ldquo;color: 0.00,0.00,0.81&rdquo;},[3]{style=&ldquo;color: 0.00,0.00,0.81&rdquo;})) [plot]{style=&ldquo;color: 0.13,0.29,0.53&rdquo;}(fits.R [<strong>~</strong>]{style=&ldquo;color: 0.81,0.36,0.00&rdquo;} A) [plot]{style=&ldquo;color: 0.13,0.29,0.53&rdquo;}(fits.R [<strong>~</strong>]{style=&ldquo;color: 0.81,0.36,0.00&rdquo;} B) [plot]{style=&ldquo;color: 0.13,0.29,0.53&rdquo;}(fits.R [<strong>~</strong>]{style=&ldquo;color: 0.81,0.36,0.00&rdquo;} C)</p><p>We see that each factor has a positive effect on fill height. The factor with the biggest marginal effect on fill height is the percent of carbonation (factor [\(A\)]{.math .inline}).</p><h1 id=problem-2>Problem 2</h1><p>An engineer is interested in the effects of cutting speed, tool geometry, and cutting angle on the life (in hours) of a machine tool. Two levels of each factor are set, and [\(n=3\)]{.math .inline} runs of a [\(2^3\)]{.math .inline} design are completed. The data is available on Blackboard as an Excel File.</p><h2 id=a-1>(a)</h2><p>snugshade</p><pre><code>##             Df Sum Sq Mean Sq F value   Pr(&gt;F)    
## A            1    0.7     0.7   0.022 0.883680    
## B            1  770.7   770.7  25.547 0.000117 ***
## C            1  280.2   280.2   9.287 0.007679 ** 
## A:B          1   16.7    16.7   0.552 0.468078    
## A:C          1  468.2   468.2  15.519 0.001172 ** 
## B:C          1   48.2    48.2   1.597 0.224475    
## A:B:C        1   28.2    28.2   0.934 0.348282    
## Residuals   16  482.7    30.2                     
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
</code></pre><p>Factors [\(B\)]{.math .inline} and [\(C\)]{.math .inline} are important effects and the the interaction between [\(A\)]{.math .inline} and [\(C\)]{.math .inline} is also important. Thus, [\(A\)]{.math .inline}, [\(B\)]{.math .inline}, [\(C\)]{.math .inline}, and [\(A:C\)]{.math .inline} should be included in the model (we include [\(A\)]{.math .inline} because of the importance of [\(A:C\)]{.math .inline}).</p><p>effects [\(F^*\)]{.math .inline} [\(p\)]{.math .inline}-value</p><hr><p>[\(A\)]{.math .inline} [\(.022\)]{.math .inline} [\(.884\)]{.math .inline}
[\(B\)]{.math .inline} [\(25.547\)]{.math .inline} [\(.000\)]{.math .inline}
[\(C\)]{.math .inline} [\(9.287\)]{.math .inline} [\(.008\)]{.math .inline}
[\(A:C\)]{.math .inline} [\(15.519\)]{.math .inline} [\(.001\)]{.math .inline}</p><h2 id=b-1>(b)</h2><p>snugshade
Highlighting
reduced.mod [=]{style=&ldquo;color: 0.56,0.35,0.01&rdquo;} [aov]{style=&ldquo;color: 0.13,0.29,0.53&rdquo;}(y [<strong>~</strong>]{style=&ldquo;color: 0.81,0.36,0.00&rdquo;} A[<strong>+</strong>]{style=&ldquo;color: 0.81,0.36,0.00&rdquo;}B[<strong>+</strong>]{style=&ldquo;color: 0.81,0.36,0.00&rdquo;}C[<strong>+</strong>]{style=&ldquo;color: 0.81,0.36,0.00&rdquo;}A[<strong>:</strong>]{style=&ldquo;color: 0.81,0.36,0.00&rdquo;}C) [summary]{style=&ldquo;color: 0.13,0.29,0.53&rdquo;}(reduced.mod)</p><pre><code>##             Df Sum Sq Mean Sq F value   Pr(&gt;F)    
## A            1    0.7     0.7   0.022 0.883641    
## B            1  770.7   770.7  25.436 7.22e-05 ***
## C            1  280.2   280.2   9.247 0.006724 ** 
## A:C          1  468.2   468.2  15.452 0.000897 ***
## Residuals   19  575.7    30.3                     
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
</code></pre><h3 id=i>(i)</h3><p>snugshade
Highlighting
[<em># define the estimated means for the reduced model for plotting (randomness has</em>]{style=&ldquo;color: 0.56,0.35,0.01&rdquo;} [<em># been smoothed)</em>]{style=&ldquo;color: 0.56,0.35,0.01&rdquo;} fits.r [=]{style=&ldquo;color: 0.56,0.35,0.01&rdquo;} [predict]{style=&ldquo;color: 0.13,0.29,0.53&rdquo;}(reduced.mod) [<strong>interaction.plot</strong>]{style=&ldquo;color: 0.13,0.29,0.53&rdquo;}(A,C,fits.r,[ylab=]{style=&ldquo;color: 0.13,0.29,0.53&rdquo;}["y"]{style=&ldquo;color: 0.31,0.60,0.02&rdquo;})</p><h4 id=interpretation>Interpretation</h4><p>The experiment finds that when cutting speed (factor [\(A\)]{.math .inline}) is low, cutting angle has a positive effect on the life of a machine tool (response).</p><h3 id=ii>(ii)</h3><p>snugshade
Highlighting
[plot]{style=&ldquo;color: 0.13,0.29,0.53&rdquo;}(fits.r [<strong>~</strong>]{style=&ldquo;color: 0.81,0.36,0.00&rdquo;} B)</p><h4 id=interpetation>Interpetation</h4><p>Tool geometry (factor [\(B\)]{.math .inline}) has a positive effect on the life of a machine tool.</p><h3 id=iii>(iii)</h3><p>snugshade
Highlighting
A.C [=]{style=&ldquo;color: 0.56,0.35,0.01&rdquo;} [interaction]{style=&ldquo;color: 0.13,0.29,0.53&rdquo;}(A,C) [<strong>interaction.plot</strong>]{style=&ldquo;color: 0.13,0.29,0.53&rdquo;}(B,A.C, fits.r)</p><h4 id=maximum-setting>Maximum setting</h4><p>In this characterization experiment, we find that the best combination of factor levels is given by a low cutting speed ([\(A^-\)]{.math .inline}), a high tool geometry ([\(B^+\)]{.math .inline}), and a high cutting angle ([\(C^+\)]{.math .inline}).</p><h4 id=explanation>Explanation</h4><p>First, we observe that [\(A^-\)]{.math .inline} and [\(C^+\)]{.math .inline} has the best interaction effect (its corresponding line is above all of the others). Second, we see that [\(B\)]{.math .inline} has a positive effect, i.e., as we go from [\(B^-\)]{.math .inline} to [\(B^+\)]{.math .inline}, the response increases, and thus [\(B^+\)]{.math .inline} is better. Taking these two facts together, we see that the best combination in this experiment is [\((A^-,B^+,C^+)\)]{.math .inline}.</p><p>We may also just look at the highest point on the graph and see that [\((A^-,B^+,C^+)\)]{.math .inline} has the highest mean response. However, the interaction plot reveals more, particularly if in follow-up experiments where we use what we learned in this experiment to narrow down our search for an optimal combination (where optimality may be with respect to, say, mean response or minimal variability in the response).</p><h1 id=appendix>Appendix</h1><h2 id=problem-1-additional-analysis-of-the-additive-model>Problem 1: additional analysis of the additive model</h2><p>The model parameter estimates are given by:</p><p>snugshade
Highlighting
[<strong>dummy.coef</strong>]{style=&ldquo;color: 0.13,0.29,0.53&rdquo;}(mod.R)</p><pre><code>## Full coefficients are 
##                                             
## (Intercept):         3.125                  
## A:                      10         12     14
##                     -3.625     -0.625  4.250
## B:                      25         30       
##                     -1.375      1.375       
## C:                     200        250       
##                 -0.9583333  0.9583333
</code></pre><p>Thus, the estimated mean response [\(\hat{Y}_{i j k}^{(R)}\)]{.math .inline} is given by [\[\begin{aligned} \hat{Y}_{i j k}^{(R)} = 3.125 - &amp;I(i=1) 3.625 - I(i=2) 6.25 + I(i=3) 4.250\\ - &amp;I(j=1) 1.375 + I(j=2) 1.375\\ - &amp;I(k=1) 9.58\bar{3} + I(k=2) 9.58\bar{3}. \end{aligned}\]]{.math .display}</p><p>In R code, this may be brute-force implemented as:</p><p>snugshade
Highlighting
yhat.R [=]{style=&ldquo;color: 0.56,0.35,0.01&rdquo;} [function]{style=&ldquo;color: 0.13,0.29,0.53&rdquo;}(i,j,k) { y [=]{style=&ldquo;color: 0.56,0.35,0.01&rdquo;} [3.125]{style=&ldquo;color: 0.00,0.00,0.81&rdquo;} [if]{style=&ldquo;color: 0.13,0.29,0.53&rdquo;} (i [<strong>==</strong>]{style=&ldquo;color: 0.81,0.36,0.00&rdquo;} [1]{style=&ldquo;color: 0.00,0.00,0.81&rdquo;}) y [=]{style=&ldquo;color: 0.56,0.35,0.01&rdquo;} y [<strong>-</strong>]{style=&ldquo;color: 0.81,0.36,0.00&rdquo;} [3.625]{style=&ldquo;color: 0.00,0.00,0.81&rdquo;}; [if]{style=&ldquo;color: 0.13,0.29,0.53&rdquo;} (i [<strong>==</strong>]{style=&ldquo;color: 0.81,0.36,0.00&rdquo;} [2]{style=&ldquo;color: 0.00,0.00,0.81&rdquo;}) y [=]{style=&ldquo;color: 0.56,0.35,0.01&rdquo;} y [<strong>-</strong>]{style=&ldquo;color: 0.81,0.36,0.00&rdquo;} .[625]{style=&ldquo;color: 0.00,0.00,0.81&rdquo;}; [if]{style=&ldquo;color: 0.13,0.29,0.53&rdquo;} (i [<strong>==</strong>]{style=&ldquo;color: 0.81,0.36,0.00&rdquo;} [3]{style=&ldquo;color: 0.00,0.00,0.81&rdquo;}) y [=]{style=&ldquo;color: 0.56,0.35,0.01&rdquo;} y [<strong>+</strong>]{style=&ldquo;color: 0.81,0.36,0.00&rdquo;} [4.25]{style=&ldquo;color: 0.00,0.00,0.81&rdquo;} [if]{style=&ldquo;color: 0.13,0.29,0.53&rdquo;} (j [<strong>==</strong>]{style=&ldquo;color: 0.81,0.36,0.00&rdquo;} [1]{style=&ldquo;color: 0.00,0.00,0.81&rdquo;}) y [=]{style=&ldquo;color: 0.56,0.35,0.01&rdquo;} y [<strong>-</strong>]{style=&ldquo;color: 0.81,0.36,0.00&rdquo;} [1.375]{style=&ldquo;color: 0.00,0.00,0.81&rdquo;}; [if]{style=&ldquo;color: 0.13,0.29,0.53&rdquo;} (j [<strong>==</strong>]{style=&ldquo;color: 0.81,0.36,0.00&rdquo;} [2]{style=&ldquo;color: 0.00,0.00,0.81&rdquo;}) y [=]{style=&ldquo;color: 0.56,0.35,0.01&rdquo;} y [<strong>+</strong>]{style=&ldquo;color: 0.81,0.36,0.00&rdquo;} [1.375]{style=&ldquo;color: 0.00,0.00,0.81&rdquo;} [if]{style=&ldquo;color: 0.13,0.29,0.53&rdquo;} (k [<strong>==</strong>]{style=&ldquo;color: 0.81,0.36,0.00&rdquo;} [1]{style=&ldquo;color: 0.00,0.00,0.81&rdquo;}) y [=]{style=&ldquo;color: 0.56,0.35,0.01&rdquo;} y [<strong>-</strong>]{style=&ldquo;color: 0.81,0.36,0.00&rdquo;} .[95833333]{style=&ldquo;color: 0.00,0.00,0.81&rdquo;}; [if]{style=&ldquo;color: 0.13,0.29,0.53&rdquo;} (k [<strong>==</strong>]{style=&ldquo;color: 0.81,0.36,0.00&rdquo;} [2]{style=&ldquo;color: 0.00,0.00,0.81&rdquo;}) y [=]{style=&ldquo;color: 0.56,0.35,0.01&rdquo;} y [<strong>+</strong>]{style=&ldquo;color: 0.81,0.36,0.00&rdquo;} .[95833333]{style=&ldquo;color: 0.00,0.00,0.81&rdquo;} y }</p><p>We print out all of the estimates of the mean response with:</p><p>snugshade
Highlighting
[for]{style=&ldquo;color: 0.13,0.29,0.53&rdquo;} (i [in]{style=&ldquo;color: 0.13,0.29,0.53&rdquo;} [1]{style=&ldquo;color: 0.00,0.00,0.81&rdquo;}[<strong>:</strong>]{style=&ldquo;color: 0.81,0.36,0.00&rdquo;}[3]{style=&ldquo;color: 0.00,0.00,0.81&rdquo;}) [for]{style=&ldquo;color: 0.13,0.29,0.53&rdquo;} (j [in]{style=&ldquo;color: 0.13,0.29,0.53&rdquo;} [1]{style=&ldquo;color: 0.00,0.00,0.81&rdquo;}[<strong>:</strong>]{style=&ldquo;color: 0.81,0.36,0.00&rdquo;}[2]{style=&ldquo;color: 0.00,0.00,0.81&rdquo;}) [for]{style=&ldquo;color: 0.13,0.29,0.53&rdquo;} (k [in]{style=&ldquo;color: 0.13,0.29,0.53&rdquo;} [1]{style=&ldquo;color: 0.00,0.00,0.81&rdquo;}[<strong>:</strong>]{style=&ldquo;color: 0.81,0.36,0.00&rdquo;}[2]{style=&ldquo;color: 0.00,0.00,0.81&rdquo;}) [cat]{style=&ldquo;color: 0.13,0.29,0.53&rdquo;}(["Y("]{style=&ldquo;color: 0.31,0.60,0.02&rdquo;},[c]{style=&ldquo;color: 0.13,0.29,0.53&rdquo;}(i,j,k),[") = "]{style=&ldquo;color: 0.31,0.60,0.02&rdquo;},[<strong>yhat.R</strong>]{style=&ldquo;color: 0.13,0.29,0.53&rdquo;}(i,j,k),["]{style=&ldquo;color: 0.31,0.60,0.02&rdquo;}[<strong>\n</strong>]{style=&ldquo;color: 0.81,0.36,0.00&rdquo;}["]{style=&ldquo;color: 0.31,0.60,0.02&rdquo;})</p><pre><code>## Y( 1 1 1 ) =  -2.833333 
## Y( 1 1 2 ) =  -0.9166667 
## Y( 1 2 1 ) =  -0.08333333 
## Y( 1 2 2 ) =  1.833333 
## Y( 2 1 1 ) =  0.1666667 
## Y( 2 1 2 ) =  2.083333 
## Y( 2 2 1 ) =  2.916667 
## Y( 2 2 2 ) =  4.833333 
## Y( 3 1 1 ) =  5.041667 
## Y( 3 1 2 ) =  6.958333 
## Y( 3 2 1 ) =  7.791667 
## Y( 3 2 2 ) =  9.708333
</code></pre><h2 id=problem-1-plots-of-interactions-that-were-deemed-insignificant>Problem 1: plots of interactions that were deemed insignificant</h2><p>The data showed no statistically significant interaction effects between factors [\(A\)]{.math .inline} and [\(B\)]{.math .inline} and between factors [\(B\)]{.math .inline} and [\(C\)]{.math .inline}. Thus, their interaction plots are, as expected, parallel:</p><p>snugshade
Highlighting
[par]{style=&ldquo;color: 0.13,0.29,0.53&rdquo;}([mfrow=]{style=&ldquo;color: 0.13,0.29,0.53&rdquo;}[c]{style=&ldquo;color: 0.13,0.29,0.53&rdquo;}([1]{style=&ldquo;color: 0.00,0.00,0.81&rdquo;},[2]{style=&ldquo;color: 0.00,0.00,0.81&rdquo;})) [<strong>interaction.plot</strong>]{style=&ldquo;color: 0.13,0.29,0.53&rdquo;}(A,B,fits.r,[ylab=]{style=&ldquo;color: 0.13,0.29,0.53&rdquo;}["y"]{style=&ldquo;color: 0.31,0.60,0.02&rdquo;}) [<strong>interaction.plot</strong>]{style=&ldquo;color: 0.13,0.29,0.53&rdquo;}(B,C,fits.r,[ylab=]{style=&ldquo;color: 0.13,0.29,0.53&rdquo;}["y"]{style=&ldquo;color: 0.31,0.60,0.02&rdquo;})</p></div><nav class=post-navigation><a href=/probsets/stat581/stat581-hw7/ class=nav-prev><span class=nav-label>← Previous</span>
<span class=nav-title>Statistical Methods - STAT 581 - Problem Set 7</span>
</a><a href=/probsets/stat581/stat581-hw5/ class=nav-next><span class=nav-label>Next →</span>
<span class=nav-title>Statistical Methods - STAT 581 - Problem Set 5</span></a></nav></article></div></div></main><footer class=elegant-footer role=contentinfo aria-label="Site footer"><div class=footer-content><div class=footer-about><h3>metafunctor</h3><p>Research engineer and computer scientist specializing in machine learning, statistical computing, and open source software development.</p><nav aria-label="Social media links" class=social-links><a href=https://twitter.com/queelius target=_blank rel="noopener noreferrer" aria-label=Twitter><i class="fab fa-twitter" aria-hidden=true></i>
</a><a href=https://github.com/queelius target=_blank rel="noopener noreferrer" aria-label=GitHub><i class="fab fa-github" aria-hidden=true></i>
</a><a href=https://www.linkedin.com/in/alexander-towell-487015151/ target=_blank rel="noopener noreferrer" aria-label=LinkedIn><i class="fab fa-linkedin" aria-hidden=true></i>
</a><a href=/index.xml target=_blank rel="noopener noreferrer" aria-label=RSS><i class="fas fa-rss" aria-hidden=true></i>
</a><a href=mailto:lex@metafunctor.com target=_blank rel="noopener noreferrer" aria-label=Email><i class="fas fa-envelope" aria-hidden=true></i>
</a><a href=https://keybase.io/queelius target=_blank rel="noopener noreferrer" aria-label=Keybase><i class="fab fa-keybase" aria-hidden=true></i>
</a><a href=https://www.youtube.com/@queelius target=_blank rel="noopener noreferrer" aria-label=YouTube><i class="fab fa-youtube" aria-hidden=true></i>
</a><a href="https://scholar.google.com/citations?view_op=list_works&amp;hl=en&amp;user=E9mnFzQAAAAJ" target=_blank rel="noopener noreferrer" aria-label="Google Scholar"><i class="fas fa-graduation-cap" aria-hidden=true></i>
</a><a href="https://orcid.org/my-orcid?orcid=0000-0001-6443-9897" target=_blank rel="noopener noreferrer" aria-label=ORCID><i class="fab fa-orcid" aria-hidden=true></i></a></nav></div><nav class=footer-section aria-labelledby=footer-research><h4 id=footer-research>Research</h4><div class=footer-links><a href=https://queelius.github.io/publications/>Publications</a>
<a href=https://queelius.github.io/research/>Research Areas</a>
<a href=https://queelius.github.io/featured/>Featured Work</a></div></nav><nav class=footer-section aria-labelledby=footer-development><h4 id=footer-development>Development</h4><div class=footer-links><a href=https://github.com/queelius target=_blank rel="noopener noreferrer">GitHub</a>
<a href=https://pypi.org/user/queelius/ target=_blank rel="noopener noreferrer">PyPI</a>
<a href=https://queelius.github.io/projects/>Projects</a></div></nav><nav class=footer-section aria-labelledby=footer-connect><h4 id=footer-connect>Connect</h4><div class=footer-links><a href=https://queelius.github.io/about/>About</a>
<a href=mailto:lex@metafunctor.com>Contact</a>
<a href=https://queelius.github.io/archive/>Archive</a>
<a href=https://queelius.github.io/sitemap.xml>Sitemap</a>
<a href=https://queelius.github.io/index.xml type=application/rss+xml>RSS Feed</a></div></nav></div><div class=footer-bottom><p class=copyright>© 2025 Alex Towell. All rights reserved.</p><p class=accessibility-note><a href=#main-content>Back to top</a></p></div></footer><script src=/js/performance-optimizations.js defer></script><script src=/js/performance-enhancements.js defer></script><script src=/js/mobile-menu.js defer></script><script src=/js/modern-interactions.js defer></script><script src=/js/search.js defer></script><script src=/js/reading-progress.js defer></script><script src=/js/copy-code.js defer></script><script src=/js/anchor-links.js defer></script><button id=back-to-top aria-label="Back to top" style="display:none;position:fixed;bottom:30px;right:30px;z-index:1000;background:linear-gradient(135deg,#667eea 0%,#764ba2 100%);color:#fff;border:none;border-radius:50%;width:50px;height:50px;cursor:pointer;box-shadow:0 4px 15px rgba(102,126,234,.4);transition:all .3s ease">
<i class="fas fa-arrow-up"></i>
</button>
<script>const backToTop=document.getElementById("back-to-top");window.addEventListener("scroll",()=>{window.scrollY>300?backToTop.style.display="block":backToTop.style.display="none"}),backToTop.addEventListener("click",()=>{window.scrollTo({top:0,behavior:"smooth"})})</script><script data-goatcounter=https://queelius.goatcounter.com/count async src=//gc.zgo.at/count.js></script></body></html>