<!doctype html><html lang=en-us prefix="og: https://ogp.me/ns#"><head><meta charset=utf-8><meta name=viewport content="width=device-width,initial-scale=1,shrink-to-fit=no"><meta http-equiv=X-UA-Compatible content="IE=edge"><title>Regression Analysis - STAT 482 - Problem Set 2 | metafunctor</title><meta name=title content="Regression Analysis - STAT 482 - Problem Set 2 | metafunctor"><meta name=description content="Refer to the data from Exercise 1.27 A person&rsquo;s muscle mass is expected to decrease with age. muscle mass (in muscle mass units)."><meta name=keywords content="machine learning,statistical computing,open source,research,computer science,artificial intelligence"><meta name=author content="Alex Towell"><meta name=robots content="index, follow, max-image-preview:large, max-snippet:-1, max-video-preview:-1"><link rel=canonical href=https://metafunctor.com/probsets/stat482/stat482-hw2/><link rel=alternate hreflang=en href=https://metafunctor.com/probsets/stat482/stat482-hw2/><link rel=alternate hreflang=x-default href=https://metafunctor.com/probsets/stat482/stat482-hw2/><style>*,*::before,*::after{box-sizing:border-box;margin:0;padding:0}html{font-size:16px;-webkit-font-smoothing:antialiased;-moz-osx-font-smoothing:grayscale}body{margin:0;font-family:-apple-system,BlinkMacSystemFont,segoe ui,roboto,sans-serif;font-size:17px;line-height:1.7;color:#2c2c2c;background:#fff}.elegant-header{position:sticky;top:0;z-index:1000;background:rgba(254,254,254,.95);backdrop-filter:blur(10px);border-bottom:1px solid rgba(0,0,0,8%)}.header-inner{max-width:1400px;margin:0 auto;padding:1rem 2rem;display:flex;justify-content:space-between;align-items:center}.site-logo{font-size:1.5rem;font-weight:700;color:#2c2c2c;text-decoration:none}.nav-primary ul{display:flex;gap:2rem;list-style:none}.nav-primary a{font-size:.9rem;font-weight:500;color:#4a4a4a;text-decoration:none}.hero-elegant{padding:5rem 2rem;text-align:center;background:linear-gradient(180deg,#fafafa 0%,#ffffff 100%)}.hero-title{font-size:3.5rem;font-weight:700;margin-bottom:1rem;background:linear-gradient(135deg,#2c2c2c 0%,#003d7a 100%);-webkit-background-clip:text;-webkit-text-fill-color:transparent;background-clip:text}.hero-subtitle{font-size:1.25rem;color:#4a4a4a;max-width:600px;margin:0 auto 3rem}.skip-to-main{position:absolute;top:-100px;left:0;background:#0050a0;color:#fff;padding:.5rem 1rem;text-decoration:none;font-weight:600;z-index:10000}.skip-to-main:focus{top:0}.preload *{transition:none!important}</style><link rel=preconnect href=https://fonts.googleapis.com><link rel=preconnect href=https://fonts.gstatic.com crossorigin><link rel=preconnect href=https://cdnjs.cloudflare.com crossorigin><link rel=dns-prefetch href=https://www.google-analytics.com><link rel=dns-prefetch href=https://cdn.jsdelivr.net><meta property="og:type" content="article"><meta property="og:url" content="https://metafunctor.com/probsets/stat482/stat482-hw2/"><meta property="og:title" content="Regression Analysis - STAT 482 - Problem Set 2"><meta property="og:description" content="Refer to the data from Exercise 1.27 A person&rsquo;s muscle mass is expected to decrease with age. muscle mass (in muscle mass units)."><meta property="og:image" content="https://metafunctor.com/images/og-image.jpg"><meta property="og:image:width" content="1200"><meta property="og:image:height" content="630"><meta property="og:site_name" content="metafunctor"><meta property="og:locale" content="en_US"><meta property="article:author" content="Alex Towell"><meta property="article:published_time" content="2021-07-01T00:00:00Z"><meta property="article:modified_time" content="2026-04-26T17:47:31-05:00"><meta property="article:tag" content="statistics"><meta property="article:tag" content="regression-analysis"><meta property="article:tag" content="R"><meta property="article:tag" content="SIUe"><meta name=twitter:card content="summary_large_image"><meta name=twitter:url content="https://metafunctor.com/probsets/stat482/stat482-hw2/"><meta name=twitter:title content="Regression Analysis - STAT 482 - Problem Set 2"><meta name=twitter:description content="Refer to the data from Exercise 1.27 A person&rsquo;s muscle mass is expected to decrease with age. muscle mass (in muscle mass units)."><meta name=twitter:image content="https://metafunctor.com/images/og-image.jpg"><meta name=twitter:site content="@queelius"><meta name=twitter:creator content="@queelius"><script type=application/ld+json>{"@context":"https://schema.org","@graph":[{"@type":"Article","@id":"https:\/\/metafunctor.com\/probsets\/stat482\/stat482-hw2\/#primaryContent","headline":"Regression Analysis - STAT 482 - Problem Set 2","description":"Refer to the data from Exercise 1.27 A person\u0026rsquo;s muscle mass is expected to decrease with age. muscle mass (in muscle mass units).","url":"https:\/\/metafunctor.com\/probsets\/stat482\/stat482-hw2\/","inLanguage":"en-US","datePublished":"2021-07-01T00:00:00Z","dateModified":"2026-04-26T17:47:31-05:00","wordCount":963,"timeRequired":"PT5M","author":{"@type":"Person","@id":"https:\/\/metafunctor.com\/#author","name":"Alex Towell","url":"https:\/\/metafunctor.com\/about/"},"publisher":{"@type":"Organization","@id":"https:\/\/metafunctor.com\/#organization","name":"metafunctor","url":"https:\/\/metafunctor.com\/","logo":{"@type":"ImageObject","url":"https:\/\/metafunctor.com\/images\/og-image.jpg"}},"keywords":["statistics","regression-analysis","R","SIUe"]},{"@type":"BreadcrumbList","@id":"https:\/\/metafunctor.com\/probsets\/stat482\/stat482-hw2\/#breadcrumb","itemListElement":[{"@type":"ListItem","position":1,"name":"Home","item":"https:\/\/metafunctor.com\/"},{"@type":"ListItem","position":2,"name":"STAT 482 - Regression Analysis - SIUe - Fall 2021","item":"https:\/\/metafunctor.com\/probsets\/stat482\/"},{"@type":"ListItem","position":3,"name":"Regression Analysis - STAT 482 - Problem Set 2","item":"https:\/\/metafunctor.com\/probsets\/stat482\/stat482-hw2\/"}]}]}</script><link rel=preload href="https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700;800&family=Lora:ital,wght@0,400;0,600;0,700;1,400&family=JetBrains+Mono:wght@400;500&display=swap" as=style><link href="https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700;800&family=Lora:ital,wght@0,400;0,600;0,700;1,400&family=JetBrains+Mono:wght@400;500&display=swap" rel=stylesheet media=print onload='this.media="all"'><noscript><link href="https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700;800&family=Lora:ital,wght@0,400;0,600;0,700;1,400&family=JetBrains+Mono:wght@400;500&display=swap" rel=stylesheet></noscript><link rel=stylesheet href=../../../css/refined-elegant.css><link rel=stylesheet href=../../../css/micro-interactions.css><link rel=stylesheet href=../../../css/elegant.css media=print onload='this.media="all"'><link rel=stylesheet href=../../../css/custom.css><link rel=stylesheet href=../../../css/beautify.css><link rel=stylesheet href=https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css crossorigin=anonymous><link rel=stylesheet href=https://cdn.jsdelivr.net/npm/katex@0.16.8/dist/katex.min.css><script defer src=https://cdn.jsdelivr.net/npm/katex@0.16.8/dist/katex.min.js></script><script defer src=https://cdn.jsdelivr.net/npm/katex@0.16.8/dist/contrib/auto-render.min.js></script><script>document.addEventListener("DOMContentLoaded",function(){renderMathInElement(document.body,{delimiters:[{left:"$$",right:"$$",display:!0},{left:"\\[",right:"\\]",display:!0},{left:"$",right:"$",display:!1},{left:"\\(",right:"\\)",display:!1}]})})</script><script defer src=https://cdn.jsdelivr.net/npm/fuse.js@7.0.0/dist/fuse.min.js></script><script async src="https://www.googletagmanager.com/gtag/js?id=G-E08ZXTFTTY"></script><script>var doNotTrack=!1,dnt=navigator.doNotTrack||window.doNotTrack||navigator.msDoNotTrack,doNotTrack=dnt=="1"||dnt=="yes";if(!doNotTrack){window.dataLayer=window.dataLayer||[];function gtag(){dataLayer.push(arguments)}gtag("js",new Date),gtag("config","G-E08ZXTFTTY")}</script><meta name=generator content="Hugo 0.163.0"></head><body><a href=#main-content class=skip-to-main>Skip to main content</a><header class=elegant-header role=banner><div class=header-inner><div class=site-identity><a href=https://metafunctor.com/ class=site-logo aria-label="metafunctor home">metafunctor</a>
<span class=site-tagline aria-label="Site tagline">Research · Coding</span></div><nav class=nav-primary role=navigation aria-label="Main navigation"><button class=mobile-menu-toggle aria-label="Toggle mobile menu" aria-expanded=false>
<span></span>
<span></span>
<span></span></button><ul role=list><li><a href=https://metafunctor.com/>Home</a></li><li><a href=https://metafunctor.com/post/>Posts</a></li><li><a href=https://metafunctor.com/series/>Series</a></li><li class=nav-dropdown><a href=# class=dropdown-toggle aria-haspopup=true aria-expanded=false>Academic <i class="fas fa-chevron-down dropdown-icon"></i></a><ul class=dropdown-menu role=menu><li role=menuitem><a href=https://metafunctor.com/papers/>Papers</a></li><li role=menuitem><a href=https://metafunctor.com/publications/>Publications</a></li><li role=menuitem><a href=https://metafunctor.com/research/>Research</a></li></ul></li><li class=nav-dropdown><a href=# class=dropdown-toggle aria-haspopup=true aria-expanded=false>Creative <i class="fas fa-chevron-down dropdown-icon"></i></a><ul class=dropdown-menu role=menu><li role=menuitem><a href=https://metafunctor.com/writing/>Writing</a></li><li role=menuitem><a href=https://metafunctor.com/media/>Media</a></li></ul></li><li><a href=https://metafunctor.com/projects/>Projects</a></li><li><a href=https://metafunctor.com/about/>About</a></li><li><a href=https://metafunctor.com/search/><i class="fas fa-search" aria-hidden=true></i><span class=sr-only>Search</span></a></li></ul></nav></div></header><style>.nav-dropdown{position:relative}.dropdown-toggle{display:flex;align-items:center;gap:.35rem;cursor:pointer}.dropdown-icon{font-size:.6rem;transition:transform .2s ease}.nav-dropdown.open .dropdown-icon{transform:rotate(180deg)}.dropdown-menu{position:absolute;top:calc(100% + .5rem);left:50%;transform:translateX(-50%);min-width:160px;background:#fff;border:1px solid rgba(0,0,0,.1);border-radius:8px;box-shadow:0 4px 20px rgba(0,0,0,.15);padding:.5rem 0;opacity:0;visibility:hidden;pointer-events:none;transition:opacity .15s ease;z-index:9999;list-style:none}.nav-dropdown.open .dropdown-menu{opacity:1!important;visibility:visible!important;pointer-events:auto!important;transform:translateX(-50%)translateY(0)scale(1)!important}.dropdown-menu::before{content:'';position:absolute;top:-6px;left:50%;transform:translateX(-50%);border-left:6px solid transparent;border-right:6px solid transparent;border-bottom:6px solid #fff;filter:drop-shadow(0 -1px 1px rgba(0,0,0,.1))}.dropdown-menu li{margin:0}.nav-dropdown .dropdown-menu a{display:block!important;padding:.6rem 1.25rem!important;color:#4a4a4a!important;font-size:.875rem!important;font-weight:500!important;text-decoration:none!important;transition:all .15s ease!important;white-space:nowrap!important;cursor:pointer!important;pointer-events:auto!important}.nav-dropdown .dropdown-menu a:hover{background:#f3f4f6!important;color:#4f46e5!important}.nav-dropdown .dropdown-menu a.active{color:#4f46e5!important}@media(max-width:768px){.dropdown-menu{position:static;transform:none;box-shadow:none;border:none;background:rgba(0,0,0,3%);border-radius:0;padding:0;max-height:0;overflow:hidden;opacity:1;visibility:visible;transition:max-height .2s ease}.dropdown-menu::before{display:none}.nav-dropdown.open .dropdown-menu{max-height:300px;padding:.5rem 0}.dropdown-menu a{padding:.5rem 1.5rem .5rem 2rem;font-size:.85rem}}</style><script>document.addEventListener("DOMContentLoaded",function(){const e=document.querySelectorAll(".nav-dropdown");e.forEach(t=>{const n=t.querySelector(".dropdown-toggle");n.addEventListener("click",function(n){n.preventDefault(),n.stopPropagation();const s=t.classList.contains("open");e.forEach(e=>e.classList.remove("open")),s||t.classList.add("open")})}),document.addEventListener("click",function(t){t.target.closest(".nav-dropdown")||e.forEach(e=>e.classList.remove("open"))}),document.addEventListener("keydown",function(t){t.key==="Escape"&&e.forEach(e=>e.classList.remove("open"))})})</script><nav aria-label=Breadcrumb class=breadcrumb-nav><ol class=breadcrumb itemscope itemtype=https://schema.org/BreadcrumbList><li itemprop=itemListElement itemscope itemtype=https://schema.org/ListItem><a itemprop=item href=https://metafunctor.com/><span itemprop=name>Home</span>
</a><meta itemprop=position content="1"></li><li itemprop=itemListElement itemscope itemtype=https://schema.org/ListItem><span class=breadcrumb-separator>/</span>
<a itemprop=item href=https://metafunctor.com/probsets/stat482/><span itemprop=name>STAT 482 - Regression Analysis - SIUe - Fall 2021</span>
</a><meta itemprop=position content="2"></li><li itemprop=itemListElement itemscope itemtype=https://schema.org/ListItem><span class=breadcrumb-separator>/</span>
<span itemprop=name aria-current=page>Regression Analysis - STAT 482 - Problem Set 2</span>
<meta itemprop=position content="3"></li></ol></nav><main id=main-content role=main aria-label="Main content"><div class=main-container><div class=single-post-layout><aside class=post-sidebar><aside class=toc-wrapper aria-label="Table of contents"><nav class=table-of-contents><h2 class=toc-title>Table of Contents</h2><div class=toc-content><nav id=TableOfContents><ul><li><ul><li><ul><li><a href=#alex-towell-atowellsiue.edu>Alex Towell (atowell@siue.edu)</a></li></ul></li></ul></li></ul><ul><li><a href=#alterantive-formulation>Alterantive formulation</a></li></ul></nav></div></nav></aside><style>.toc-wrapper{position:sticky;top:80px;max-height:calc(100vh - 100px);overflow-y:auto;padding:var(--space-lg);background:var(--paper-dark);border:var(--border-width)solid var(--border-color);border-radius:var(--radius-lg);margin-bottom:var(--space-xl)}.toc-title{font-size:1rem;font-weight:600;color:var(--ink);margin:0 0 var(--space-md);text-transform:uppercase;letter-spacing:.05em;font-size:.875rem}.toc-content{font-size:.9rem}.toc-content ul{list-style:none;padding-left:0;margin:0}.toc-content>ul{border-left:2px solid var(--border-color);padding-left:var(--space-md)}.toc-content li{margin-bottom:var(--space-sm)}.toc-content a{color:var(--ink-light);text-decoration:none;transition:color var(--transition-fast);display:block;padding:var(--space-xs)0}.toc-content a:hover{color:var(--accent)}.toc-content ul ul{margin-top:var(--space-sm);padding-left:var(--space-md)}@media(max-width:1024px){.toc-wrapper{position:relative;top:0;max-height:none}}</style><script>document.addEventListener("DOMContentLoaded",function(){const e=document.querySelectorAll(".toc-content a"),n=Array.from(e).map(e=>{const t=e.getAttribute("href").substring(1);return document.getElementById(t)}).filter(e=>e!==null);function t(){let t="";n.forEach(e=>{const n=e.offsetTop,s=window.scrollY+100;s>=n&&(t=e.getAttribute("id"))}),e.forEach(e=>{e.classList.remove("active"),e.getAttribute("href")==="#"+t?(e.classList.add("active"),e.style.color="var(--accent)",e.style.fontWeight="600"):(e.style.color="",e.style.fontWeight="")})}window.addEventListener("scroll",t),t()})</script></aside><article class=single-post itemscope itemtype=https://schema.org/Article><header class=post-header><h1 class=post-title itemprop=headline>Regression Analysis - STAT 482 - Problem Set 2</h1><div class=post-meta><span class=post-date><i class="far fa-calendar" aria-hidden=true></i>
<time datetime=2021-07-01T00:00:00Z itemprop=datePublished>July 1, 2021
</time></span><span class=post-author itemprop=author itemscope itemtype=https://schema.org/Person><i class="far fa-user" aria-hidden=true></i>
<span itemprop=name>Alex Towell (lex@metafunctor.com)</span>
</span><span class=post-reading-time><i class="far fa-clock" aria-hidden=true></i>
5 min read
</span><span class=post-updated><i class="far fa-edit" aria-hidden=true></i>
Updated: <time datetime=2026-04-26T17:47:31-05:00 itemprop=dateModified>April 26, 2026</time></span></div><div class=tags role=list><a href=https://metafunctor.com/tags/statistics/ class=tag role=listitem>statistics</a>
<a href=https://metafunctor.com/tags/regression-analysis/ class=tag role=listitem>regression-analysis</a>
<a href=https://metafunctor.com/tags/r/ class=tag role=listitem>R</a>
<a href=https://metafunctor.com/tags/siue/ class=tag role=listitem>SIUe</a></div></header><div class=content itemprop=articleBody><p>row</p><h4 id=alex-towell-atowellsiue.edu class=author>Alex Towell (<a href=mailto:atowell@siue.edu>atowell@siue.edu</a>)</h4><p>Refer to the data from Exercise 1.27</p><p>A person&rsquo;s muscle mass is expected to decrease with age. To explore this relationship in women, a nutritionist randomly selected [\(15\)]{.math .inline} women for each [\(10\)]{.math .inline} year age group, beginning with [\(40\)]{.math .inline} and ending with age [\(79\)]{.math .inline}. The input variable [\(x\)]{.math .inline} is age (in years), and the response variable [\(y\)]{.math .inline} is muscle mass (in muscle mass units).</p><h1 id=part-1>Part (1)</h1><p>We assume a random sample [\(\{\mathcal{D}_i\}\)]{.math .inline} where [\(\mathcal{D}_i = (X_i,Y_i)\)]{.math .inline} is generated by the linear model [\(Y_i = \beta_0 + \beta_1 X_i + \epsilon_i\)]{.math .inline}. We are not particularly interested in the distribution of [\(X_i\)]{.math .inline} and instead seek to use it as an explanatory variable (input) for response variable [\(Y_i\)]{.math .inline} (output).</p><p>Thus, we are interested in estimating the parameters of the conditional distribution [\[ Y_i | X_i = x_i \sim \mathcal{N}(\beta_0 + \beta_1 x_i, \sigma^2). \]]{.math .display}</p><p>We fit the given data [\(\{\mathcal{d}_i\}\)]{.math .inline} where [\(\mathcal{d}_i = (x_i,y_i)\)]{.math .inline} to the linear regression model [\[ Y_i = \beta_0 + \beta_1 x_i + \epsilon_i \]]{.math .display} using the following R code:</p><div class="highlight sourceCode r"><pre tabindex=0 class=chroma><code class=language-fallback data-lang=fallback><span class=line><span class=cl>mass.data = read.table(&#39;CH01PR27.txt&#39;)
</span></span><span class=line><span class=cl>colnames(mass.data)=c(&#34;mass&#34;,&#34;age&#34;)
</span></span><span class=line><span class=cl>mass.mod = lm(mass ~ age, data=mass.data)
</span></span></code></pre></div><p>We compute the [\(t\)]{.math .inline}-statistic [\(t^* = \frac{b_1}{\operatorname{SE}(b_1)} \sim t(n-2)\)]{.math .inline} and the [\(p\)]{.math .inline}-value [\(p = \Pr\{t(n-2) > |t_*|\}\)]{.math .inline} with the following R code:</p><div class="highlight sourceCode r"><pre tabindex=0 class=chroma><code class=language-fallback data-lang=fallback><span class=line><span class=cl>beta1.stats = summary(mass.mod)$coefficients[2,]
</span></span><span class=line><span class=cl>beta1.stats
</span></span></code></pre></div><pre><code>##      Estimate    Std. Error       t value      Pr(&gt;|t|) 
## -1.189996e+00  9.019725e-02 -1.319326e+01  4.123987e-19
</code></pre><p>We see that [\(t^* = -13.193\)]{.math .inline} which has a [\(p\)]{.math .inline}-value less than [\(0.001\)]{.math .inline}.</p><h1 id=part-2>Part (2)</h1><p>We think of the the null hypothesis as a simplification to the model, which we prefer to the more complicated model (there is a probabilistic justification for this bias), [\[ H_0 \colon \beta_1 = 0 \qquad \text{(age has no effect on muscle mass)}. \]]{.math .display}</p><p>We obtained a [\(p\)]{.math .inline}-value of approximately [\(.000\)]{.math .inline}, and so the data is not compatible with the no effect model; we accept the model which includes age as a predictor for muscle mass.</p><h2 id=alterantive-formulation>Alterantive formulation</h2><p>Can we say the null hypothesis [\(H_0 : \beta_1 = 0\)]{.math .inline} is equivalent to [\[ H_0 : \text{no association between age and muscle mass} \]]{.math .display} since if [\(\beta_1 = 0\)]{.math .inline} then [\[ Y_1,\ldots,Y_n \overset{\rm{iid}}{\sim} \mathcal{N}(\beta_0,\sigma^2)? \]]{.math .display}</p><p>However, I am concerned that I am going beyond the model since our model is given by the conditional distribution of [\(Y_i|X_i\)]{.math .inline}. So, we may say that [\(x_i\)]{.math .inline} has no effect on [\(Y_i\)]{.math .inline}, but in general [\(y_i\)]{.math .inline} may effect [\(X_i\)]{.math .inline}. Clearly, in this case, we have scientific insight that one&rsquo;s muscle mass does not effect one&rsquo;s age.</p><p>Also, I&rsquo;m struggling with the wording . I find myself wanting to say that any outcome that has non-zero probability under the model is compatible with the model. Is it simply too subtle to say, &ldquo;Assuming the null hypothesis is true, then with probability [\(p\)]{.math .inline} the observed statistic or a more extreme value will have been observed.&rdquo; This may in fact be a bit much, especially for the less mathematically inclined, whom we wish to inform with our analysis. So, perhaps we are better off using phrasing like &ldquo;fail to reject the null hypothesis&rdquo; or &ldquo;the data is not compatible with the null model.&rdquo; I must confess that I sort of prefer &ldquo;fail to reject the null hypothesis,&rdquo; since it seems to be taking the stance that either model may be correct, but we lack sufficient data to reject the null model, which is some model we prefer for some reason, e.g., the null model is often the simplest model in a family of models.</p><p>I&rsquo;m still unsatisfied with my thoughts on this subject. On a related note, I enjoyed your discussion last Spring on the Bayesian perspective. When we combine this perspective with, say, a universal prior, perhaps we are getting closer to a sort of formalism for the scientific method (where the universal prior is a sort of formalism for Occam&rsquo;s razor).</p><h1 id=part-3>Part (3)</h1><p>Since both [\(t^* &lt; 0\)]{.math .inline} and [\(b_1 &lt; 0\)]{.math .inline}, the data supports the hypothesis of a negative association between age and muscle mass, i.e., as age increases muscle mass is expected to decrease.</p><h1 id=part-4>Part (4)</h1><p>We compute a [\(95\%\)]{.math .inline} confidence interval for [\(\beta_1\)]{.math .inline} with:</p><div class="highlight sourceCode r"><pre tabindex=0 class=chroma><code class=language-fallback data-lang=fallback><span class=line><span class=cl>alpha = 0.05
</span></span><span class=line><span class=cl>beta1.ci = round(confint(mass.mod, level=1-alpha)[2,],digits=3)
</span></span><span class=line><span class=cl>beta1.ci
</span></span></code></pre></div><pre><code>##  2.5 % 97.5 % 
## -1.371 -1.009
</code></pre><p>We see that [\(\beta_1\)]{.math .inline} has a [\(95\%\)]{.math .inline} confidence interval given by [\[ [-1.371,-1.009]. \]]{.math .display}</p><h1 id=part-5>Part (5)</h1><p>We can say more about the size of the effect and a measure of the estimation accuracy.</p><p>We make two observations about the CI for [\(\beta_1\)]{.math .inline}:</p><ol><li><p>All the values in the CI are distant from [\(0\)]{.math .inline}, and thus we can say there is strong evidence that age has a large effect.</p></li><li><p>The CI represents a relatively small range of values, and thus we can say the model is accurate, i.e., the data has a significant amount of information about [\(\beta_1\)]{.math .inline}.</p></li></ol><h1 id=part-6>Part (6)</h1><p>[\(\beta_0^<em>\)]{.math .inline} represents the mean muscle mass at the mean age in the sample, [\[ E(Y|x=\bar{x}) = \beta_0^</em>, \]]{.math .display} and thus [\[ b_0^* = \frac{1}{n} \sum_{i=1}^{n} Y_i. \]]{.math .display}</p><p>To compute the confidence interval for [\(b_0^*\)]{.math .inline}, I refit the model using the following R code:</p><div class="highlight sourceCode r"><pre tabindex=0 class=chroma><code class=language-fallback data-lang=fallback><span class=line><span class=cl>x = mass.data$age
</span></span><span class=line><span class=cl>y = mass.data$mass
</span></span><span class=line><span class=cl>x.bar = mean(x)
</span></span><span class=line><span class=cl>y.bar = mean(y)
</span></span><span class=line><span class=cl>x.star = x - x.bar
</span></span><span class=line><span class=cl>star.mod = lm(y ~ x.star, data=mass.data)
</span></span><span class=line><span class=cl>beta0.star.ci = round(confint(star.mod)[1,],digits=3)
</span></span><span class=line><span class=cl>beta0.star.ci
</span></span></code></pre></div><pre><code>##  2.5 % 97.5 % 
## 82.855 87.079
</code></pre><p>We see that [\(\beta_0^*\)]{.math .inline} has a [\(95\%\)]{.math .inline} confidence interval given by [\[ [82.855,87.079]. \]]{.math .display}</p><h1 id=part-7>Part (7)</h1><p>We estimate that the mean muscle mass for all women at the center value of age ([\(\bar{x} = 59.983\)]{.math .inline}) is between 82.855 and 87.079.</p></div><nav class=post-navigation><a href=../../../probsets/stat482/stat482-hw3/ class=nav-prev><span class=nav-label>← Previous</span>
<span class=nav-title>Regression Analysis - STAT 482 - Problem Set 3</span>
</a><a href=../../../probsets/stat482/stat482-hw10/ class=nav-next><span class=nav-label>Next →</span>
<span class=nav-title>Regression Analysis - STAT 482 - Problem Set 10</span></a></nav></article></div></div></main><footer class=elegant-footer role=contentinfo aria-label="Site footer"><div class=footer-content><div class=footer-about><h3>metafunctor</h3><p>Research engineer and computer scientist specializing in machine learning, statistical computing, and open source software development.</p><nav aria-label="Social media links" class=social-links><a href=https://twitter.com/queelius target=_blank rel="noopener noreferrer" aria-label=Twitter><i class="fab fa-twitter" aria-hidden=true></i>
</a><a href=https://github.com/queelius target=_blank rel="noopener noreferrer" aria-label=GitHub><i class="fab fa-github" aria-hidden=true></i>
</a><a href=https://www.linkedin.com/in/alexander-towell-487015151/ target=_blank rel="noopener noreferrer" aria-label=LinkedIn><i class="fab fa-linkedin" aria-hidden=true></i>
</a><a href=../../../index.xml target=_blank rel="noopener noreferrer" aria-label=RSS><i class="fas fa-rss" aria-hidden=true></i>
</a><a href=mailto:lex@metafunctor.com target=_blank rel="noopener noreferrer" aria-label=Email><i class="fas fa-envelope" aria-hidden=true></i>
</a><a href=https://keybase.io/queelius target=_blank rel="noopener noreferrer" aria-label=Keybase><i class="fab fa-keybase" aria-hidden=true></i>
</a><a href=https://www.youtube.com/@queelius target=_blank rel="noopener noreferrer" aria-label=YouTube><i class="fab fa-youtube" aria-hidden=true></i>
</a><a href="https://scholar.google.com/citations?view_op=list_works&amp;hl=en&amp;user=E9mnFzQAAAAJ" target=_blank rel="noopener noreferrer" aria-label="Google Scholar"><i class="fas fa-graduation-cap" aria-hidden=true></i>
</a><a href="https://orcid.org/my-orcid?orcid=0000-0001-6443-9897" target=_blank rel="noopener noreferrer" aria-label=ORCID><i class="fab fa-orcid" aria-hidden=true></i></a></nav></div><nav class=footer-section aria-labelledby=footer-content><h4 id=footer-content>Content</h4><div class=footer-links><a href=https://metafunctor.com/post/>Posts</a>
<a href=https://metafunctor.com/papers/>Papers</a>
<a href=https://metafunctor.com/series/>Series</a>
<a href=https://metafunctor.com/publications/>Publications</a>
<a href=https://metafunctor.com/writing/>Writing</a></div></nav><nav class=footer-section aria-labelledby=footer-code><h4 id=footer-code>Code</h4><div class=footer-links><a href=https://metafunctor.com/projects/>Projects</a>
<a href=https://github.com/queelius target=_blank rel="noopener noreferrer">GitHub</a>
<a href=https://pypi.org/user/queelius/ target=_blank rel="noopener noreferrer">PyPI</a></div></nav><nav class=footer-section aria-labelledby=footer-connect><h4 id=footer-connect>Connect</h4><div class=footer-links><a href=https://metafunctor.com/about/>About</a>
<a href=mailto:lex@metafunctor.com>Contact</a>
<a href=https://metafunctor.com/index.xml type=application/rss+xml>RSS Feed</a></div></nav></div><div class=footer-bottom><p class=copyright>© 2026 Alex Towell. All rights reserved.</p><p class=accessibility-note><a href=#main-content>Back to top</a></p></div></footer><script src=../../../js/performance-optimizations.js defer></script><script src=../../../js/performance-enhancements.js defer></script><script src=../../../js/mobile-menu.js defer></script><script src=../../../js/modern-interactions.js defer></script><script src=../../../js/search.js defer></script><script src=../../../js/reading-progress.js defer></script><script src=../../../js/copy-code.js defer></script><script src=../../../js/anchor-links.js defer></script><button id=back-to-top aria-label="Back to top" style="display:none;position:fixed;bottom:30px;right:30px;z-index:1000;background:linear-gradient(135deg,#667eea 0%,#764ba2 100%);color:#fff;border:none;border-radius:50%;width:50px;height:50px;cursor:pointer;box-shadow:0 4px 15px rgba(102,126,234,.4);transition:all .3s ease">
<i class="fas fa-arrow-up"></i>
</button>
<script>const backToTop=document.getElementById("back-to-top");window.addEventListener("scroll",()=>{window.scrollY>300?backToTop.style.display="block":backToTop.style.display="none"}),backToTop.addEventListener("click",()=>{window.scrollTo({top:0,behavior:"smooth"})})</script><script data-goatcounter=https://queelius.goatcounter.com/count async src=//gc.zgo.at/count.js></script></body></html>